// nim-kit-vue-ui-h5/src/components/NEUIKit/Conversation/conversation-item-read.vue
<template>
  <div
    class="p2p-msg-receipt-wrapper"
    v-if="
      conversationType ===
        V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P &&
      p2pMsgReceiptVisible
    "
  >
    <div v-if="p2pMsgRotateDeg == 360" class="icon-read-wrapper">
      <Icon type="icon-read" :size="16"></Icon>
    </div>
    <div v-else class="sector">
      <span
        class="cover-1"
        :style="`transform: rotate(${p2pMsgRotateDeg}deg)`"
      ></span>
      <span
        :class="p2pMsgRotateDeg >= 180 ? 'cover-2 cover-3' : 'cover-2'"
      ></span>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, getCurrentInstance } from "vue";
import Icon from "../CommonComponents/Icon.vue";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import type {
  V2NIMConversationForUI,
  V2NIMLocalConversationForUI,
} from "@xkit-yx/im-store-v2/dist/types/src/types";
const { proxy } = getCurrentInstance()!; // 获取组件实例

const props = withDefaults(
  defineProps<{
    conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI;
  }>(),
  {}
);

// 是否需要显示 p2p 消息、p2p会话列表消息已读未读，默认 false
const p2pMsgReceiptVisible =
  proxy?.$UIKitStore.localOptions.p2pMsgReceiptVisible;

const conversationType =
  proxy?.$NIM.V2NIMConversationIdUtil.parseConversationType(
    props.conversation.conversationId
  );
const p2pMsgRotateDeg = computed(() => {
  return (props?.conversation?.msgReceiptTime || 0) >=
    (props?.conversation?.lastMessage?.messageRefer?.createTime || 0)
    ? 360
    : 0;
});
</script>

<style scoped>
/* 消息已读状态容器 */
.p2p-msg-receipt-wrapper {
  width: 22px;
  height: 22px;
  overflow: hidden;
  line-height: 18px;
  vertical-align: bottom;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 已读图标容器 */
.icon-read-wrapper {
  margin: 0 3px 0 0;
  width: 18px;
  height: 18px;
  overflow: hidden;
  display: flex;
  align-items: center;
}

/* 扇形进度容器 */
.sector {
  display: inline-block;
  position: relative;
  overflow: hidden;
  border: 2px solid #4c84ff;
  width: 14px;
  height: 14px;
  background-color: #fff;
  border-radius: 50%;
  margin: 0 3px 0 0;
}

/* 扇形进度遮罩层1 */
.cover-1 {
  position: absolute;
  top: 0;
  width: 50%;
  height: 100%;
  background-color: #4c84ff;
  transform-origin: right;
}

/* 扇形进度遮罩层2 */
.cover-2 {
  position: absolute;
  top: 0;
  width: 50%;
  height: 100%;
  background-color: #fff;
}

/* 扇形进度遮罩层3 */
.cover-3 {
  right: 0;
  background-color: #4c84ff;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/conversation/conversation-list/conversation-item-read.tsx
import React from 'react'
import { observer } from 'mobx-react-lite'
import Icon from '@/NEUIKit/common/components/Icon'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import type { V2NIMConversationForUI, V2NIMLocalConversationForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import './conversation-item-read.less'

interface ConversationItemReadProps {
  conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI
}

/**
 * 会话消息已读状态组件
 */
const ConversationItemRead: React.FC<ConversationItemReadProps> = observer(({ conversation }) => {
  const { store } = useStateContext()

  // 是否需要显示 p2p 消息、p2p会话列表消息已读未读，默认 false
  const p2pMsgReceiptVisible = store.localOptions.p2pMsgReceiptVisible

  // 计算旋转角度，表示已读状态
  const p2pMsgRotateDeg = (conversation?.msgReceiptTime || 0) >= (conversation?.lastMessage?.messageRefer?.createTime || 0) ? 360 : 0

  // 如果不是点对点会话或不显示已读状态，则不渲染
  if (conversation.type !== V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P || !p2pMsgReceiptVisible) {
    return null
  }

  return (
    <div className="nim-p2p-msg-receipt-wrapper">
      {p2pMsgRotateDeg === 360 ? (
        <div className="icon-read-wrapper">
          <Icon type="icon-read" size={16} />
        </div>
      ) : (
        <div className="sector">
          <span className="cover-1" style={{ transform: `rotate(${p2pMsgRotateDeg}deg)` }}></span>
          <span className={p2pMsgRotateDeg >= 180 ? 'cover-2 cover-3' : 'cover-2'}></span>
        </div>
      )}
    </div>
  )
})

export default ConversationItemRead
