// src/components/NEUIKit/Conversation/conversation-item.vue
<template>
  <div
    :class="[
      'conversation-item-container',
      {
        'show-action-list': showMoreActions,
        'stick-on-top': conversation.stickTop,
      },
    ]"
    @touchstart="handleTouchStart"
    @touchmove="handleTouchMove"
    @click="() => handleConversationItemClick()"
  >
    <div class="conversation-item-content">
      <div class="conversation-item-left">
        <div class="unread" v-if="unread">
          <div class="dot" v-if="isMute"></div>
          <div class="badge" v-else>{{ unread }}</div>
        </div>
        <Avatar :account="to" :avatar="teamAvatar" />
      </div>
      <div class="conversation-item-right">
        <div class="conversation-item-top">
          <Appellation
            class="conversation-item-title"
            v-if="
              conversation.type ===
              V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P
            "
            :account="to"
          />
          <span v-else class="conversation-item-title">
            {{ sessionName }}
          </span>
          <span class="conversation-item-time">{{ date }}</span>
        </div>
        <div class="conversation-item-desc">
          <span class="conversation-item-desc-span">
            <span v-if="beMentioned" class="beMentioned">
              {{ "[" + t("someoneText") + "@" + t("meText") + "]" }}
            </span>
            <ConversationItemIsRead
              v-if="showSessionUnread"
              :conversation="props.conversation"
            ></ConversationItemIsRead>
            <span
              v-if="props.conversation.lastMessage"
              class="conversation-item-desc-content"
            >
              <LastMsgContent :lastMessage="props.conversation.lastMessage" />
            </span>
          </span>
          <div class="conversation-item-state">
            <Icon
              v-if="isMute"
              iconClassName="conversation-item-desc-state"
              type="icon-xiaoximiandarao"
              color="#ccc"
            />
          </div>
        </div>
      </div>
    </div>
    <div class="right-action-list">
      <div
        v-for="action in moreActions"
        :key="action.type"
        :class="['right-action-item', action.class]"
        @click="() => handleClick(action.type)"
      >
        {{ action.name }}
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import Avatar from "../CommonComponents/Avatar.vue";
import Appellation from "../CommonComponents/Appellation.vue";
import Icon from "../CommonComponents/Icon.vue";
import { computed, onUpdated, getCurrentInstance } from "vue";
import dayjs from "dayjs";
import { t } from "../utils/i18n";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import {
  V2NIMConversationForUI,
  V2NIMLocalConversationForUI,
} from "@xkit-yx/im-store-v2/dist/types/types";
import ConversationItemIsRead from "./conversation-item-read.vue";
import LastMsgContent from "./conversation-item-last-msg-content.vue";
const props = withDefaults(
  defineProps<{
    conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI;
    showMoreActions?: boolean;
  }>(),
  { showMoreActions: false }
);
const { proxy } = getCurrentInstance()!; // 获取组件实例

const emit = defineEmits(["click", "delete", "stickyToTop", "leftSlide"]);

const moreActions = computed(() => {
  return [
    {
      name: props.conversation.stickTop
        ? t("deleteStickTopText")
        : t("addStickTopText"),
      class: "action-top",
      type: "action-top",
    },
    {
      name: t("deleteSessionText"),
      class: "action-delete",
      type: "action-delete",
    },
  ];
});

const handleClick = (type: string) => {
  if (type === "action-top") {
    emit("stickyToTop", props.conversation);
  } else {
    emit("delete", props.conversation);
  }
};

// 群头像
const teamAvatar = computed(() => {
  if (
    props.conversation.type ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    const { avatar } = props.conversation;
    return avatar;
  }
});

// 会话名称
const sessionName = computed(() => {
  if (props.conversation.name) {
    return props.conversation.name;
  }
  return props.conversation.conversationId;
});

const to = computed(() => {
  const res = proxy?.$NIM.V2NIMConversationIdUtil.parseConversationTargetId(
    props.conversation.conversationId
  );
  return res;
});

const date = computed(() => {
  const time =
    props.conversation.lastMessage?.messageRefer.createTime ||
    props.conversation.updateTime;
  // 如果最后一条消息时间戳不存在，则会话列表不显示
  if (!time) {
    return "";
  }
  const _d = dayjs(time);
  const isCurrentDay = _d.isSame(dayjs(), "day");
  const isCurrentYear = _d.isSame(dayjs(), "year");
  return _d.format(
    isCurrentDay ? "HH:mm" : isCurrentYear ? "MM-DD HH:mm" : "YYYY-MM-DD HH:mm"
  );
});

const max = 99;

const unread = computed(() => {
  return props.conversation.unreadCount > 0
    ? props.conversation.unreadCount > max
      ? `${max}+`
      : props.conversation.unreadCount + ""
    : "";
});

const isMute = computed(() => {
  return !!props.conversation.mute;
});

const beMentioned = computed(() => {
  return !!props.conversation.aitMsgs?.length;
});

const showSessionUnread = computed(() => {
  const myUserAccountId = proxy?.$NIM.V2NIMLoginService.getLoginUser();
  if (
    props.conversation.type ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P
  ) {
    return (
      props?.conversation?.lastMessage?.messageRefer.senderId ===
        myUserAccountId &&
      props?.conversation?.lastMessage?.messageType !==
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL &&
      props?.conversation?.lastMessage?.messageType !==
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION &&
      props?.conversation?.lastMessage?.sendingState ===
        V2NIMConst.V2NIMMessageSendingState
          .V2NIM_MESSAGE_SENDING_STATE_SUCCEEDED &&
      props?.conversation?.lastMessage?.lastMessageState !==
        V2NIMConst.V2NIMLastMessageState.V2NIM_MESSAGE_STATUS_REVOKE
    );
  } else {
    return false;
  }
});

// 左滑显示 action 动画
let startX = 0,
  startY = 0;
// 开始左滑
function handleTouchStart(event: TouchEvent) {
  startX = event.changedTouches[0].pageX;
  startY = event.changedTouches[0].pageY;
}

function handleTouchMove(event: TouchEvent) {
  const moveEndX = event.changedTouches[0].pageX;
  const moveEndY = event.changedTouches[0].pageY;
  const X = moveEndX - startX + 20;
  const Y = moveEndY - startY;
  if (Math.abs(X) > Math.abs(Y) && X > 0) {
    emit("leftSlide", null);
  } else if (Math.abs(X) > Math.abs(Y) && X < 0) {
    emit("leftSlide", props.conversation);
  }
}

function handleConversationItemClick() {
  if (props.showMoreActions) {
    emit("leftSlide", null);
    return;
  }
  emit("click", props.conversation);
}

onUpdated(() => {
  console.log("onUpdated", props.conversation.unreadCount);
});
</script>

<style scoped>
/* 基础容器 */
.conversation-item-container {
  position: relative;
  transition: transform 0.3s;
  z-index: 9;
}

.conversation-item-container.show-action-list {
  transform: translateX(-200px);
}

.conversation-item-container.stick-on-top {
  background: #f3f5f7;
}

.beMentioned {
  color: #ff4d4f;
}

.content {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* 右侧操作列表 */
.right-action-list {
  position: absolute;
  top: 0;
  right: -200px;
  bottom: 0;
  width: 200px;
}

.right-action-item {
  width: 100px;
  display: inline-block;
  color: #fff;
  text-align: center;
  height: 72px;
  line-height: 72px;
}

.action-top {
  background: #337eff;
}

.action-delete {
  background: #a8abb6;
}

/* 会话内容 */
.conversation-item-content {
  display: flex;
  align-items: center;
  padding: 10px 20px 10px 15px;
  height: 72px;
  box-sizing: border-box;
}

.conversation-item-left {
  position: relative;
}

.conversation-item-desc-span {
  display: flex;
  flex: 1;
  box-sizing: border-box;
  min-width: 0;
  overflow: hidden;
}

.conversation-item-state {
  display: inline-block;
  width: 26px;
  box-sizing: border-box;
  height: 22px;
}
.conversation-item-badge {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 10;
}

.conversation-item-right {
  flex: 1;
  width: 0;
  margin-left: 10px;
}

.conversation-item-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.conversation-item-time {
  font-size: 12px;
  color: #ccc;
  text-align: right;
  width: 90px;
  flex-shrink: 0;
}

.conversation-item-title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: rgb(51, 51, 51);
  font-size: 16px;
}

.conversation-item-desc {
  width: 100%;
  font-size: 13px;
  color: #999;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 22px;
  overflow: hidden;
}

.conversation-item-desc-state {
  margin-left: 10px;
}

.conversation-item-desc-content {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex: 1;
}

/* 未读标记 */
.dot {
  background-color: #ff4d4f;
  color: #fff;
  width: 10px;
  height: 10px;
  border-radius: 5px;
  box-sizing: border-box;
  z-index: 99;
}

.badge {
  background-color: #ff4d4f;
  color: #fff;
  font-size: 12px;
  min-width: 20px;
  height: 20px;
  line-height: 19px;
  border-radius: 10px;
  padding: 0 5px;
  box-sizing: border-box;
  text-align: center;
  z-index: 99;
  position: relative;
}

.unread {
  position: absolute;
  right: -4px;
  top: -2px;
  z-index: 99;
}

.conversation-item-desc-ait {
  display: inline-block;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/conversation/conversation-list/conversation-item.tsx
import React, { useState } from 'react'
import { observer } from 'mobx-react-lite'
import dayjs from 'dayjs'
import Avatar from '@/NEUIKit/common/components/Avatar'
import AvatarWithStatus from '@/NEUIKit/common/components/AvatarWithStatus'
import Appellation from '@/NEUIKit/common/components/Appellation'
import Icon from '@/NEUIKit/common/components/Icon'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import type { V2NIMConversationForUI, V2NIMLocalConversationForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import ConversationItemRead from './conversation-item-read'
import LastMsgContent from './conversation-item-last-msg-content'
import './conversation-item.less'

interface ConversationItemProps {
  conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI
  showMoreActions?: boolean
  onClick?: (conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI) => void
  onDelete?: (conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI) => void
  onStickyToTop?: (conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI) => void
  onLeftSlide?: (conversation: V2NIMConversationForUI | V2NIMLocalConversationForUI | null) => void
}

/**
 * 会话列表项组件
 */
const ConversationItem: React.FC<ConversationItemProps> = observer(
  ({ conversation, showMoreActions = false, onClick, onDelete, onStickyToTop, onLeftSlide }) => {
    const { t } = useTranslation()
    const { store } = useStateContext()

    // 触摸相关状态
    const [startX, setStartX] = useState(0)
    const [startY, setStartY] = useState(0)

    // 更多操作按钮
    const moreActions = [
      {
        name: conversation.stickTop ? t('deleteStickTopText') : t('addStickTopText'),
        class: 'action-top',
        type: 'action-top'
      },
      {
        name: t('deleteSessionText'),
        class: 'action-delete',
        type: 'action-delete'
      }
    ]

    // 处理操作按钮点击
    const handleActionClick = (type: string, e: React.MouseEvent) => {
      e.stopPropagation()

      if (type === 'action-top') {
        onStickyToTop?.(conversation)
      } else {
        onDelete?.(conversation)
      }
    }

    // 获取会话目标ID
    const to = store.nim.V2NIMConversationIdUtil.parseConversationTargetId(conversation.conversationId)

    // 获取群头像
    const teamAvatar = conversation.type === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM ? conversation.avatar : undefined

    // 获取会话名称
    const sessionName = conversation.name || conversation.conversationId

    // 格式化时间
    const formatDate = (): string => {
      const time = conversation.lastMessage?.messageRefer.createTime || conversation.updateTime

      if (!time) {
        return ''
      }

      const _d = dayjs(time)
      const isCurrentDay = _d.isSame(dayjs(), 'day')
      const isCurrentYear = _d.isSame(dayjs(), 'year')

      return _d.format(isCurrentDay ? 'HH:mm' : isCurrentYear ? 'MM-DD HH:mm' : 'YYYY-MM-DD HH:mm')
    }

    // 未读数量显示格式化
    const max = 99
    const unread = conversation.unreadCount > 0 ? (conversation.unreadCount > max ? `${max}+` : `${conversation.unreadCount}`) : ''

    // 是否静音
    const isMute = !!conversation.mute

    // 是否有@消息
    // 1. 优先检查 aitMsgs（SDK维护的@消息列表）
    // 2. 如果 aitMsgs 为空但有未读消息，则检查最后一条消息的 serverExtension（用于免打扰状态下的补充检测）
    // 3. 消息已读后（unreadCount 为 0 且 aitMsgs 为空），不再显示@提示
    const beMentioned = (() => {
      // 如果 aitMsgs 有值，直接使用（SDK会在消息已读后清空）
      if (conversation.aitMsgs?.length) {
        return true
      }
      
      // 如果没有未读消息，不显示@提示
      if (conversation.unreadCount === 0) {
        return false
      }
      
      // 有未读消息时，检查最后一条消息是否@了当前用户（用于免打扰状态下的补充检测）
      const lastMsg = conversation.lastMessage
      if (!lastMsg?.serverExtension) {
        return false
      }
      
      try {
        const ext = JSON.parse(lastMsg.serverExtension)
        if (!ext?.yxAitMsg) {
          return false
        }
        
        const myAccountId = store.nim.V2NIMLoginService.getLoginUser()
        // 检查是否@了当前用户或@了所有人
        return myAccountId in ext.yxAitMsg || 'ait_all' in ext.yxAitMsg
      } catch {
        return false
      }
    })()

    // 是否显示消息已读状态
    const showSessionUnread = (() => {
      const myUserAccountId = store.nim.V2NIMLoginService.getLoginUser()

      if (conversation.type === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P) {
        return (
          conversation?.lastMessage?.messageRefer.senderId === myUserAccountId &&
          conversation?.lastMessage?.messageType !== V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL &&
          conversation?.lastMessage?.messageType !== V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION &&
          conversation?.lastMessage?.sendingState === V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_SUCCEEDED &&
          conversation?.lastMessage?.lastMessageState !== V2NIMConst.V2NIMLastMessageState.V2NIM_MESSAGE_STATUS_REVOKE
        )
      }

      return false
    })()

    // 处理触摸开始
    const handleTouchStart = (event: React.TouchEvent) => {
      setStartX(event.changedTouches[0].pageX)
      setStartY(event.changedTouches[0].pageY)
    }

    // 处理触摸移动
    const handleTouchMove = (event: React.TouchEvent) => {
      const moveEndX = event.changedTouches[0].pageX
      const moveEndY = event.changedTouches[0].pageY
      const X = moveEndX - startX + 20
      const Y = moveEndY - startY

      if (Math.abs(X) > Math.abs(Y) && X > 0) {
        // 右滑，收起操作栏
        onLeftSlide?.(null)
      } else if (Math.abs(X) > Math.abs(Y) && X < 0) {
        // 左滑，展示操作栏
        onLeftSlide?.(conversation)
      }
    }

    // 处理会话项点击
    const handleConversationItemClick = () => {
      if (showMoreActions) {
        // 如果当前显示操作栏，点击应该收起
        onLeftSlide?.(null)
        return
      }
      onClick?.(conversation)
    }

    // CSS 类名
    const containerClassName = ['nim-conversation-item-container', showMoreActions ? 'show-action-list' : '', conversation.stickTop ? 'stick-on-top' : '']
      .filter(Boolean)
      .join(' ')

    return (
      <div className={containerClassName} onTouchStart={handleTouchStart} onTouchMove={handleTouchMove} onClick={handleConversationItemClick}>
        <div className="conversation-item-content">
          <div className="conversation-item-left">
            {unread && <div className="unread">{isMute ? <div className="dot"></div> : <div className="badge">{unread}</div>}</div>}
            {conversation.type === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P ? (
              <AvatarWithStatus account={to} />
            ) : (
              <Avatar account={to} avatar={teamAvatar} />
            )}
          </div>

          <div className="conversation-item-right">
            <div className="conversation-item-top">
              {conversation.type === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P ? (
                <Appellation className="conversation-item-title" account={to} />
              ) : (
                <span className="conversation-item-title">{sessionName}</span>
              )}
              <span className="conversation-item-time">{formatDate()}</span>
            </div>

            <div className="conversation-item-desc">
              <span className="conversation-item-desc-span">
                {beMentioned && <span className="beMentioned">{`[${t('someoneText')}@${t('meText')}]`}</span>}

                {showSessionUnread && <ConversationItemRead conversation={conversation} />}

                {conversation.lastMessage && (
                  <span className="conversation-item-desc-content">
                    <LastMsgContent lastMessage={conversation.lastMessage} />
                  </span>
                )}
              </span>

              <div className="conversation-item-state">
                {isMute && <Icon iconClassName="conversation-item-desc-state" style={{ color: '#ccc' }} type="icon-xiaoximiandarao" />}
              </div>
            </div>
          </div>
        </div>

        <div className="right-action-list">
          {moreActions.map((action) => (
            <div key={action.type} className={`right-action-item ${action.class}`} onClick={(e) => handleActionClick(action.type, e)}>
              {action.name}
            </div>
          ))}
        </div>
      </div>
    )
  }
)

export default ConversationItem
