// nim-kit-vue-ui-h5/src/components/NEUIKit/Team/team-setting/team-nick-edit.vue
<template>
  <div class="wrapper">
    <NavBar :title="t('nickInTeam')">
      <template v-slot:left>
        <div class="nav-bar-text" @click="back">{{ t("cancelText") }}</div>
      </template>
      <template v-slot:right>
        <div @click="onOk">
          {{ t("okText") }}
        </div>
      </template>
    </NavBar>
    <div class="userInfo-item-wrapper">
      <textarea
        class="nick-textarea"
        :maxlength="30"
        v-model="inputValue"
        :placeholder="t('nickInTeam')"
        rows="3"
      />
      <div v-if="inputValue" @click="clearInputValue" class="clear-icon-wrapper">
        <Icon
          iconClassName="clear-icon"
          type="icon-shandiao"
        ></Icon>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
// 此组件用于修改群昵称
import { autorun } from "mobx";
import { onUnmounted, ref, getCurrentInstance } from "vue";
import Icon from "../../CommonComponents/Icon.vue";
import NavBar from "../../CommonComponents/NavBar.vue";
import { t } from "../../utils/i18n";
import type { V2NIMTeamMember } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService";
import { onMounted } from "vue";
import RootStore from "@xkit-yx/im-store-v2";
import { useRouter } from "vue-router";
import { toast } from "../../utils/toast";
import { useTeamNotification } from "../../composables/useTeamNotification";

const router = useRouter();
const inputValue = ref("");
const myMemberInfo = ref<V2NIMTeamMember>();
let teamId = "";
let uninstallTeamMemberWatch = () => {};
const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore as RootStore;
useTeamNotification(() => teamId);

onMounted(() => {
  teamId = (router.currentRoute.value.query.teamId as string) || "";
  uninstallTeamMemberWatch = autorun(() => {
    const memberList = store?.teamMemberStore.getTeamMember(teamId, [
      store?.userStore.myUserInfo.accountId,
    ]);
    myMemberInfo.value = memberList?.[0];

    inputValue.value = myMemberInfo.value?.teamNick || "";
  });
});

const clearInputValue = () => {
  inputValue.value = "";
};

const onOk = () => {
  store?.teamMemberStore
    .updateMyMemberInfoActive({
      teamId,
      memberInfo: {
        teamNick: inputValue.value.trim(),
      },
    })
    .then(() => {
      back();
    })
    .catch(() => {
      toast.info(t("saveFailedText"));
    });
};

const back = () => {
  router.back();
};

onUnmounted(() => {
  uninstallTeamMemberWatch();
});
</script>

<style>
.wrapper {
  width: 100%;
  height: 100vh;
  box-sizing: border-box;
  background-color: rgb(245, 246, 247);
}
.nav-bar-text {
  color: rgb(20, 146, 209);
}

.userInfo-item-wrapper {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  background-color: #fff;
  border-radius: 8px;
  padding: 12px 16px 5px;
  margin: 10px 20px;
}
.nick-textarea {
  width: 100%;
  border: none;
  outline: none;
  resize: none;
  font-size: 16px;
  color: #000;
  line-height: 1.5;
  font-family: inherit;
  padding: 0;

  &::placeholder {
    color: #c0c4cc;
  }
}

.clear-icon-wrapper {
  flex-shrink: 0;
  cursor: pointer;
  margin-left: 8px;
  margin-top: 2px;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/team/team-setting/team-nick-edit.tsx
import React, { useState, useEffect, useCallback } from 'react'
import { observer } from 'mobx-react-lite'
import { useNavigate, useLocation } from '@/utils/router'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { toast } from '@/NEUIKit/common/utils/toast'
import { useTeamNotification } from '@/NEUIKit/common/hooks/useTeamNotification'

import NavBar from '@/NEUIKit/common/components/NavBar'
import Icon from '@/NEUIKit/common/components/Icon'

import './team-nick-edit.less'

/**
 * 群昵称编辑组件
 */
const TeamNickEdit: React.FC = observer(() => {
  const { t } = useTranslation()
  const { store } = useStateContext()
  const navigate = useNavigate()
  const location = useLocation()

  // 输入内容
  const [inputValue, setInputValue] = useState('')
  const params = new URLSearchParams(location.search)
  const id = params.get('teamId') || ''
  useTeamNotification(id)
  // 我的成员信息
  const myMemberInfo = store.teamMemberStore.getTeamMember(id, [store.userStore.myUserInfo.accountId])?.[0]

  // 输入变化
  const onInputChange = useCallback((value: string) => {
    setInputValue(value)
  }, [])

  // 输入框获取焦点
  const onInputFocus = useCallback(() => {}, [])

  // 清除输入内容
  const clearInputValue = useCallback(() => {
    setInputValue('')
  }, [])

  // 返回
  const back = useCallback(() => {
    navigate(-1)
  }, [])

  // 确认修改
  const onOk = useCallback(() => {
    store.teamMemberStore
      .updateMyMemberInfoActive({
        teamId: id,
        memberInfo: {
          teamNick: inputValue.trim()
        }
      })
      .then(() => {
        back()
      })
      .catch(() => {
        toast.info(t('saveFailedText'))
      })
  }, [id, inputValue])

  // 初始化数据和自动更新
  useEffect(() => {
    setInputValue(myMemberInfo?.teamNick || '')
  }, [myMemberInfo])

  return (
    <div className="team-nick-edit-wrapper">
      <NavBar
        title={t('nickInTeam')}
        leftContent={
          <div className="nav-bar-text" onClick={back}>
            {t('cancelText')}
          </div>
        }
        rightContent={<div onClick={onOk}>{t('okText')}</div>}
      />
      <div className="userInfo-item-wrapper">
        <textarea
          className="nick-textarea"
          onFocus={onInputFocus}
          maxLength={30}
          onChange={(e) => onInputChange(e.target.value)}
          value={inputValue}
          placeholder={t('nickInTeam')}
          rows={3}
        />
        {inputValue && (
          <div onClick={clearInputValue} className="clear-icon-wrapper">
            <Icon iconClassName="clear-icon" type="icon-shandiao" />
          </div>
        )}
      </div>
    </div>
  )
})

export default TeamNickEdit
