// src/components/NEUIKit/Chat/message/message-list.vue
<template>
  <div class="msg-list-wrapper" @touchstart="handleTapMessageList">
    <div
      id="message-scroll-list"
      scroll-y="true"
      :scroll-top="scrollTop"
      class="message-scroll-list"
      ref="messageListRef"
    >
      <div v-show="!noMore" @click="onLoadMore" class="view-more-text">
        {{ t("viewMoreText") }}
      </div>
      <div class="msg-tip" v-show="noMore">{{ t("noMoreText") }}</div>
      <div v-for="(item, index) in finalMsgs" :key="item.messageClientId">
        <MessageItem
          :msg="item"
          :index="index"
          :key="item.messageClientId"
          :reply-msgs-map="replyMsgsMap"
          :broadcastNewAudioSrc="broadcastNewAudioSrc"
        >
        </MessageItem>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {
  ref,
  computed,
  onBeforeMount,
  onUnmounted,
  getCurrentInstance,
  nextTick,
  onMounted,
} from "vue";
import MessageItem from "./message-item.vue";
import { caculateTimeago } from "../../utils/date";
import { t } from "../../utils/i18n";
import { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/types";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import { autorun } from "mobx";
import { V2NIMTeam } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService";
import emitter from "../../utils/eventBus";
import { events } from "../../utils/constants";

const props = withDefaults(
  defineProps<{
    msgs: V2NIMMessageForUI[];
    conversationType: V2NIMConst.V2NIMConversationType;
    to: string;
    loadingMore?: boolean;
    noMore?: boolean;
    replyMsgsMap?: {
      [key: string]: V2NIMMessageForUI;
    };
  }>(),
  {}
);

const { proxy } = getCurrentInstance()!; // 获取组件实例
const messageListRef = ref<HTMLElement | null>(null);

onBeforeMount(() => {
  let team: V2NIMTeam | undefined = undefined;

  autorun(() => {
    team = proxy?.$UIKitStore.teamStore.teams.get(props.to);
  });

  if (
    props.conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    proxy?.$UIKitStore.teamMemberStore.getTeamMemberActive({
      teamId: props.to,
      queryOption: {
        limit: Math.max((team as unknown as V2NIMTeam)?.memberLimit || 0, 200),
        roleQueryType: 0,
      },
    });
  }

  emitter.on(events.AUDIO_URL_CHANGE, (url) => {
    broadcastNewAudioSrc.value = url as string;
  });

  emitter.on(events.ON_LOAD_MORE, () => {
    const msg = finalMsgs.value.filter(
      (item) =>
        !(
          item.messageType ===
            V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
          ["beReCallMsg", "reCallMsg"].includes(item.recallType || "")
        )
    )[0];
    if (msg) {
      emitter.emit(events.GET_HISTORY_MSG, msg);
    }
  });
});

onMounted(() => {
  emitter.on(events.ON_SCROLL_BOTTOM, scrollToBottom);
  let timer = setTimeout(() => {
    scrollToBottom();
    clearTimeout(timer);
  }, 100);
});

onUnmounted(() => {
  emitter.off(events.ON_SCROLL_BOTTOM, scrollToBottom);
  emitter.off(events.ON_LOAD_MORE);
  emitter.off(events.AUDIO_URL_CHANGE);
});

const scrollTop = ref(0);
const finalMsgs = computed(() => {
  const res: V2NIMMessageForUI[] = [];
  props.msgs.forEach((item, index) => {
    // 如果两条消息间隔超过5分钟，插入一条自定义时间消息
    if (
      index > 0 &&
      item.createTime - props.msgs[index - 1].createTime > 5 * 60 * 1000
    ) {
      res.push({
        ...item,
        messageClientId: "time-" + item.createTime,
        messageType: V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM,
        sendingState:
          V2NIMConst.V2NIMMessageSendingState
            .V2NIM_MESSAGE_SENDING_STATE_SUCCEEDED,
        // @ts-ignore
        timeValue: caculateTimeago(item.createTime),
        renderKey: `${item.createTime + 1}`,
      });
    }
    res.push({
      ...item,
      // @ts-ignore
      renderKey: `${item.createTime}`,
    });
  });

  return res;
});

const broadcastNewAudioSrc = ref<string>("");

// 消息滑动到底部
const scrollToBottom = () => {
  nextTick(() => {
    if (messageListRef.value) {
      messageListRef.value.scrollTop = messageListRef.value.scrollHeight;
    }
  });
  // let timer = setTimeout(() => {
  //   if (messageListRef.value) {
  //     messageListRef.value.scrollTop = messageListRef.value.scrollHeight;
  //   }
  //   clearTimeout(timer);
  // }, 0);
};

// 加载更多消息
const onLoadMore = () => {
  const msg = finalMsgs.value.filter(
    (item) =>
      !(
        item.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        ["beReCallMsg", "reCallMsg"].includes(item.recallType || "")
      )
  )[0];
  emitter.emit(events.GET_HISTORY_MSG, msg);
};

const handleTapMessageList = () => {
  // 点击消息列表时让输入框失焦
  const activeElement = document.activeElement as HTMLElement;
  if (activeElement && activeElement.tagName === "INPUT") {
    activeElement.blur();
  }

  emitter.emit(events.CLOSE_PANEL);
};
</script>

<style scoped>
.msg-list-wrapper {
  flex: 1;
  overflow: hidden;
  display: flex;
  height: 100%;
  box-sizing: border-box;
  padding: 0px 10px 5px 10px;
  transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
  background-color: #fff;
}

.msg-tip {
  text-align: center;
  color: #b3b7bc;
  font-size: 12px;
  margin-top: 10px;
  width: 100%;
}

.block {
  width: 100%;
  height: 40px;
}

.message-scroll-list {
  height: 100%;
  box-sizing: border-box;
  padding-bottom: 1px;
  overflow-y: auto;
  width: 100%;
}

.view-more-text {
  text-align: center;
  color: #b3b7bc;
  font-size: 15px;
  margin-top: 20px;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/chat/message/message-list/index.tsx
import React, { useEffect, useRef, useState } from 'react'
import { observer } from 'mobx-react-lite'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { caculateTimeago } from '@/NEUIKit/common/utils/date'
import { events, MSG_ID_FLAG } from '@/NEUIKit/common/utils/constants'
import emitter from '@/NEUIKit/common/utils/eventBus'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'

import MessageItem from '../message-item'
import { getMessageSelectKey } from '../message-multi-select/utils'
import './index.less'

interface MessageListProps {
  msgs: any[]
  conversationType: V2NIMConst.V2NIMConversationType
  to: string
  loadingOlder?: boolean
  hasOlder?: boolean
  replyMsgsMap?: {
    [key: string]: any
  }
  voiceTextMap?: Map<string, string>
  setVoiceText?: (messageClientId: string, text: string) => void
  anchorMessageClientId?: string
  anchorMode?: boolean
  loadingNewer?: boolean
  autoScrollToBottom?: boolean
  onLoadOlder?: (firstMsg?: any) => void | Promise<unknown>
  onLoadNewer?: (lastMsg?: any) => void | Promise<unknown>
  isMultiSelecting?: boolean
  selectedMessageIds?: string[]
  onToggleSelect?: (msg: any) => void
  onMultiSelect?: (msg: any) => void
}

const isNormalMsg = (item: any) => !(item.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && ['beReCallMsg', 'reCallMsg'].includes(item.recallType || ''))

/**
 * 消息列表组件
 */
const MessageList: React.FC<MessageListProps> = observer(
  ({
    msgs = [],
    conversationType,
    to,
    loadingOlder = false,
    hasOlder = true,
    replyMsgsMap = {},
    voiceTextMap = new Map(),
    setVoiceText,
    anchorMessageClientId = '',
    anchorMode = false,
    loadingNewer = false,
    autoScrollToBottom = true,
    onLoadOlder,
    onLoadNewer,
    isMultiSelecting = false,
    selectedMessageIds = [],
    onToggleSelect,
    onMultiSelect
  }) => {
    const { t } = useTranslation()
    const { store } = useStateContext()
    const messageListRef = useRef<HTMLDivElement>(null)
    const anchorScrollStateRef = useRef({
      anchorMessageClientId: '',
      scrolled: false
    })
    const pagingLockRef = useRef(false)
    const loadingOlderRef = useRef(loadingOlder)
    const loadingNewerRef = useRef(loadingNewer)
    const onLoadMoreRef = useRef<() => void>(() => undefined)
    const pendingPaginationRef = useRef<{
      direction: 'older' | 'newer'
      prevScrollHeight: number
      prevScrollTop: number
    } | null>(null)
    const [broadcastNewAudioSrc, setBroadcastNewAudioSrc] = useState('')

    /**
     * 处理消息列表，插入时间分割线
     */
    const finalMsgs = msgs.reduce((result: any[], item, index) => {
      // 如果两条消息间隔超过5分钟，插入一条自定义时间消息
      if (index > 0 && item.createTime - msgs[index - 1].createTime > 5 * 60 * 1000) {
        result.push({
          ...item,
          messageClientId: 'time-' + item.createTime,
          messageType: V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM,
          sendingState: V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_SUCCEEDED,
          timeValue: caculateTimeago(item.createTime),
          renderKey: `${item.createTime + 1}`
        })
      }
      result.push({
        ...item,
        renderKey: `${item.createTime}`
      })
      return result
    }, [])

    const getFirstNormalMsg = () => finalMsgs.find(isNormalMsg)

    const getLastNormalMsg = () => {
      const normalMsgs = finalMsgs.filter(isNormalMsg)
      return normalMsgs[normalMsgs.length - 1]
    }

    /**
     * 滚动到底部
     */
    const scrollToBottom = () => {
      if (messageListRef.current) {
        messageListRef.current.scrollTop = messageListRef.current.scrollHeight
      }
    }

    const scrollToAnchor = () => {
      if (!anchorMessageClientId) return false
      const el = document.getElementById(`${MSG_ID_FLAG}${anchorMessageClientId}`)
      if (!el) return false
      el.scrollIntoView({ block: 'center' })
      return true
    }

    const unlockPaginationAfterRender = () => {
      requestAnimationFrame(() => {
        const pending = pendingPaginationRef.current
        if (!pending || loadingOlderRef.current || loadingNewerRef.current) return

        if (messageListRef.current && pending.direction === 'older') {
          const nextScrollHeight = messageListRef.current.scrollHeight
          messageListRef.current.scrollTop = pending.prevScrollTop + (nextScrollHeight - pending.prevScrollHeight)
        }

        requestAnimationFrame(() => {
          if (loadingOlderRef.current || loadingNewerRef.current) return
          pagingLockRef.current = false
          pendingPaginationRef.current = null
        })
      })
    }

    const startPagination = (direction: 'older' | 'newer', load: () => void | Promise<unknown>) => {
      if (pagingLockRef.current || !messageListRef.current) return

      pagingLockRef.current = true
      pendingPaginationRef.current = {
        direction,
        prevScrollHeight: messageListRef.current.scrollHeight,
        prevScrollTop: messageListRef.current.scrollTop
      }

      const result = load()
      Promise.resolve(result).finally(() => {
        setTimeout(() => {
          if (!loadingOlderRef.current && !loadingNewerRef.current) {
            unlockPaginationAfterRender()
          }
        }, 0)
      })
    }

    /**
     * 加载更多消息
     */
    const onLoadMore = () => {
      if (pagingLockRef.current || loadingOlderRef.current || !onLoadOlder) return
      const msg = getFirstNormalMsg()
      if (!msg) return
      startPagination('older', () => onLoadOlder(msg))
    }

    useEffect(() => {
      onLoadMoreRef.current = onLoadMore
    })

    const handleScroll = () => {
      if (!messageListRef.current) return
      if (pagingLockRef.current || loadingOlderRef.current || loadingNewerRef.current) return

      const { scrollTop, scrollHeight, clientHeight } = messageListRef.current
      if (anchorMode && onLoadNewer && scrollHeight - scrollTop - clientHeight < 24) {
        const msg = getLastNormalMsg()
        if (msg) {
          startPagination('newer', () => onLoadNewer(msg))
        }
      }
      if (anchorMode && scrollTop < 24) {
        onLoadMore()
      }
    }

    /**
     * 处理点击消息列表
     */
    const handleTapMessageList = () => {
      // 点击消息列表时让输入框失焦
      const activeElement = document.activeElement as HTMLElement
      if (activeElement && activeElement.id === 'msg-input') {
        activeElement.blur()
      }

      emitter.emit(events.CLOSE_PANEL)
    }

    useEffect(() => {
      loadingOlderRef.current = loadingOlder
      loadingNewerRef.current = loadingNewer
    }, [loadingOlder, loadingNewer])

    useEffect(() => {
      const pending = pendingPaginationRef.current
      if (!pending || loadingOlder || loadingNewer) return
      unlockPaginationAfterRender()
    }, [finalMsgs.length, loadingOlder, loadingNewer])

    // 组件挂载时初始化
    useEffect(() => {
      const team = store.teamStore.teams.get(to)

      // 如果是群聊，加载群成员信息
      if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM) {
        store.teamMemberStore.getTeamMemberActive({
          teamId: to,
          queryOption: {
            limit: Math.max(team?.memberLimit || 0, 200),
            roleQueryType: 0
          }
        })
      }

      // 监听音频URL变化
      const handleAudioUrlChange = (url: string) => {
        setBroadcastNewAudioSrc(url)
      }

      // 监听加载更多
      const handleOnLoadMore = () => {
        onLoadMoreRef.current()
      }

      // 注册事件
      // emitter.on(events.AUDIO_URL_CHANGE, handleAudioUrlChange)
      emitter.on(events.ON_LOAD_MORE, handleOnLoadMore)
      if (autoScrollToBottom) {
        emitter.on(events.ON_SCROLL_BOTTOM, scrollToBottom)
      }

      // 初次加载完成后滚动到底部
      const timer = setTimeout(() => {
        if (anchorMessageClientId) {
          if (scrollToAnchor()) {
            anchorScrollStateRef.current = {
              anchorMessageClientId,
              scrolled: true
            }
          }
        } else if (autoScrollToBottom) {
          scrollToBottom()
        }
        clearTimeout(timer)
      }, 100)

      return () => {
        // emitter.off(events.AUDIO_URL_CHANGE, handleAudioUrlChange)
        emitter.off(events.ON_LOAD_MORE, handleOnLoadMore)
        if (autoScrollToBottom) {
          emitter.off(events.ON_SCROLL_BOTTOM, scrollToBottom)
        }
      }
    }, [autoScrollToBottom])

    useEffect(() => {
      if (!anchorMessageClientId) return
      if (anchorScrollStateRef.current.anchorMessageClientId !== anchorMessageClientId) {
        anchorScrollStateRef.current = {
          anchorMessageClientId,
          scrolled: false
        }
      }
      if (anchorScrollStateRef.current.scrolled) return

      const timer = setTimeout(() => {
        if (scrollToAnchor()) {
          anchorScrollStateRef.current = {
            anchorMessageClientId,
            scrolled: true
          }
        }
        clearTimeout(timer)
      }, 100)
    }, [anchorMessageClientId, finalMsgs.length])

    return (
      <div className="msg-list-wrapper" onTouchStart={handleTapMessageList} onClick={handleTapMessageList}>
        <div id="message-scroll-list" className="message-scroll-list" ref={messageListRef} onScroll={handleScroll}>
          {hasOlder && (
            <div className="view-more-text" onClick={onLoadMore}>
              {loadingOlder ? t('loadingMoreText') : t('viewMoreText')}
            </div>
          )}
          {!hasOlder && <div className="msg-tip">{t('noMoreText')}</div>}

          {finalMsgs.map((item, index) => (
            <MessageItem
              key={item.messageClientId || index}
              msg={item}
              index={index}
              replyMsgsMap={replyMsgsMap}
              broadcastNewAudioSrc={broadcastNewAudioSrc}
              voiceTextMap={voiceTextMap}
              setVoiceText={setVoiceText}
              isMultiSelecting={isMultiSelecting}
              selected={selectedMessageIds.includes(getMessageSelectKey(item))}
              onToggleSelect={onToggleSelect}
              onMultiSelect={onMultiSelect}
            />
          ))}

          {anchorMode && loadingNewer && <div className="msg-tip">{t('loadingMoreText')}</div>}
        </div>
      </div>
    )
  }
)

export default MessageList
