// nim-kit-react-ui-h5/src/NEUIKit/common/components/PersonSelect/index.tsx
import React, { useEffect, useState } from 'react'
import Avatar from '../Avatar'
import Appellation from '../Appellation'
import Empty from '../Empty'
import { t } from '../../utils/i18n'
import './index.less'

export interface PersonSelectItem {
  /**
   * 用户账号ID
   */
  accountId: string
  /**
   * 群组ID（可选）
   */
  teamId?: string
  /**
   * 是否禁用
   */
  disabled?: boolean
  /**
   * 是否选中
   */
  checked?: boolean
}

export interface PersonSelectProps {
  /**
   * 联系人列表
   */
  personList: PersonSelectItem[]
  /**
   * 是否显示按钮
   * @default true
   */
  showBtn?: boolean
  /**
   * 按钮文本
   * @default ""
   */
  btnText?: string
  /**
   * 是否为单选模式
   * @default false
   */
  radio?: boolean
  /**
   * 最大可选数量
   * @default Number.MAX_SAFE_INTEGER
   */
  max?: number
  /**
   * 选择变化事件
   */
  onCheckboxChange?: (selectList: string | string[]) => void
  /**
   * 按钮点击事件
   */
  onBtnClick?: () => void
  /**
   * 超过最大选择数量时触发
   */
  onMaxExceeded?: () => void
}

/**
 * 联系人选择组件
 */
const PersonSelect: React.FC<PersonSelectProps> = ({
  personList,
  showBtn = true,
  btnText = '',
  radio = false,
  max = Number.MAX_SAFE_INTEGER,
  onCheckboxChange,
  onBtnClick,
  onMaxExceeded
}) => {
  // 已选择的账号列表
  const [selectAccount, setSelectAccount] = useState<string[]>([])

  // 初始化选中状态
  useEffect(() => {
    const initialSelectedAccounts = personList.filter((item) => item.checked).map((item) => item.accountId)
    setSelectAccount(initialSelectedAccounts)
  }, [personList])

  // 处理单选变化
  const handleRadioChange = (event: React.ChangeEvent<HTMLInputElement>, accountId: string) => {
    event.preventDefault()
    const checked = event.target.checked
    const newSelectAccount = checked ? [accountId] : []
    setSelectAccount(newSelectAccount)
    onCheckboxChange?.(newSelectAccount)
  }

  // 处理多选变化
  const handleCheckboxChange = (event: React.MouseEvent, accountId: string) => {
    event.preventDefault()
    const isSelected = selectAccount.includes(accountId)
    let newSelectAccount: string[]

    if (isSelected) {
      // 如果已选中，则取消选择
      newSelectAccount = selectAccount.filter((id) => id !== accountId)
    } else {
      // 如果未选中，且未超过最大数量，则添加选择
      newSelectAccount = [...selectAccount, accountId]
      if (newSelectAccount.length > max) {
        onMaxExceeded?.()
        return // 已达最大选择数量
      }
    }

    setSelectAccount(newSelectAccount)
    onCheckboxChange?.(newSelectAccount)
  }

  // 处理按钮点击
  const handleBtnClick = () => {
    onBtnClick?.()
  }

  // 如果没有联系人，则显示空状态
  if (personList.length === 0) {
    return <Empty text={t('noFriendText')} />
  }

  return (
    <div className="nim-friend-select-wrapper">
      <div className="nim-member-wrapper">
        {/* 单选模式 */}
        {radio ? (
          <div className="nim-radio-group">
            {personList.map((item) => (
              <div className="nim-member-item" key={item.accountId}>
                <label className="nim-radio-label">
                  <input
                    type="radio"
                    className="nim-radio-input"
                    value={item.accountId}
                    checked={selectAccount.includes(item.accountId)}
                    disabled={item.disabled || (selectAccount.length >= max && !selectAccount.includes(item.accountId))}
                    onChange={(e) => handleRadioChange(e, item.accountId)}
                  />
                  <span className="nim-radio-custom"></span>
                  <Avatar className="nim-user-avatar" size={36} account={item.accountId} teamId={item.teamId} />
                  <div className="nim-user-name">
                    <Appellation account={item.accountId} teamId={item.teamId} />
                  </div>
                </label>
              </div>
            ))}
          </div>
        ) : (
          /* 多选模式 */
          <div className="nim-checkbox-group">
            {personList.map((item) => {
              const isChecked = selectAccount.includes(item.accountId)
              const isMaxReached = selectAccount.length >= max && !isChecked
              const isDisabled = item.disabled || isMaxReached
              return (
              <div className="nim-member-item" key={item.accountId}>
                <label
                  className={`nim-checkbox-label${isDisabled ? ' disabled' : ''}`}
                  onClick={(e) => {
                    if (item.disabled) return
                    if (isMaxReached) {
                      onMaxExceeded?.()
                      return
                    }
                    handleCheckboxChange(e, item.accountId)
                  }}
                >
                  <span className={`nim-checkbox-custom${isChecked ? ' checked' : ''}${isDisabled ? ' disabled' : ''}`}>
                    {isChecked && (
                      <svg viewBox="0 0 18 18" width="18" height="18" fill="none">
                        <path d="M5.15 8.74L8 12.5L14.24 7.18" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    )}
                  </span>
                  <Avatar className="nim-user-avatar" size={36} account={item.accountId} teamId={item.teamId} />
                  <div className="nim-user-name">
                    <Appellation account={item.accountId} teamId={item.teamId} />
                  </div>
                </label>
              </div>
            )})}
          </div>
        )}
      </div>

      {/* 确认按钮 */}
      {showBtn && btnText && (
        <div className="nim-ok-btn">
          <button onClick={handleBtnClick}>{btnText}</button>
        </div>
      )}
    </div>
  )
}

export default PersonSelect

// nim-kit-vue-ui-h5/src/components/NEUIKit/CommonComponents/PersonSelect.vue
<template>
  <div v-if="personList.length > 0" class="friend-select-wrapper">
    <div class="member-wrapper">
      <!-- 单选模式 -->
      <div v-if="radio" class="radio-group">
        <div
          class="member-item"
          v-for="item in personList"
          :key="item.accountId"
        >
          <label class="radio-label">
            <input
              type="radio"
              class="radio-input"
              :value="item.accountId"
              :checked="selectAccount.includes(item.accountId)"
              :disabled="
                item.disabled ||
                (selectAccount.length >= max &&
                  !selectAccount.includes(item.accountId))
              "
              @change="handleRadioChange($event, item.accountId)"
            />
            <span class="radio-custom"></span>
            <Avatar class="user-avatar" size="36" :account="item.accountId" />
            <div class="user-name">
              <Appellation :account="item.accountId" :teamId="item.teamId" />
            </div>
          </label>
        </div>
      </div>
      <!-- 多选模式 -->
      <div v-else class="checkbox-group">
        <div
          class="member-item"
          v-for="item in personList"
          :key="item.accountId"
        >
          <label
            class="checkbox-label"
            :class="{
              disabled:
                item.disabled ||
                (selectAccount.length >= max &&
                  !selectAccount.includes(item.accountId)),
            }"
            @click.prevent="
              item.disabled ? null :
              (selectAccount.length >= max &&
                !selectAccount.includes(item.accountId)) ? $emit('maxExceeded') :
              handleCheckboxChange($event, item.accountId)
            "
          >
            <span
              class="checkbox-custom"
              :class="{
                checked: selectAccount.includes(item.accountId),
                disabled:
                  item.disabled ||
                  (selectAccount.length >= max &&
                    !selectAccount.includes(item.accountId)),
              }"
            >
              <svg
                v-if="selectAccount.includes(item.accountId)"
                viewBox="0 0 18 18"
                width="18"
                height="18"
                fill="none"
              >
                <path
                  d="M5.15 8.74L8 12.5L14.24 7.18"
                  stroke="#fff"
                  stroke-width="1.6"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </span>
            <Avatar class="user-avatar" size="36" :account="item.accountId" />
            <div class="user-name">
              <Appellation :account="item.accountId" :teamId="item.teamId" />
            </div>
          </label>
        </div>
      </div>
    </div>
  </div>
  <Empty v-else :text="t('noFriendText')"></Empty>
</template>

<script lang="ts" setup>
import Avatar from "./Avatar.vue";
import Appellation from "./Appellation.vue";
import Empty from "./Empty.vue";
import { t } from "../utils/i18n";
import { ref, onMounted } from "vue";

export type PersonSelectItem = {
  accountId: string;
  teamId?: string;
  disabled?: boolean;
  checked?: boolean;
};

const props = withDefaults(
  defineProps<{
    personList: PersonSelectItem[];
    showBtn?: boolean;
    btnText?: string;
    radio?: boolean;
    max?: number;
  }>(),
  {
    showBtn: true,
    btnText: "",
    radio: false,
    max: Number.MAX_SAFE_INTEGER,
  }
);

const selectAccount = ref<string[]>([]);

onMounted(() => {
  selectAccount.value = props.personList
    .filter((item) => item.checked)
    .map((item) => item.accountId);
});

const $emit = defineEmits<{
  (event: "checkboxChange", selectList: string | string[]): void;
  (event: "onBtnClick"): void;
  (event: "maxExceeded"): void;
}>();

const onBtnClick = () => {
  $emit("onBtnClick");
};

const handleRadioChange = (event: Event, accountId: string) => {
  event.preventDefault(); // 添加这行，阻止默认行为

  const checked = (event.target as HTMLInputElement).checked;
  selectAccount.value = checked ? [accountId] : [];
  $emit("checkboxChange", selectAccount.value);
};

const handleCheckboxChange = (event: Event, accountId: string) => {
  event.preventDefault(); // 添加这行，阻止默认行为
  const newChecked = !selectAccount.value.includes(accountId);
  
  if (newChecked) {
    selectAccount.value = [...selectAccount.value, accountId];
  } else {
    selectAccount.value = selectAccount.value.filter((id) => id !== accountId);
  }
  $emit("checkboxChange", selectAccount.value);
};
</script>

<style scoped>
/* 好友选择容器 */
.friend-select-wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
}

/* 成员列表容器 */
.member-wrapper {
  overflow-y: auto;
  height: 100%;
  width: 100%;
  padding-top: 10px;
  display: flex;
  flex-direction: column; /* 添加这行 */
  overflow-y: auto;
  overflow-x: hidden;
}

/* 成员项 */
.member-item {
  display: flex;
  flex-direction: row;
  align-items: center;
  padding: 8px 20px;
}

/* 用户头像 */
.member-item .user-avatar {
  margin: 0 14px;
}

/* 用户名称 */
.member-item .user-name {
  max-width: 230px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: #000;
  font-size: 16px;
}

/* 复选框 */
.member-item .checkbox {
  margin-right: 8px;
}

/* 确认按钮 */
.ok-btn {
  margin-bottom: 15px;
}

/* 自定义单选框样式 */
.radio-label,
.checkbox-label {
  display: flex;
  align-items: center;
  cursor: pointer;
  width: 100%;
}

.radio-input,
.checkbox-input {
  position: absolute;
  opacity: 0;
}

.radio-custom,
.checkbox-custom {
  width: 18px;
  height: 18px;
  border: 1px solid #969aa0;
  border-radius: 50%;
  position: relative;
  transition: all 0.3s;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.checkbox-custom.checked {
  background: #337eff;
  border-color: #337eff;
}

.checkbox-custom.disabled {
  background-color: #f5f7fa;
  border-color: #e4e7ed;
  cursor: not-allowed;
}

.checkbox-label.disabled {
  cursor: not-allowed;
}
</style>
