// nim-kit-vue-ui-h5/src/components/NEUIKit/CommonComponents/PreviewText.vue
<template>
  <div
    v-if="visible && msg"
    class="collection-preview-mask collection-text-preview-mask"
    @click="handleClose"
  >
    <div class="collection-text-preview" @click.stop>
      <div class="collection-text-preview-content">
        <MessageText :msg="msg" />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { onUnmounted, watch } from "vue";
import type { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/src/types";
import MessageText from "../Chat/message/message-text.vue";

const props = defineProps<{
  visible: boolean;
  msg?: V2NIMMessageForUI;
  onClose?: () => void;
}>();

const handleClose = () => {
  props.onClose?.();
};

watch(
  () => props.visible,
  (visible) => {
    document.body.style.overflow = visible ? "hidden" : "";
  },
  { immediate: true }
);

onUnmounted(() => {
  document.body.style.overflow = "";
});
</script>

<style scoped>
.collection-preview-mask {
  position: fixed;
  z-index: 9999;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
  box-sizing: border-box;
  overflow: hidden;
  background: rgba(0, 0, 0, 0.9);
}

.collection-text-preview-mask {
  background: #eef3f7;
}

.collection-text-preview {
  position: relative;
  width: 100%;
  max-width: calc(100vw - 48px);
  max-height: 78vh;
  overflow-y: auto;
  box-sizing: border-box;
}

.collection-text-preview-content {
  color: #333;
  font-size: 28px;
  line-height: 38px;
  text-align: center;
  word-break: break-word;
}

.collection-text-preview-content :deep(.msg-text) {
  text-align: center;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/common/components/PreviewText/index.tsx
import React, { useEffect } from 'react'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import MessageText from '@/NEUIKit/chat/message/message-text'
import './index.less'

export interface PreviewTextProps {
  visible: boolean
  msg?: V2NIMMessageForUI
  onClose?: () => void
}

const PreviewText: React.FC<PreviewTextProps> = ({ visible, msg, onClose }) => {
  useEffect(() => {
    if (visible) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }

    return () => {
      document.body.style.overflow = ''
    }
  }, [visible])

  if (!visible || !msg) return null

  return (
    <div className="collection-preview-mask collection-text-preview-mask" onClick={onClose}>
      <div className="collection-text-preview" onClick={(e) => e.stopPropagation()}>
        <div className="collection-text-preview-content">
          <MessageText msg={msg} />
        </div>
      </div>
    </div>
  )
}

export default PreviewText
