// nim-kit-react-ui-h5/src/NEUIKit/team/team-create/index.tsx
import React, { useState, useEffect, useMemo, useCallback } from 'react'
import { observer } from 'mobx-react-lite'
import { useNavigate, useLocation } from '@/utils/router'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { toast } from '@/NEUIKit/common/utils/toast'
import { neUiKitRouterPath } from '@/NEUIKit/common/utils/uikitRouter'

import NavBar from '@/NEUIKit/common/components/NavBar'
import PersonSelect from '@/NEUIKit/common/components/PersonSelect'

import './index.less'

interface PersonSelectItem {
  accountId: string
  teamId?: string
  disabled?: boolean
  checked?: boolean
}

/**
 * 创建群组组件
 */
const TeamCreate: React.FC = observer(() => {
  const { t } = useTranslation()
  const { store, nim } = useStateContext()
  const navigate = useNavigate()
  const location = useLocation()

  // 好友列表
  const [friendList, setFriendList] = useState<PersonSelectItem[]>([])
  // p2p 会话 ID
  const [p2pConversationId, setP2pConversationId] = useState('')
  // 防止重复创建标志
  const [flag, setFlag] = useState(false)

  // 选中的团队成员
  const teamMembers = useMemo(() => {
    return friendList.filter((item) => item.checked).map((item) => item.accountId)
  }, [friendList])

  // 初始化数据
  useEffect(() => {
    // 从 URL 查询参数获取 p2p 会话 ID
    const params = new URLSearchParams(location.search)
    const conversationId = params.get('p2pConversationId') || ''
    setP2pConversationId(conversationId)

    // 获取好友列表
    const list = store?.uiStore.friends.filter((item) => !store?.relationStore.blacklist.includes(item.accountId)) || []

    // 过滤掉当前会话的用户
    const formattedList = list.map((item) => ({ accountId: item.accountId })).filter((item) => item.accountId !== conversationId)

    setFriendList(formattedList)
  }, [])

  // 处理选择变化
  const checkboxChange = useCallback((selectList: string | string[]) => {
    if (Array.isArray(selectList)) {
      if (selectList.length > 200) {
        toast.info(t('maxSelectedText'))
        return
      }

      setFriendList((prevList) =>
        prevList.map((item) => ({
          accountId: item.accountId,
          checked: selectList.includes(item.accountId)
        }))
      )
    }
  }, [])

  // 创建群名称
  const createTeamName = useCallback(
    (members: string[]) => {
      const memberNickArr: string[] = []

      members.forEach((item) => {
        const appellation = store?.uiStore.getAppellation({ account: item })
        if (appellation) {
          memberNickArr.push(appellation)
        }
      })

      const ownerName = store?.userStore.myUserInfo.name || store?.userStore.myUserInfo.accountId
      const teamName = (ownerName + '、' + memberNickArr.join('、')).slice(0, 30)

      return teamName
    },
    [store.userStore.myUserInfo]
  )

  // 创建群头像
  const createTeamAvatar = useCallback(() => {
    const teamAvatarArr = [
      'https://yx-web-nosdn.netease.im/common/2425b4cc058e5788867d63c322feb7ac/groupAvatar1.png',
      'https://yx-web-nosdn.netease.im/common/62c45692c9771ab388d43fea1c9d2758/groupAvatar2.png',
      'https://yx-web-nosdn.netease.im/common/d1ed3c21d3f87a41568d17197760e663/groupAvatar3.png',
      'https://yx-web-nosdn.netease.im/common/e677d8551deb96723af2b40b821c766a/groupAvatar4.png',
      'https://yx-web-nosdn.netease.im/common/fd6c75bb6abca9c810d1292e66d5d87e/groupAvatar5.png'
    ]

    const index = Math.floor(Math.random() * 5)
    return teamAvatarArr[index]
  }, [])

  // 创建群组
  const createTeam = useCallback(async () => {
    try {
      if (flag) return

      if (teamMembers.length === 0) {
        toast.info(t('friendSelect'))
        return
      }

      if (teamMembers.length > 200) {
        toast.info(t('maxSelectedText'))
        return
      }

      setFlag(true)

      const accounts = p2pConversationId ? [...teamMembers, p2pConversationId] : [...teamMembers]

      const team = await store?.teamStore.createTeamActive({
        accounts,
        avatar: createTeamAvatar(),
        name: createTeamName(teamMembers)
      })

      const teamId = team?.teamId

      if (teamId) {
        const conversationId = nim.V2NIMConversationIdUtil.teamConversationId(teamId)
        store?.uiStore.selectConversation(conversationId)

        navigate(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`)
      }

      toast.info(t('createTeamSuccessText'))
    } catch (error) {
      toast.info(t('createTeamFailedText'))
    } finally {
      setFlag(false)
    }
  }, [flag, teamMembers, p2pConversationId])

  return (
    <div className="create-team-container">
      <NavBar
        title={t('createTeamText')}
        showLeft
        leftContent={<div className="nav-cancel-btn" onClick={() => navigate(-1)}>{t('cancelText')}</div>}
        rightContent={
          <div
            className={`create-team-button${teamMembers.length === 0 ? ' disabled' : ''}`}
            onClick={teamMembers.length === 0 ? undefined : createTeam}
          >
            {teamMembers.length > 0 ? `${t('yesText')}(${teamMembers.length})` : t('yesText')}
          </div>
        }
      />
      <div className="create-team-content">
        <PersonSelect personList={friendList} onCheckboxChange={checkboxChange} radio={false} showBtn={false} max={200} onMaxExceeded={() => toast.info(t('maxSelectedText'))} />
      </div>
    </div>
  )
})

export default TeamCreate

// nim-kit-vue-ui-h5/src/components/NEUIKit/Team/team-create/index.vue
<template>
  <div class="create-team-container">
    <NavBar :title="t('createTeamText')" showLeft>
      <template v-slot:left>
        <div class="nav-cancel-btn" @click="router.back()">{{ t('cancelText') }}</div>
      </template>
      <template v-slot:right>
        <div
          :class="['create-team-button', { disabled: teamMembers.length === 0 }]"
          @click="teamMembers.length > 0 && createTeam()"
        >
          {{ teamMembers.length > 0 ? `${t('yesText')}(${teamMembers.length})` : t('yesText') }}
        </div>
      </template>
    </NavBar>
    <div class="create-team-content">
      <PersonSelect
        :personList="friendList"
        @checkboxChange="checkboxChange"
        @maxExceeded="toast.info(t('maxSelectedText'))"
        :radio="false"
        :showBtn="false"
        :max="200"
      >
      </PersonSelect>
    </div>
  </div>
</template>

<script lang="ts" setup>
import PersonSelect, {
  type PersonSelectItem,
} from "../../CommonComponents/PersonSelect.vue";
import { ref, computed, onMounted, getCurrentInstance } from "vue";
import NavBar from "../../CommonComponents/NavBar.vue";
import { t } from "../../utils/i18n";
import { useRouter } from "vue-router";
import { toast } from "../../utils/toast";
import { neUiKitRouterPath } from "../../utils/uikitRouter";
const router = useRouter();

const { proxy } = getCurrentInstance()!; // 获取组件实例
const store = proxy?.$UIKitStore;
const nim = proxy?.$NIM;
const friendList = ref<PersonSelectItem[]>([]);

const teamMembers = computed(() => {
  return friendList.value
    .filter((item) => item.checked)
    .map((item) => item.accountId);
});

let p2pConversationId = "";

onMounted(() => {
  p2pConversationId =
    (router.currentRoute.value.query.p2pConversationId as string) || "";

  const list =
    store?.uiStore.friends.filter(
      (item) => !store?.relationStore.blacklist.includes(item.accountId)
    ) || [];
  friendList.value = list
    .map((item) => ({ accountId: item.accountId }))
    .filter((item) => {
      return item.accountId !== p2pConversationId;
    });
});

const checkboxChange = (selectList) => {
  if (selectList.length > 200) {
    toast.info(t("maxSelectedText"));
    return;
  }
  friendList.value = friendList.value.map((item) => {
    return {
      accountId: item.accountId,
      checked: selectList.includes(item.accountId),
    };
  });
};

const createTeamName = (teamMembers: string[]) => {
  const _memberNickArr: string[] = [];
  teamMembers.map((item) => {
    let appellation = store?.uiStore.getAppellation({ account: item });
    if (appellation) {
      _memberNickArr.push(appellation);
    }
  });

  const _ownerName =
    store?.userStore.myUserInfo.name || store?.userStore.myUserInfo.accountId;
  const _teamName = (_ownerName + "、" + _memberNickArr.join("、")).slice(
    0,
    30
  );
  return _teamName;
};

const createTeamAvatar = () => {
  const teamAvatarArr = [
    "https://yx-web-nosdn.netease.im/common/2425b4cc058e5788867d63c322feb7ac/groupAvatar1.png",
    "https://yx-web-nosdn.netease.im/common/62c45692c9771ab388d43fea1c9d2758/groupAvatar2.png",
    "https://yx-web-nosdn.netease.im/common/d1ed3c21d3f87a41568d17197760e663/groupAvatar3.png",
    "https://yx-web-nosdn.netease.im/common/e677d8551deb96723af2b40b821c766a/groupAvatar4.png",
    "https://yx-web-nosdn.netease.im/common/fd6c75bb6abca9c810d1292e66d5d87e/groupAvatar5.png",
  ];
  const _index = Math.floor(Math.random() * 5);
  return teamAvatarArr[_index];
};

let flag = false;

const createTeam = async () => {
  try {
    if (flag) return;
    if (teamMembers?.value?.length == 0) {
      toast.info(t("friendSelect"));
      return;
    }

    if (teamMembers?.value?.length > 200) {
      toast.info(t("maxSelectedText"));
      return;
    }
    flag = true;

    const team = await store?.teamStore.createTeamActive({
      accounts: p2pConversationId
        ? [...teamMembers.value, p2pConversationId]
        : [...teamMembers.value],
      avatar: createTeamAvatar(),
      name: createTeamName(teamMembers.value),
    });
    let teamId = team?.teamId;
    if (teamId) {
      store?.uiStore.selectConversation(
        nim.V2NIMConversationIdUtil.teamConversationId(teamId)
      );
      router.push(`${neUiKitRouterPath.chat}?conversationId=${nim.V2NIMConversationIdUtil.teamConversationId(teamId)}`);
    }

    toast.info(t("createTeamSuccessText"));
  } catch (error) {
    toast.info(t("createTeamFailedText"));
  } finally {
    flag = false;
  }
};
</script>

<style scoped>
.create-team-container {
  height: 100%;
  box-sizing: border-box;
  overflow: auto;
  background-color: #fff;
}

.create-team-container :deep(.nav-bar-container) {
  background-color: #FFF;
  border-bottom: 1px solid #e6e6e6;
}
/* .create-team-content {
  height: calc(100% - 60px);
} */
.select-wrapper {
  flex: 1;
}

.create-btn {
  color: #fff;
  background-color: rgb(20, 146, 209);
  padding: 10px;
  font-size: 16px;
  text-align: center;
}

.team-input-wrapper {
  display: flex;
  align-items: center;
}
.team-input {
  margin: 10px;
  background-color: #f2f4f5;
  padding: 4px;
  border-radius: 5px;
  flex: 1;
}

.button {
  width: 65px;
  height: 30px;
  font-size: 12px;
  text-align: center;
  line-height: 30px;
  margin-right: 5px;
  padding: 0;
  color: #5c9bed;
}

.placeholder {
  color: #a6adb6;
}

.create-team-button {
  color: #337eff;
  font-size: 16px;
  cursor: pointer;

  &.disabled {
    color: #b3cff7;
    cursor: not-allowed;
  }
}

.nav-cancel-btn {
  font-size: 16px;
  color: #333;
  cursor: pointer;
}
</style>
