// src/components/NEUIKit/Contact/contact-list/team-list.vue
<template>
  <div class="team-list-container">
    <NavBar :title="t('teamMenuText')" />
    <div class="team-list-content">
      <Empty v-if="teamList.length === 0" :text="t('teamEmptyText')" />
      <div
        v-else
        class="team-item"
        v-for="team in teamList"
        :key="team.teamId"
        @click="handleClick(team)"
      >
        <Avatar :account="team.teamId" :avatar="team.avatar" />
        <span class="team-name">{{ team.name }}</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
/** 群列表组件 */
import { autorun } from "mobx";
import { onUnmounted, ref, getCurrentInstance } from "vue";
import Empty from "../../CommonComponents/Empty.vue";
import Avatar from "../../CommonComponents/Avatar.vue";
import NavBar from "../../CommonComponents/NavBar.vue";
import { t } from "../../utils/i18n";
import { V2NIMTeam } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService";
import { useRouter } from "vue-router";
import RootStore from "@xkit-yx/im-store-v2";
import { neUiKitRouterPath } from "../../utils/uikitRouter";

const teamList = ref<V2NIMTeam[]>([]);

const router = useRouter();

const { proxy } = getCurrentInstance()!;

const store = proxy?.$UIKitStore as RootStore;
const nim = proxy?.$NIM;

const handleClick = async (team: V2NIMTeam) => {
  await store?.uiStore.selectConversation(
    nim.V2NIMConversationIdUtil.teamConversationId(team.teamId)
  );
  router.push(neUiKitRouterPath.chat);
};

/** 群列表监听 */
const teamListWatch = autorun(() => {
  teamList.value = store?.uiStore.teamList;
});

onUnmounted(() => {
  teamListWatch();
});
</script>

<style scoped>
.team-list-container {
  height: 100vh;
  box-sizing: border-box;
  background-color: #fff;
  overflow-y: auto;
}

.team-list-content {
  height: calc(100% - 60px - var(--status-bar-height));
  width: 100%;
  overflow-y: auto;
  overflow-x: hidden;
}

.team-item {
  display: flex;
  align-items: center;
  height: 60px;
  padding: 0 20px;
}

.team-name {
  margin-left: 10px;
  font-size: 16px;
  padding-right: 20px;
  color: #000;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/contact/team-list/index.tsx
import React, { useState, useEffect } from 'react'
import { useNavigate } from '@/utils/router'
import { observer } from 'mobx-react-lite'
import NavBar from '@/NEUIKit/common/components/NavBar'
import Empty from '@/NEUIKit/common/components/Empty'
import Avatar from '@/NEUIKit/common/components/Avatar'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { neUiKitRouterPath } from '@/NEUIKit/common/utils/uikitRouter'
import { V2NIMTeam } from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService'
import './index.less'

/**
 * 群组列表页面
 */
const TeamList: React.FC = observer(() => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { store } = useStateContext()

  // 群组列表本地状态
  const [teamList, setTeamList] = useState<V2NIMTeam[]>([])

  // 从store获取群组列表数据
  useEffect(() => {
    setTeamList(store.uiStore.teamList || [])
  }, [store.uiStore.teamList])

  // 点击群组进入聊天
  const handleTeamClick = async (team: V2NIMTeam) => {
    // 选择会话
    const conversationId = store.nim.V2NIMConversationIdUtil.teamConversationId(team.teamId)
    await store.uiStore.selectConversation(conversationId)

    // 跳转到聊天页面
    navigate(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`)
  }

  return (
    <div className="team-list-container">
      <NavBar title={t('teamMenuText')} />

      <div className="team-list-content">
        {teamList.length === 0 ? (
          <Empty text={t('teamEmptyText')} />
        ) : (
          teamList.map((team) => (
            <div className="team-item" key={team.teamId} onClick={() => handleTeamClick(team)}>
              <Avatar account={team.teamId} avatar={team.avatar} />
              <span className="team-name">{team.name}</span>
            </div>
          ))
        )}
      </div>
    </div>
  )
})

export default TeamList
