// nim-kit-react-ui-h5/src/NEUIKit/user/detail-item-edit/index.tsx
import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate } from '@/utils/router'
import { observer } from 'mobx-react-lite'
import NavBar from '@/NEUIKit/common/components/NavBar'
import Icon from '@/NEUIKit/common/components/Icon'
import Input from '@/NEUIKit/common/components/Input'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { toast } from '@/NEUIKit/common/utils/toast'
import { V2NIMUser } from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMUserService'
import './index.less'

/**
 * 用户详情项编辑组件
 */
const DetailItemEdit: React.FC = observer(() => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const { store } = useStateContext()

  // 获取要编辑的字段key（从URL参数中）
  const query = new URLSearchParams(location.search)
  const key: any = query.get('key') || ''

  // 状态
  const [inputValue, setInputValue] = useState('')
  const [showClearIcon, setShowClearIcon] = useState(false)
  // const [myUserInfo, setMyUserInfo] = useState<V2NIMUser | undefined>()
  const myUserInfo = store.userStore.myUserInfo

  // 各字段最大长度限制
  const maxlengthMap = {
    name: 15,
    mobile: 11,
    sign: 50,
    email: 30
  }

  // 监听用户信息变化并更新输入值
  useEffect(() => {
    if (key && myUserInfo) {
      let value = myUserInfo[key as keyof V2NIMUser] as string

      // 如果昵称没有值，则默认显示账号
      if (key === 'name' && !value) {
        value = myUserInfo.accountId
      }

      setInputValue(value || '')
    }
  }, [key])

  // 输入值变化处理
  const onInputChange = (str: string) => {
    setInputValue(str)
  }

  // 输入框获取焦点处理
  const onInputFocus = () => {
    setShowClearIcon(true)
  }

  // 清空输入值
  const clearInputValue = () => {
    setInputValue('')
  }

  // 确认修改用户信息
  const onUserInfoConfirm = () => {
    const value = inputValue

    // 手机号格式验证
    if (key === 'mobile' && !/^\d+(\.\d+)?$/.test(value) && value.trim() !== '') {
      toast.info(t('telErrorText'))
      return
    }

    // 邮箱格式验证
    if (key === 'email' && !/[a-zA-Z0-9]+([-_.][A-Za-zd]+)*@([a-zA-Z0-9]+[-.])+[A-Za-zd]{2,5}$/.test(value) && value.trim() !== '') {
      toast.info(t('emailErrorText'))
      return
    }

    // 保存用户信息
    if (key && myUserInfo) {
      store.userStore
        .updateSelfUserProfileActive({ ...myUserInfo, [key]: value })
        .then(() => {
          // 保存成功后返回上一页
          navigate(-1)
        })
        .catch(() => {
          toast.info(`${t('saveText')}${t(key)}${t('failText')}`)
        })
    }
  }

  return (
    <div className="nim-detail-item-edit">
      <NavBar
        title={t(key)}
        backgroundColor="transparent"
        rightContent={
          <div className="nav-bar-text" onClick={onUserInfoConfirm}>
            {t('okText')}
          </div>
        }
      />

      <div className="user-info-item-wrapper">
        <Input
          value={inputValue}
          onChange={onInputChange}
          onFocus={onInputFocus}
          maxLength={maxlengthMap[key as keyof typeof maxlengthMap]}
          className="detail-input"
        />
        {showClearIcon && (
          <div onClick={clearInputValue}>
            <Icon iconClassName="clear-icon" type="icon-shandiao" />
          </div>
        )}
      </div>
    </div>
  )
})

export default DetailItemEdit

// nim-kit-vue-ui-h5/src/components/NEUIKit/User/detail-item-edit.vue
<template>
  <div class="wrapper">
    <NavBar :title="t(key)" backgroundColor="transparent">
      <template v-slot:right>
        <div class="nav-bar-text" @click="onUserInfoConfirm">
          {{ t("okText") }}
        </div>
      </template>
    </NavBar>
    <div class="userInfo-item-wrapper">
      <Input
        :maxlength="maxlengthMap[key]"
        @input="onInputChange"
        @focus="onInputFocus"
        :modelValue="inputValue"
      />
      <div @click="clearInputValue">
        <Icon
          v-show="showClearIcon"
          iconClassName="clear-icon"
          type="icon-shandiao"
        ></Icon>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { autorun } from "mobx";
import { onMounted, onUnmounted, ref, getCurrentInstance } from "vue";
import Icon from "../CommonComponents/Icon.vue";
import NavBar from "../CommonComponents/NavBar.vue";
import { t } from "../utils/i18n";
import type { V2NIMUser } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMUserService";
import RootStore from "@xkit-yx/im-store-v2";
import { useRouter } from "vue-router";
import Input from "../CommonComponents/Input.vue";
import { showToast } from "../utils/toast";

const { proxy } = getCurrentInstance()!;
const router = useRouter();

const store = proxy?.$UIKitStore as RootStore;
const key = ref();
const inputValue = ref("");
const showClearIcon = ref(false);
const myUserInfo = ref<V2NIMUser>();
const maxlengthMap = {
  name: 15,
  mobile: 11,
  sign: 50,
  email: 30,
};

let uninstallMyUserInfoWatch = () => {};

onMounted(() => {
  key.value = (router.currentRoute.value.query.key as string) || "";

  uninstallMyUserInfoWatch = autorun(() => {
    myUserInfo.value = store.userStore.myUserInfo;

    if (key.value) {
      const _value = (myUserInfo.value as V2NIMUser)[key.value];
      inputValue.value = _value as string;
      // 如果昵称没有值，则默认显示账号
      if (key.value === "name" && !_value) {
        inputValue.value = myUserInfo.value?.accountId || "";
      }
    }
  });
});

const onInputChange = (event) => {
  const value = event.target.value;
  inputValue.value = value;
};

const onInputFocus = () => {
  showClearIcon.value = true;
};

const clearInputValue = () => {
  inputValue.value = "";
};

const onUserInfoConfirm = () => {
  const _value = inputValue.value;
  // 需要修改邮箱的正则，可在此处自定义
  if (
    key.value == "mobile" &&
    !/^\d+(\.\d+)?$/.test(_value) &&
    _value.trim() !== ""
  ) {
    showToast({
      message: t("telErrorText"),
      type: "info",
    });
    return;
  }
  // 需要修改邮箱的正则，可在此处自定义
  if (
    key.value == "email" &&
    !/[a-zA-Z0-9]+([-_.][A-Za-zd]+)*@([a-zA-Z0-9]+[-.])+[A-Za-zd]{2,5}$/.test(
      _value
    ) &&
    _value.trim() !== ""
  ) {
    showToast({
      message: t("emailErrorText"),
      type: "info",
    });
    return;
  }
  inputValue.value = _value;

  if (key.value) {
    store.userStore
      .updateSelfUserProfileActive({ ...myUserInfo.value, [key.value]: _value })
      .then(() => {
        router.back();
      })
      .catch(() => {
        showToast({
          message: t("saveText") + t(key.value || "") + t("failText"),
          type: "info",
        });
      });
  }
};

onUnmounted(() => {
  uninstallMyUserInfoWatch();
});
</script>

<style scoped>
.wrapper {
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  background-color: #E9EFF5;
}

.userInfo-item-wrapper {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background-color: #fff;
  margin: 22px 20px 0 20px;
  padding: 0 16px;
  border-radius: 8px;
  height: 40px;
}
.nav-bar-text {
  color: #666666;
  font-size: 16px;
}
.input {
  display: inline-block;
  width: 85%;
  padding: 6px;
}

.clear-icon {
  margin-right: 5px;
  z-index: 999;
}
</style>
