// nim-kit-react-ui-h5/src/NEUIKit/user/gender-edit/index.tsx
import React from 'react'
import { useNavigate } from '@/utils/router'
import { observer } from 'mobx-react-lite'
import NavBar from '@/NEUIKit/common/components/NavBar'
import Icon from '@/NEUIKit/common/components/Icon'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { toast } from '@/NEUIKit/common/utils/toast'
import './index.less'

/**
 * 性别编辑页面 —— 男/女两个选项平铺，当前已选项带蓝色勾，点击已勾选项无效
 */
const GenderEdit: React.FC = observer(() => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { store } = useStateContext()
  const myUserInfo = store.userStore.myUserInfo
  const currentGender = myUserInfo?.gender ?? 0 // 0 未知 1 男 2 女

  const handleSelect = async (gender: number) => {
    if (gender === currentGender) return // 点击已选项无效
    if (!myUserInfo) return
    try {
      await store.userStore.updateSelfUserProfileActive({ ...myUserInfo, gender })
      navigate(-1)
    } catch {
      toast.info(`${t('saveText')}${t('failText')}`)
    }
  }

  return (
    <div className="gender-edit-wrapper">
      <NavBar title={t('genderText')} backgroundColor="transparent" />
      <div className="gender-options">
        <div className="gender-option" onClick={() => handleSelect(1)}>
          <span className="gender-label">{t('man')}</span>
          {currentGender === 1 && <Icon type="icon-select-blue" size={16} />}
        </div>
        <div className="gender-option-divider" />
        <div className="gender-option" onClick={() => handleSelect(2)}>
          <span className="gender-label">{t('woman')}</span>
          {currentGender === 2 && <Icon type="icon-select-blue" size={16} />}
        </div>
      </div>
    </div>
  )
})

export default GenderEdit

// nim-kit-vue-ui-h5/src/components/NEUIKit/User/gender-edit.vue
<template>
  <div class="gender-edit-wrapper">
    <NavBar :title="t('genderText')" backgroundColor="transparent" />
    <div class="gender-options">
      <div class="gender-option" @click="() => handleSelect(1)">
        <span class="gender-label">{{ t("man") }}</span>
        <Icon v-if="currentGender === 1" type="icon-select-blue" :size="16" />
      </div>
      <div class="gender-option-divider" />
      <div class="gender-option" @click="() => handleSelect(2)">
        <span class="gender-label">{{ t("woman") }}</span>
        <Icon v-if="currentGender === 2" type="icon-select-blue" :size="16" />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed, getCurrentInstance, onUnmounted } from "vue";
import NavBar from "../CommonComponents/NavBar.vue";
import Icon from "../CommonComponents/Icon.vue";
import { t } from "../utils/i18n";
import { showToast } from "../utils/toast";
import { autorun } from "mobx";
import type { V2NIMUser } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMUserService";
import RootStore from "@xkit-yx/im-store-v2";
import router from "@/router";

const myUserInfo = ref<V2NIMUser>();

const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore as RootStore;

const uninstallMyUserInfoWatch = autorun(() => {
  myUserInfo.value = store?.userStore.myUserInfo;
});

const currentGender = computed(() => myUserInfo.value?.gender ?? 0);

const handleSelect = async (gender: number) => {
  if (gender === currentGender.value) return;
  if (!myUserInfo.value) return;
  try {
    await store?.userStore.updateSelfUserProfileActive({
      ...myUserInfo.value,
      gender,
    });
    router.back();
  } catch {
    showToast({
      message: `${t("saveText")}${t("failText")}`,
      type: "info",
    });
  }
};

onUnmounted(() => {
  uninstallMyUserInfoWatch();
});
</script>

<style scoped>
.gender-edit-wrapper {
  height: 100%;
  box-sizing: border-box;
  background-color: #e9eff5;
}

.gender-options {
  margin: 16px 20px 0 20px;
  overflow: hidden;
  border-radius: 12px;
  background-color: #fff;
}

.gender-option {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 46px;
  padding: 0 16px;
}

.gender-label {
  font-size: 16px;
  color: #333;
}

.gender-option-divider {
  height: 1px;
  background: #f5f8fc;
  margin: 0 16px;
}
</style>
