// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/index.vue
<template>
  <div class="msg-page-wrapper-h5">
    <NavBar :title="title" :subTitle="subTitle" :showLeft="true">
      <template v-slot:left>
        <div @click="backToConversation">
          <Icon type="icon-zuojiantou" :size="24"></Icon>
        </div>
      </template>
      <template v-slot:right>
        <div
          v-if="isMultiSelecting"
          class="msg-nav-cancel"
          @click="exitMultiSelect"
        >
          {{ t("cancelText") }}
        </div>
        <div v-else @click="handleSetting">
          <Icon type="icon-More" :size="24" />
        </div>
      </template>
    </NavBar>
    <div class="msg-alert">
      <NetworkAlert />
    </div>
    <div class="security-tip">
      <svg class="security-tip-icon" width="14" height="14" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M10.5 0C4.706 0 0 4.706 0 10.5S4.706 21 10.5 21 21 16.294 21 10.5 16.294 0 10.5 0zm.75 15h-1.5v1.5h1.5V15zm-1.5-2V4.5h1.5V13h-1.5z" fill="#FC596A"/>
      </svg>{{ t("securityTipText") }}<span class="security-tip-report" @click="handleReportClick">{{ t("reportText") }}</span>
    </div>
    <MessageList
      :conversationType="conversationType"
      :to="to"
      :msgs="msgs"
      :loading-older="loadingOlder"
      :has-older="hasOlder"
      :reply-msgs-map="replyMsgsMap"
      :voice-text-map="voiceTextMap"
      :set-voice-text="setVoiceText"
      :anchor-message-client-id="anchorMessageClientId"
      :anchor-mode="anchorMode"
      :loading-newer="loadingNewer"
      :auto-scroll-to-bottom="!anchorMode"
      :on-load-older="loadOlder"
      :on-load-newer="loadNewer"
      :is-multi-selecting="isMultiSelecting"
      :selected-message-ids="selectedMessageIds"
      :on-toggle-select="toggleSelectMessage"
      :on-multi-select="enterMultiSelect"
    />
    <div
      v-if="anchorMode && (hasNewer || showLatestHint)"
      class="msg-anchor-latest"
      @click="backToLatestMsgs"
    >
      <Icon
        v-if="loadingNewer"
        type="icon-a-Frame8"
        :size="20"
        iconClassName="msg-anchor-loading"
      />
      <Icon v-else type="icon-jiantou" :size="20" />
    </div>
    <div v-if="isMultiSelecting" class="msg-multi-action-bar">
      <div
        class="msg-multi-action"
        :class="{ disabled: !selectedMessages.length }"
        @click="handleMergedForward"
      >
        <div class="msg-multi-action-icon">
          <Icon type="icon-zhuanfa" :size="22" />
        </div>
        <div>{{ t("mergedForwardText") }}</div>
      </div>
      <div
        class="msg-multi-action"
        :class="{ disabled: !selectedMessages.length }"
        @click="handleMultiForward"
      >
        <div class="msg-multi-action-icon">
          <Icon type="icon-zhuanfa" :size="22" />
        </div>
        <div>{{ t("oneByOneForwardText") }}</div>
      </div>
      <div
        class="msg-multi-action"
        :class="{ disabled: !selectedMessages.length }"
        @click="handleMultiDelete"
      >
        <div class="msg-multi-action-icon">
          <Icon type="icon-shanchu" :size="22" />
        </div>
        <div>{{ t("deleteText") }}</div>
      </div>
    </div>
    <MessageInput
      v-else
      :reply-msgs-map="replyMsgsMap"
      :conversation-type="conversationType"
      :to="to"
      @send-message="handleSendMessage"
    />
    <MessageForward
      v-if="multiForwardMsgs.length"
      v-model="forwardVisible"
      :msgIdClient="multiForwardMsgs[0]?.messageClientId || ''"
      :msgs="multiForwardMsgs"
      :conversation-id="conversationId"
      :forward-mode="forwardMode"
      @close="handleMultiForwardClose"
      @forward-success="exitMultiSelect"
    />
  </div>
</template>

<script lang="ts" setup>
import { trackInit } from "../utils/reporter";
import { autorun } from "mobx";
import {
  ref,
  computed,
  onMounted,
  onUnmounted,
  getCurrentInstance,
  watch,
} from "vue";
import NetworkAlert from "../CommonComponents/NetworkAlert.vue";
import NavBar from "./message/nav-bar.vue";
import Icon from "../CommonComponents/Icon.vue";
import MessageList from "./message/message-list.vue";
import MessageInput from "./message/message-input.vue";
import MessageForward from "./message/message-forward.vue";
import { t } from "../utils/i18n";
import type { V2NIMMessage } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMMessageService";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import type { V2NIMConversationType } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMConversationService";
import { useRouter } from "vue-router";
import emitter from "../utils/eventBus";
import { events } from "../utils/constants";
import { showModal } from "../utils/modal";
import { showToast } from "../utils/toast";
import { neUiKitRouterPath } from "../utils/uikitRouter";
import { checkUserOnline } from "../utils/userStatus";
import {
  getVoiceTextMap,
  setVoiceText as setCachedVoiceText,
} from "./voiceTextCache";
import { createChatMessageLoader } from "./message-pin/messageLoader";
import type { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/src/types";
import {
  getMessageSelectKey,
  isForwardableMessage,
  isSelectableMessage,
  MULTI_DELETE_LIMIT,
  MULTI_FORWARD_LIMIT,
  syncConversationLastMessageAfterDelete,
} from "./message/message-multi-select/utils";
import {
  isMergeForwardableMessage,
  MERGED_FORWARD_LIMIT,
} from "./message/merged-forward/utils";

export interface YxReplyMsg {
  messageClientId: string;
  scene: V2NIMConst.V2NIMConversationType;
  from: string;
  receiverId: string;
  to: string;
  idServer: string;
  time: number;
}

const title = ref("");
const subTitle = ref("");
const router = useRouter();

const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore;
const nim = proxy?.$NIM;

const queryConversationId =
  (router.currentRoute.value.query.conversationId as string) || "";
const anchorMessageClientId =
  (router.currentRoute.value.query.anchorMessageClientId as string) || "";

/**会话ID */
const conversationId = (queryConversationId ||
  store?.uiStore.selectedConversation) as string;

if (queryConversationId && queryConversationId !== store?.uiStore.selectedConversation) {
  store?.uiStore.selectConversation(queryConversationId);
}

/**会话类型 */
const conversationType =
  nim.V2NIMConversationIdUtil.parseConversationType(
    conversationId
  ) as unknown as V2NIMConversationType;

/**对话方 */
const to = nim.V2NIMConversationIdUtil.parseConversationTargetId(conversationId);

trackInit("ChatUIKit", nim?.options?.appkey);

/**是否需要显示群组消息已读未读，默认 false */
const teamManagerVisible = store?.localOptions.teamMsgReceiptVisible;

/**是否需要显示 p2p 消息、p2p会话列表消息已读未读，默认 false */
const p2pMsgReceiptVisible = store?.localOptions.p2pMsgReceiptVisible;

/**回复消息map，用于回复消息的解析处理 */
const replyMsgsMap = ref<Record<string, V2NIMMessage>>();
const isMultiSelecting = ref(false);
const selectedMessageIds = ref<string[]>([]);
const multiForwardMsgs = ref<V2NIMMessageForUI[]>([]);
const forwardVisible = ref(false);
const forwardMode = ref<"oneByOne" | "merged">("oneByOne");

/** 语音转文字结果map，在进入会话列表前保留在内存中 */
const voiceTextMap = ref<Record<string, string>>(
  getVoiceTextMap(conversationId)
);

const setVoiceText = (messageClientId: string, text: string) => {
  voiceTextMap.value = setCachedVoiceText(conversationId, messageClientId, text);
};

const exitMultiSelect = () => {
  isMultiSelecting.value = false;
  selectedMessageIds.value = [];
  multiForwardMsgs.value = [];
  forwardVisible.value = false;
};

const enterMultiSelect = (msg: V2NIMMessageForUI) => {
  if (!isSelectableMessage(msg)) {
    return;
  }
  isMultiSelecting.value = true;
  selectedMessageIds.value = [getMessageSelectKey(msg)];
  emitter.emit(events.CLOSE_PANEL);
};

const toggleSelectMessage = (msg: V2NIMMessageForUI) => {
  if (!isSelectableMessage(msg)) {
    return;
  }
  const selectKey = getMessageSelectKey(msg);
  selectedMessageIds.value = selectedMessageIds.value.includes(selectKey)
    ? selectedMessageIds.value.filter((id) => id !== selectKey)
    : [...selectedMessageIds.value, selectKey];
};

const openMultiForward = (forwardMsgs: V2NIMMessageForUI[]) => {
  forwardMode.value = "oneByOne";
  multiForwardMsgs.value = forwardMsgs;
  forwardVisible.value = true;
};

const openMergedForward = (forwardMsgs: V2NIMMessageForUI[]) => {
  forwardMode.value = "merged";
  multiForwardMsgs.value = [...forwardMsgs].sort(
    (a, b) => a.createTime - b.createTime
  );
  forwardVisible.value = true;
};

const handleMultiForwardClose = () => {
  multiForwardMsgs.value = [];
  forwardVisible.value = false;
  forwardMode.value = "oneByOne";
};

const loginStatus = ref(
  store?.connectStore.loginStatus ||
    V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGOUT
);
const loginStatusWatch = autorun(() => {
  loginStatus.value =
    store?.connectStore.loginStatus ||
    V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGOUT;
});

/** 处理收到消息的已读回执 */
const handleMsgReceipt = (msg: V2NIMMessage[]) => {
  if (
    msg[0].conversationType ===
      V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P &&
    p2pMsgReceiptVisible
  ) {
    store?.msgStore.sendMsgReceiptActive(msg[0]);
  } else if (
    msg[0].conversationType ===
      V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM &&
    teamManagerVisible
  ) {
    store?.msgStore.sendTeamMsgReceiptActive(msg);
  }
};

/** 处理历史消息的已读未读 */
const handleHistoryMsgReceipt = (msgs: V2NIMMessage[]) => {
  if (
    conversationType ===
      V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P &&
    p2pMsgReceiptVisible
  ) {
    const myUserAccountId = nim.V2NIMLoginService.getLoginUser();
    const othersMsgs = msgs
      .filter(
        (item: V2NIMMessage) =>
          // @ts-ignore
          !["beReCallMsg", "reCallMsg"].includes(item.recallType || "")
      )
      .filter((item: V2NIMMessage) => item.senderId !== myUserAccountId);

    if (othersMsgs.length > 0) {
      const latestMsg = othersMsgs.reduce((max, msg) => (msg.createTime > max.createTime ? msg : max), othersMsgs[0]);
      store?.msgStore.sendMsgReceiptActive(latestMsg);
    }
  } else if (
    conversationType ===
      V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM &&
    teamManagerVisible
  ) {
    const myUserAccountId = nim.V2NIMLoginService.getLoginUser();
    const myMsgs = msgs
      .filter(
        (item: V2NIMMessage) =>
          // @ts-ignore
          !["beReCallMsg", "reCallMsg"].includes(item.recallType || "")
      )
      .filter((item: V2NIMMessage) => item.senderId === myUserAccountId);

    store?.msgStore.getTeamMsgReadsActive(myMsgs, conversationId);

    // 发送群消息已读回执
    // sdk 要求一次最多传入 50 个消息对象
    const othersMsgs = msgs
      .filter(
        (item: V2NIMMessage) =>
          // @ts-ignore
          !["beReCallMsg", "reCallMsg"].includes(item.recallType || "")
      )
      .filter((item: V2NIMMessage) => item.senderId !== myUserAccountId);

    if (othersMsgs.length > 0) {
      store?.msgStore.sendTeamMsgReceiptActive(othersMsgs.slice(-50));
    }
  }
};

const loader = createChatMessageLoader({
  conversationId,
  anchorMessageClientId,
  loginStatus,
  store,
  nim,
  onHistoryMessagesLoaded: handleHistoryMsgReceipt as any,
  onError: (err) => {
    showToast({
      message: t("getHistoryMsgFailedText"),
      type: "error",
      duration: 1000,
    });
    console.error("Get history message failed", err);
  },
});

const {
  msgs,
  loadingOlder,
  loadingNewer,
  hasOlder,
  hasNewer,
  hasLoadedLatest,
  anchorMode,
  showLatestHint,
  loadOlder,
  loadNewer,
  switchToLatest,
} = loader;

/** 进入聊天页面时，首次加载完成后自动滚动到底部 */
const initialScrollKey = ref("");
watch(
  [() => conversationId, () => anchorMessageClientId, anchorMode, hasLoadedLatest, () => msgs.value.length],
  () => {
    const key = `${conversationId}-${anchorMessageClientId}`;
    if (anchorMode.value || anchorMessageClientId || !hasLoadedLatest.value || !msgs.value.length || initialScrollKey.value === key) return;
    initialScrollKey.value = key;
    setTimeout(() => {
      emitter.emit(events.ON_SCROLL_BOTTOM);
    }, 0);
  }
);

const selectedMessages = computed(() => {
  return selectedMessageIds.value
    .map((id) => msgs.value.find((msg) => getMessageSelectKey(msg) === id))
    .filter(Boolean) as V2NIMMessageForUI[];
});

const keepSelectedMessages = (messages: V2NIMMessageForUI[]) => {
  const messageKeys = new Set(messages.map(getMessageSelectKey));
  selectedMessageIds.value = selectedMessageIds.value.filter((id) =>
    messageKeys.has(id)
  );
};

const handleMultiForward = () => {
  if (!selectedMessages.value.length) {
    return;
  }

  if (
    store?.connectStore.loginStatus !==
    V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED
  ) {
    showToast({ message: t("networkError"), type: "info" });
    return;
  }

  if (selectedMessages.value.length > MULTI_FORWARD_LIMIT) {
    showToast({
      message: t("oneByOneForwardLimitText"),
      type: "info",
      duration: 1000,
    });
    return;
  }

  const forwardableMsgs = selectedMessages.value.filter((msg) =>
    isForwardableMessage(store, msg)
  );
  if (forwardableMsgs.length !== selectedMessages.value.length) {
    showModal({
      title: t("forwardExceptionTitle"),
      content: t("forwardExceptionContent"),
      confirmText: t("okText"),
      cancelText: t("cancelText"),
      onConfirm: () => {
        keepSelectedMessages(forwardableMsgs);
        if (forwardableMsgs.length) {
          openMultiForward(forwardableMsgs);
        } else {
          showToast({
            message: t("noForwardableMsgText"),
            type: "info",
            duration: 1000,
          });
        }
      },
    });
    return;
  }

  openMultiForward(forwardableMsgs);
};

const handleMergedForward = () => {
  if (!selectedMessages.value.length) {
    return;
  }

  if (
    store?.connectStore.loginStatus !==
    V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED
  ) {
    showToast({ message: t("networkError"), type: "info" });
    return;
  }

  if (selectedMessages.value.length > MERGED_FORWARD_LIMIT) {
    showToast({
      message: t("mergedForwardLimitText"),
      type: "info",
      duration: 1000,
    });
    return;
  }

  const mergeForwardableMsgs = selectedMessages.value.filter((msg) =>
    isMergeForwardableMessage(store, msg)
  );
  if (mergeForwardableMsgs.length !== selectedMessages.value.length) {
    showModal({
      title: t("forwardExceptionTitle"),
      content: t("forwardExceptionContent"),
      confirmText: t("okText"),
      cancelText: t("cancelText"),
      onConfirm: () => {
        keepSelectedMessages(mergeForwardableMsgs);
        if (mergeForwardableMsgs.length) {
          openMergedForward(mergeForwardableMsgs);
        } else {
          showToast({
            message: t("noForwardableMsgText"),
            type: "info",
            duration: 1000,
          });
        }
      },
    });
    return;
  }

  openMergedForward(mergeForwardableMsgs);
};

const handleMultiDelete = () => {
  if (!selectedMessages.value.length) {
    return;
  }

  if (selectedMessages.value.length > MULTI_DELETE_LIMIT) {
    showToast({ message: t("multiDeleteLimitText"), type: "error" });
    return;
  }

  if (
    store?.connectStore.loginStatus !==
    V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED
  ) {
    showToast({ message: t("networkError"), type: "info" });
    return;
  }

  showModal({
    title: t("deleteText"),
    content: t("delete"),
    confirmText: t("deleteText"),
    cancelText: t("cancelText"),
    onConfirm: async () => {
      try {
        await store?.msgStore.deleteMsgActive(selectedMessages.value)
        showToast({ message: t("deleteMsgSuccessText"), type: "info" });
        syncConversationLastMessageAfterDelete(store, conversationId);
        exitMultiSelect();
      } catch {
        showToast({ message: t("deleteMsgFailText"), type: "info" });
      }
    },
  });
};

/**回到会话列表 */
const backToConversation = () => {
  store?.uiStore.unselectConversation?.();
  router.push(neUiKitRouterPath.conversation);
};

const backToLatestMsgs = async () => {
  await router.replace(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`);
  await switchToLatest();
  setTimeout(() => {
    emitter.emit(events.ON_SCROLL_BOTTOM);
  }, 0);
};

const handleSendMessage = () => {
  if (!anchorMode.value) {
    return;
  }
  backToLatestMsgs();
};

/** 解散群组回调 */
const onTeamDismissed = (data: any) => {
  if (data.teamId === to) {
    showModal({
      content: t("onDismissTeamText"),
      title: t("tipText"),
      cancelText: "",
      onConfirm: () => {
        backToConversation();
      },
    });
  }
};

// 跳转设置页
const handleSetting = async () => {
  store?.uiStore.unselectConversation?.();
  // 仅在锚点模式下移除 URL 中的 anchorMessageClientId，防止从设置页返回后仍锚点到标记消息
  if (anchorMessageClientId) {
    await router.replace({
      path: neUiKitRouterPath.chat,
      query: { conversationId },
    });
  }
  if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P
  ) {
    router.push({
      path: neUiKitRouterPath.p2pSetting,
      query: {
        accountId: to,
      },
    });
  } else if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    router.push({
      path: neUiKitRouterPath.teamSetting,
      query: {
        teamId: to,
      },
    });
  }
};

/** 举报点击 */
const handleReportClick = () => {
  window.open("https://yunxin.163.com/survey/report", "_blank");
};

/** 自己主动离开群组或被管理员踢出回调 */
const onTeamLeft = (data: any) => {
  if (data.teamId === to) {
    showModal({
      content: t("onTeamKickedText"),
      title: t("tipText"),
      cancelText: "",
      onConfirm: () => {
        backToConversation();
      },
    });
  }
};

/** 收到新消息 */
const onReceiveMessages = (newMsgs: V2NIMMessage[]) => {
  const curRoute = router.currentRoute.value.path;
  if (
    newMsgs.length &&
    !newMsgs[0]?.isSelf &&
    newMsgs[0].conversationId == conversationId &&
    curRoute === neUiKitRouterPath.chat
  ) {
    handleMsgReceipt(newMsgs);
  }

  if (loader.handleIncomingMessages(newMsgs as V2NIMMessageForUI[])) {
    // 双 rAF 确保 Vue 重渲染 + 浏览器 layout 完成后再滚动
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        emitter.emit(events.ON_SCROLL_BOTTOM);
      })
    })
  }
};

/** 监听当前聊天页面的会话类型 */
const conversationTypeWatch = autorun(() => {
  if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P
  ) {
    const appellation = store?.uiStore.getAppellation({
      account: to,
    }) as string;
    const stateMap = store?.subscriptionStore.stateMap;
    const userStatus = stateMap?.get(to);
    const isOnline = checkUserOnline(userStatus);
    title.value = appellation;
    subTitle.value = isOnline
      ? `(${t("userOnlineText")})`
      : `(${t("userOfflineText")})`;
  } else if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    const team = store?.teamStore.teams.get(to);
    title.value = team?.name || "";
    subTitle.value = "";
  }
});

const processReplyMsgs = (messages: V2NIMMessageForUI[]) => {
  const _replyMsgsMap: any = {};
  const reqMsgs: YxReplyMsg[] = [];
  const messageClientIds: Record<string, string> = {};

  messages.forEach((msg: any) => {
    if (msg.serverExtension) {
      try {
        const { yxReplyMsg } = JSON.parse(msg.serverExtension);
        if (yxReplyMsg) {
          const replyMsg = messages.find(
            (item) => item.messageClientId === yxReplyMsg.idClient
          );
          if (replyMsg) {
            _replyMsgsMap[msg.messageClientId] = replyMsg;
          } else {
            _replyMsgsMap[msg.messageClientId] = {
              messageClientId: "noFind",
            };
            const {
              scene,
              from,
              to,
              idServer,
              messageClientId,
              time,
              receiverId,
            } = yxReplyMsg;

            if (
              scene &&
              from &&
              to &&
              idServer &&
              messageClientId &&
              time &&
              receiverId
            ) {
              reqMsgs.push({
                scene,
                from,
                to,
                idServer,
                messageClientId,
                time,
                receiverId,
              });
              messageClientIds[idServer] = msg.messageClientId;
            }
          }
        }
      } catch {}
    }
    if (msg.threadReply) {
      const yxReplyMsg = msg.threadReply;
      const replyMsg = messages.find(
        (item) => item.messageClientId === yxReplyMsg.messageClientId
      );
      if (replyMsg) {
        _replyMsgsMap[msg.messageClientId] = replyMsg;
      } else {
        _replyMsgsMap[msg.messageClientId] = {
          messageClientId: "noFind",
        };
        const {
          conversationType,
          conversationId,
          senderId,
          receiverId,
          messageServerId,
          messageClientId,
          createTime,
        } = yxReplyMsg;
        if (
          conversationType &&
          conversationId &&
          senderId &&
          receiverId &&
          messageServerId &&
          messageClientId &&
          createTime
        ) {
          reqMsgs.push({
            scene: conversationType,
            from: senderId,
            to: conversationId,
            idServer: messageServerId,
            messageClientId,
            time: createTime,
            receiverId,
          });
          messageClientIds[messageServerId] = msg.messageClientId;
        }
      }
    }
  });

  return { _replyMsgsMap, reqMsgs, messageClientIds };
};

/** 动态更新回复消息 */
const stopMsgsWatch = watch(
  msgs,
  () => {
  if (isMultiSelecting.value) {
    const selectableIds = new Set(
      (msgs.value || []).filter(isSelectableMessage).map(getMessageSelectKey)
    );
    selectedMessageIds.value = selectedMessageIds.value.filter((id) =>
      selectableIds.has(id)
    );
  }

  const messages = msgs.value || [];
  if (messages.length === 0) {
    replyMsgsMap.value = {};
    return;
  }

  const { _replyMsgsMap, reqMsgs, messageClientIds } =
    processReplyMsgs(messages as V2NIMMessageForUI[]);

  if (reqMsgs.length > 0) {
    nim.V2NIMMessageService.getMessageListByRefers(
      reqMsgs.map((item) => ({
        senderId: item.from,
        receiverId: item.receiverId,
        messageClientId: item.messageClientId,
        messageServerId: item.idServer,
        createTime: item.time,
        conversationType: item.scene,
        conversationId: item.to,
      }))
    )
      .then((res: any) => {
        if (res?.length > 0) {
          res.forEach((item: any) => {
            if (item.messageServerId) {
              _replyMsgsMap[messageClientIds[item.messageServerId]] = item;
            }
          });
        }
        replyMsgsMap.value = { ..._replyMsgsMap };
      })
      .catch(() => {
        replyMsgsMap.value = { ..._replyMsgsMap };
      });
  } else {
    replyMsgsMap.value = { ..._replyMsgsMap };
  }
  },
  { immediate: true }
);

/** 设置页面标题 */
const setNavTitle = () => {
  if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P
  ) {
    title.value = store?.uiStore.getAppellation({
      account: to,
    }) as string;
  } else if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    const team = store?.teamStore.teams.get(to);
    title.value = team?.name || "";
  }
};

onMounted(() => {
  setNavTitle();

  if (msgs.value.length) {
    const _msgs = [...msgs.value].reverse();
    handleHistoryMsgReceipt(_msgs as V2NIMMessage[]);
  }

  nim.V2NIMMessageService.on("onReceiveMessages", onReceiveMessages as any);
  nim.V2NIMTeamService.on("onTeamDismissed", onTeamDismissed);
  nim.V2NIMTeamService.on("onTeamLeft", onTeamLeft);
});

onUnmounted(() => {
  // 离开聊天页时清除选中会话，确保新消息能显示未读
  store?.uiStore.unselectConversation?.();

  nim.V2NIMTeamService.off("onTeamDismissed", onTeamDismissed);
  nim.V2NIMTeamService.off("onTeamLeft", onTeamLeft);
  nim.V2NIMMessageService.off("onReceiveMessages", onReceiveMessages as any);

  stopMsgsWatch();
  conversationTypeWatch();
  loginStatusWatch();
  loader.dispose();
});
</script>

<style scoped>
.msg-page-wrapper-h5 {
  width: 100%;
  height: 100%;
  max-width: 100%;
  overflow: hidden;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  position: relative;
}

.msg-alert {
  position: relative;
  height: 0;         /* 始终不占 flex 空间，避免 NetworkAlert 出现时消息跳动 */
  width: 100%;
  z-index: 10;
}

.msg-alert > div {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}

.security-tip {
  padding: 6px 16px;
  background: #fff5e1;
  width: 100%;
  box-sizing: border-box;
  font-size: 13px;
  line-height: 150%;
  color: #eb9718;
}

.security-tip-icon {
  vertical-align: text-top;
  margin-right: 4px;
}

.security-tip-report {
  color: #3370ff;
  cursor: pointer;
}

.msg-wrapper {
  width: 100%;
  overflow: hidden;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  position: relative;
  flex: 1;
}

.msg-wrapper-h5 {
  width: 100%;
  height: 100%;
  max-width: 100%;
  overflow: hidden;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  position: relative;
}

.msg-wrapper > message-list {
  height: 100%;
}

.msg-anchor-latest {
  position: absolute;
  right: 18px;
  bottom: 110px;
  width: 38px;
  height: 38px;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.16);
  display: flex;
  align-items: center;
  justify-content: center;
  transform: rotate(90deg);
  z-index: 1;
}

.msg-anchor-loading {
  animation: anchor-spin 1s linear infinite;
}

.msg-nav-cancel {
  color: #333;
  font-size: 16px;
  line-height: 24px;
  padding: 0 4px;
}

.msg-multi-action-bar {
  flex-shrink: 0;
  height: 64px;
  padding-bottom: env(safe-area-inset-bottom);
  background: #fff;
  border-top: 1px solid #e6e8eb;
  display: flex;
  align-items: center;
  justify-content: space-around;
  box-sizing: content-box;
}

.msg-multi-action {
  min-width: 96px;
  height: 56px;
  color: #1f2329;
  font-size: 12px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 4px;
}

.msg-multi-action.disabled {
  color: #b8b8b8;
}

.msg-multi-action.disabled :deep(img) {
  opacity: 0.35;
}

.msg-multi-action-icon {
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
}

@keyframes anchor-spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/chat/index.tsx
import React, { useState, useEffect, useRef } from 'react'
import { observer } from 'mobx-react-lite'
import { autorun } from 'mobx'
import { useLocation, useNavigate } from '@/utils/router'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { events } from '@/NEUIKit/common/utils/constants'
import { showModal } from '@/NEUIKit/common/utils/modal'
import { showToast, toast } from '@/NEUIKit/common/utils/toast'
import { neUiKitRouterPath } from '@/NEUIKit/common/utils/uikitRouter'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import emitter from '@/NEUIKit/common/utils/eventBus'

import NetworkAlert from '@/NEUIKit/common/components/NetworkAlert'
import NavBar from './message/nav-bar'
import Icon from '@/NEUIKit/common/components/Icon'
import MessageList from './message/message-list'
import MessageInput from './message/message-input'
import MessageForward from './message/message-forward'
import { useEventTracking } from '../common/hooks/useEventTracking'
import { checkUserOnline } from '../common/utils/userStatus'
import { getVoiceTextMap, setVoiceText as setCachedVoiceText } from './voiceTextCache'
import { useChatMessageLoader } from './hooks/useChatMessageLoader'
import { getMessageSelectKey, isForwardableMessage, isSelectableMessage, MULTI_DELETE_LIMIT, MULTI_FORWARD_LIMIT, syncConversationLastMessageAfterDelete } from './message/message-multi-select/utils'
import { isMergeForwardableMessage, MERGED_FORWARD_LIMIT } from './message/merged-forward/utils'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'

import './index.less'

// 回复消息类型
interface YxReplyMsg {
  conversationId: string
  messageClientId: string
  messageServerId: string
  conversationType: V2NIMConst.V2NIMConversationType
  senderId: string
  receiverId: string
  createTime: number
}

/**
 * 聊天组件
 */
const Chat = observer(() => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const { store, nim } = useStateContext()
  const query = new URLSearchParams(location.search)
  const queryConversationId = query.get('conversationId') || ''
  const anchorMessageClientId = query.get('anchorMessageClientId') || ''
  const selectedConversation = store.uiStore.selectedConversation as string
  const lastConversationIdRef = useRef(queryConversationId || selectedConversation || '')

  const [title, setTitle] = useState('')
  const [statusText, setStatusText] = useState('')  // P2P 会话的在线状态文字
  const [replyMsgsMap, setReplyMsgsMap] = useState<Record<string, any>>({})
  const [isMultiSelecting, setIsMultiSelecting] = useState(false)
  const [selectedMessageIds, setSelectedMessageIds] = useState<string[]>([])
  const [multiForwardMsgs, setMultiForwardMsgs] = useState<V2NIMMessageForUI[]>([])
  const [multiForwardMode, setMultiForwardMode] = useState<'oneByOne' | 'merge'>('oneByOne')
  const initialScrollKeyRef = useRef('')

  // 会话ID
  const currentConversationId = queryConversationId || selectedConversation
  if (currentConversationId) {
    lastConversationIdRef.current = currentConversationId
  }
  const conversationId = currentConversationId || lastConversationIdRef.current

  // 语音转文字结果存储 Map<messageClientId, text>，进入会话列表前保留在内存中
  const [voiceTextMap, setVoiceTextMap] = useState<Map<string, string>>(() => getVoiceTextMap(conversationId))

  /**
   * 设置语音转文字结果
   */
  const setVoiceText = (messageClientId: string, text: string) => {
    setVoiceTextMap(setCachedVoiceText(conversationId, messageClientId, text))
  }

  // 会话类型
  const conversationType = conversationId
    ? (nim.V2NIMConversationIdUtil.parseConversationType(conversationId) as unknown as V2NIMConst.V2NIMConversationType)
    : V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_UNKNOWN

  // 对话方
  const to = conversationId ? nim.V2NIMConversationIdUtil.parseConversationTargetId(conversationId) : ''

  // 是否需要显示群组消息已读未读，默认 false
  const teamManagerVisible = store.localOptions.teamMsgReceiptVisible

  // 是否需要显示 p2p 消息、p2p会话列表消息已读未读，默认 false
  const p2pMsgReceiptVisible = store.localOptions.p2pMsgReceiptVisible

  // 初始化埋点
  useEventTracking({
    component: 'ChatUIKit'
  })

  useEffect(() => {
    if (queryConversationId && queryConversationId !== store.uiStore.selectedConversation) {
      store.uiStore.selectConversation(queryConversationId)
    }
  }, [queryConversationId])

  // 离开聊天页时清除选中会话，确保新消息能显示未读
  // 注意：不用 useEffect cleanup，因为 React 18 StrictMode 在开发环境会模拟卸载/重新挂载，
  // 导致 cleanup 在进入聊天页时就被调用，误清除刚选中的会话。
  // 改为在每一个导航出口显式调用 unselectConversation + popstate 监听手势返回。
  useEffect(() => {
    const handlePopState = () => {
      store.uiStore.unselectConversation()
    }
    window.addEventListener('popstate', handlePopState)
    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [])

  /**
   * 返回会话列表
   */
  const backToConversation = () => {
    // 在导航离开前清除选中的会话，以便后续收到消息时能正确计算未读数
    store.uiStore.unselectConversation()
    navigate(neUiKitRouterPath.conversation)
  }

  /**
   * 跳转设置页
   */
  const handleSetting = () => {
    store.uiStore.unselectConversation()
    // 仅在锚点模式下移除 URL 中的 anchorMessageClientId，防止从设置页返回后仍锚点到标记消息
    const hashQuery = window.location.hash.split('?')[1] || ''
    if (new URLSearchParams(hashQuery).get('anchorMessageClientId')) {
      window.history.replaceState(window.history.state, '', `#${neUiKitRouterPath.chat}?conversationId=${conversationId}`)
    }
    if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P) {
      navigate({
        pathname: neUiKitRouterPath.p2pSetting,
        search: `?accountId=${to}`
      })
    } else if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM) {
      navigate({
        pathname: neUiKitRouterPath.teamSetting,
        search: `?teamId=${to}`
      })
    }
  }

  const exitMultiSelect = () => {
    setIsMultiSelecting(false)
    setSelectedMessageIds([])
    setMultiForwardMsgs([])
  }

  const handleReportClick = (e: React.MouseEvent) => {
    e.stopPropagation()
    window.open('https://yunxin.163.com/survey/report', '_blank')
  }

  const renderSecurityTip = () => {
    return (
      <div className="security-tip">
        <svg className="security-tip-icon" width="14" height="14" viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path fillRule="evenodd" clipRule="evenodd" d="M10.5 0C4.706 0 0 4.706 0 10.5S4.706 21 10.5 21 21 16.294 21 10.5 16.294 0 10.5 0zm.75 15h-1.5v1.5h1.5V15zm-1.5-2V4.5h1.5V13h-1.5z" fill="#FC596A"/>
        </svg>{t('securityTipText')}<span className="security-tip-report" onClick={handleReportClick}>{t('reportText')}</span>
      </div>
    )
  }

  const enterMultiSelect = (msg: V2NIMMessageForUI) => {
    if (!isSelectableMessage(msg)) return
    setIsMultiSelecting(true)
    setSelectedMessageIds([getMessageSelectKey(msg)])
    emitter.emit(events.CLOSE_PANEL)
  }

  const toggleSelectMessage = (msg: V2NIMMessageForUI) => {
    if (!isSelectableMessage(msg)) return
    const selectKey = getMessageSelectKey(msg)
    setSelectedMessageIds((ids) => (ids.includes(selectKey) ? ids.filter((id) => id !== selectKey) : [...ids, selectKey]))
  }

  const openMultiForward = (forwardMsgs: V2NIMMessageForUI[]) => {
    setMultiForwardMode('oneByOne')
    setMultiForwardMsgs(forwardMsgs)
  }

  const openMergeForward = (forwardMsgs: V2NIMMessageForUI[]) => {
    setMultiForwardMode('merge')
    setMultiForwardMsgs(forwardMsgs)
  }

  const syncSelectedMessages = (msgs: V2NIMMessageForUI[]) => {
    setSelectedMessageIds(msgs.map(getMessageSelectKey).filter(Boolean))
  }

  const handleMultiForward = () => {
    if (!selectedMessages.length) {
      return
    }

    if (store.connectStore.loginStatus !== V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED) {
      toast.info(t('networkError'))
      return
    }

    if (selectedMessages.length > MULTI_FORWARD_LIMIT) {
      showToast({
        message: t('oneByOneForwardLimitText'),
        type: 'info',
        duration: 1000
      })
      return
    }

    const forwardableMsgs = selectedMessages.filter((msg) => isForwardableMessage(store, msg))
    if (forwardableMsgs.length !== selectedMessages.length) {
      showModal({
        title: t('forwardExceptionTitle'),
        content: t('forwardExceptionContent'),
        confirmText: t('okText'),
        cancelText: t('cancelText'),
        onConfirm: () => {
          syncSelectedMessages(forwardableMsgs)
          if (forwardableMsgs.length) {
            openMultiForward(forwardableMsgs)
          } else {
            showToast({
              message: t('noForwardableMsgText'),
              type: 'info',
              duration: 1000
            })
          }
        }
      })
      return
    }

    openMultiForward(forwardableMsgs)
  }

  const handleMergeForward = () => {
    if (!selectedMessages.length) {
      return
    }

    if (store.connectStore.loginStatus !== V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED) {
      toast.info(t('networkError'))
      return
    }

    if (selectedMessages.length > MERGED_FORWARD_LIMIT) {
      showToast({
        message: t('mergeForwardLimitText'),
        type: 'info',
        duration: 1000
      })
      return
    }

    const forwardableMsgs = selectedMessages.filter((msg) => isMergeForwardableMessage(store, msg))
    if (forwardableMsgs.length !== selectedMessages.length) {
      showModal({
        title: t('forwardExceptionTitle'),
        content: t('forwardExceptionContent'),
        confirmText: t('okText'),
        cancelText: t('cancelText'),
        onConfirm: () => {
          syncSelectedMessages(forwardableMsgs)
          if (forwardableMsgs.length) {
            openMergeForward(forwardableMsgs)
          } else {
            showToast({
              message: t('noForwardableMsgText'),
              type: 'info',
              duration: 1000
            })
          }
        }
      })
      return
    }

    openMergeForward(forwardableMsgs)
  }

  /**
   * 解散群组回调
   */
  const onTeamDismissed = (data: any) => {
    if (data.teamId === to) {
      showModal({
        title: t('tipText'),
        content: t('onDismissTeamText'),
        cancelText: '',
        onConfirm: () => {
          backToConversation()
        }
      })
    }
  }

  /**
   * 被管理员移出群聊回调
   */
  const onTeamLeft = () => {
    showModal({
      title: t('tipText'),
      content: t('onTeamKickedText'),
      cancelText: '',
      onConfirm: () => {
        backToConversation()
      }
    })
  }

  /**
   * 收到新消息
   */
  const onReceiveMessages = (messages: any[]) => {
    // 当前在聊天页，视为消息已读，发送已读回执
    if (messages.length && !messages[0]?.isSelf && messages[0].conversationId === conversationId && location.pathname === neUiKitRouterPath.chat) {
      handleMsgReceipt(messages)
    }
    if (handleIncomingMessages(messages)) {
      // 双 rAF 确保 React 重渲染 + 浏览器 layout 完成后再滚动
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          emitter.emit(events.ON_SCROLL_BOTTOM)
        })
      })
    }
  }

  /**
   * 处理收到消息的已读回执
   */
  const handleMsgReceipt = (message: any[]) => {
    if (message[0].conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P && p2pMsgReceiptVisible) {
      store.msgStore.sendMsgReceiptActive(message[0])
    } else if (message[0].conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM && teamManagerVisible) {
      store.msgStore.sendTeamMsgReceiptActive(message)
    }
  }

  /**
   * 处理历史消息的已读未读
   */
  const handleHistoryMsgReceipt = async (messages: any[]) => {
    // 如果是单聊
    if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P && p2pMsgReceiptVisible) {
      const myUserAccountId = nim.V2NIMLoginService.getLoginUser()
      const othersMsgs = messages
        .filter((item) => !['beReCallMsg', 'reCallMsg'].includes(item.recallType || ''))
        .filter((item) => item.senderId !== myUserAccountId)

      // 发送单聊消息已读回执，取当前页 createTime 最大的对方消息
      if (othersMsgs.length > 0) {
        const latestMsg = othersMsgs.reduce((max, msg) => (msg.createTime > max.createTime ? msg : max), othersMsgs[0])
        await store.msgStore.sendMsgReceiptActive(latestMsg)
      }
    }
    // 如果是群聊
    else if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM && teamManagerVisible) {
      const myUserAccountId = nim.V2NIMLoginService.getLoginUser()
      const myMsgs = messages
        .filter((item) => !['beReCallMsg', 'reCallMsg'].includes(item.recallType || ''))
        .filter((item) => item.senderId === myUserAccountId)

      await store.msgStore.getTeamMsgReadsActive(myMsgs, conversationId)

      // 发送群消息已读回执
      // sdk 要求一次最多传入 50 个消息对象
      const othersMsgs = messages
        .filter((item) => !['beReCallMsg', 'reCallMsg'].includes(item.recallType || ''))
        .filter((item) => item.senderId !== myUserAccountId)

      if (othersMsgs.length > 0) {
        await store.msgStore.sendTeamMsgReceiptActive(othersMsgs.slice(-50))
      }
    }
  }

  const {
    msgs,
    loadingOlder,
    loadingNewer,
    hasOlder,
    hasNewer,
    anchorMode,
    showLatestHint,
    hasLoadedLatest,
    loadOlder,
    loadNewer,
    switchToLatest,
    handleIncomingMessages
  } = useChatMessageLoader({
    conversationId,
    anchorMessageClientId,
    loginStatus: store.connectStore.loginStatus,
    store,
    nim,
    onHistoryMessagesLoaded: handleHistoryMsgReceipt,
    onError: (err) => {
      showToast({
        message: t('getHistoryFailedText'),
        type: 'error',
        duration: 1000
      })
      console.error('Get history message failed', err.toString())
    }
  })

  const selectedMessageIdSet = new Set(selectedMessageIds)
  const selectedMessages = msgs.filter((msg) => selectedMessageIdSet.has(getMessageSelectKey(msg)))

  const handleMultiDelete = () => {
    if (!selectedMessages.length) {
      return
    }

    if (selectedMessages.length > MULTI_DELETE_LIMIT) {
      showToast({ message: t('multiDeleteLimitText'), type: 'error' })
      return
    }

    if (store.connectStore.loginStatus !== V2NIMConst.V2NIMLoginStatus.V2NIM_LOGIN_STATUS_LOGINED) {
      toast.info(t('networkError'))
      return
    }

    showModal({
      title: t('deleteText'),
      content: t('delete'),
      confirmText: t('deleteText'),
      cancelText: t('cancelText'),
      onConfirm: async () => {
        try {
          await store.msgStore.deleteMsgActive(selectedMessages)
          toast.info(t('deleteMsgSuccessText'))
          syncConversationLastMessageAfterDelete(store, conversationId)
          exitMultiSelect()
        } catch {
          toast.info(t('deleteMsgFailText'))
        }
      }
    })
  }

  const backToLatestMsgs = async () => {
    navigate(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`, { replace: true })
    await switchToLatest()
    setTimeout(() => {
      emitter.emit(events.ON_SCROLL_BOTTOM)
    }, 0)
  }

  const handleSendMessage = () => {
    if (!anchorMode) return
    backToLatestMsgs()
  }

  useEffect(() => {
    if (!isMultiSelecting) return
    setSelectedMessageIds((ids) => {
      const selectableIds = new Set(msgs.filter(isSelectableMessage).map(getMessageSelectKey))
      return ids.filter((id) => selectableIds.has(id))
    })
  }, [isMultiSelecting, msgs])

  // 使用 autorun 监听导航栏标题（自动追踪 MobX observable 依赖）
  // 当以下任一变化时自动触发：conversationId、群信息、在线状态
  useEffect(() => {
    const dispose = autorun(() => {
      // 防解散群的时候 conversationId 编为空字符串, type 变 unknown, to 变空字符串
      if (!conversationId) return
      
      if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_P2P) {
        const appellation = store.uiStore.getAppellation({ account: to })
        // autorun 会自动追踪 stateMap.get(to) 的变化
        const userStatus = store.subscriptionStore.getUserStatus(to)
        const isOnline = checkUserOnline(userStatus)
        // P2P 会话：标题为昵称，状态文字单独设置（确保昵称过长时状态不被截断）
        setTitle(appellation)
        setStatusText(isOnline ? `(${t('userOnlineText')})` : `(${t('userOfflineText')})`)
      } else if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM) {
        // autorun 会自动追踪 teams.get(to) 的变化
        const team = store.teamStore.teams.get(to)
        // 群聊：标题为群名，无状态文字
        setTitle(team?.name || '')
        setStatusText('')
      }
    })
    
    return () => dispose()
  }, [conversationId, conversationType, to])

  useEffect(() => {
    const key = `${conversationId}-${anchorMessageClientId}`
    if (anchorMode || anchorMessageClientId || !hasLoadedLatest || !msgs.length || initialScrollKeyRef.current === key) return

    initialScrollKeyRef.current = key
    setTimeout(() => {
      emitter.emit(events.ON_SCROLL_BOTTOM)
    }, 0)
  }, [anchorMessageClientId, anchorMode, conversationId, hasLoadedLatest, msgs.length])

  // 处理可能的回复消息
  const processReplyMsg = (msgs: any) => {
    const _replyMsgsMap: Record<string, any> = {}
    const reqMsgs: YxReplyMsg[] = []
    const messageClientIds: Record<string, string> = {}
    msgs.forEach((msg: any) => {
      // 兼容旧版本用 serverExtension 存储被回复消息的相关消息
      if (msg.serverExtension) {
        try {
          // yxReplyMsg 存储着被回复消息的相关消息
          const { yxReplyMsg } = JSON.parse(msg.serverExtension)
          if (yxReplyMsg) {
            // 从消息列表中找到被回复消息，replyMsg 为被回复的消息
            const replyMsg = msgs.find((item) => item.messageClientId === yxReplyMsg.idClient)
            // 如果直接找到，存储在map中
            if (replyMsg) {
              _replyMsgsMap[msg.messageClientId] = replyMsg
              // 如果没找到，说明被回复的消息可能有三种情况：1.被删除 2.被撤回 3.不在当前消息列表中（一次性没拉到，在之前的消息中）
            } else {
              _replyMsgsMap[msg.messageClientId] = {
                messageClientId: 'noFind'
              }
              const { scene, from, to, idServer, messageClientId, time, receiverId } = yxReplyMsg

              if (scene && from && to && idServer && messageClientId && time && receiverId) {
                reqMsgs.push({
                  conversationType: scene,
                  senderId: from,
                  conversationId: to,
                  messageServerId: idServer,
                  messageClientId,
                  createTime: time,
                  receiverId
                })
                messageClientIds[idServer] = msg.messageClientId
              }
            }
          }
        } catch (e) {
          // 解析JSON失败
        }
      }
      // 新版本采用 threadReply 存储被回复消息的相关消息
      if (msg.threadReply) {
        // serverExtension":"{\"yxReplyMsg\":{\"idClient\":\"0cb875a967854da69173df397294a832\",\"scene\":2,\"from\":\"334574329307264\",\"receiverId\":\"46223315430\",\"to\":\"334633283559552|2|46223315430\",\"idServer\":\"3101994188820971548\",\"time\":1755500811326}}","sendingState":3,"senderName":""}
        // yxReplyMsg 存储着被回复消息的相关消息
        const yxReplyMsg = msg.threadReply
        // 从消息列表中找到被回复消息，replyMsg 为被回复的消息
        const replyMsg = msgs.find((item) => item.messageClientId === yxReplyMsg.messageClientId)
        // 如果直接找到，存储在map中
        if (replyMsg) {
          _replyMsgsMap[msg.messageClientId] = replyMsg
          // 如果没找到，说明被回复的消息可能有三种情况：1.被删除 2.被撤回 3.不在当前消息列表中（一次性没拉到，在之前的消息中）
        } else {
          _replyMsgsMap[msg.messageClientId] = {
            messageClientId: 'noFind'
          }
          const { conversationType, conversationId, senderId, receiverId, messageServerId, messageClientId, createTime } = yxReplyMsg

          reqMsgs.push({
            conversationId,
            conversationType,
            senderId,
            receiverId,
            messageServerId,
            messageClientId,
            createTime
          })
          messageClientIds[messageServerId] = msg.messageClientId
        }
      }
    })

    return { _replyMsgsMap, reqMsgs, messageClientIds }
  }

  // 监听消息列表
  useEffect(() => {
    // 遍历所有消息，找出被回复消息，储存在map中
    if (msgs.length > 0) {
      const { _replyMsgsMap, reqMsgs, messageClientIds } = processReplyMsg(msgs)

      if (reqMsgs.length > 0) {
        // 从服务器拉取被回复消息, 但是有频率控制
        nim.V2NIMMessageService.getMessageListByRefers(
          reqMsgs.map((item) => ({
            senderId: item.senderId,
            receiverId: item.receiverId,
            messageClientId: item.messageClientId,
            messageServerId: item.messageServerId,
            createTime: item.createTime,
            conversationType: item.conversationType,
            conversationId: item.conversationId
          }))
        )
          .then((res: any) => {
            if (res?.length > 0) {
              res.forEach((item: any) => {
                if (item.messageServerId) {
                  _replyMsgsMap[messageClientIds[item.messageServerId]] = item
                }
              })
            }
            setReplyMsgsMap({ ..._replyMsgsMap })
          })
          .catch(() => {
            setReplyMsgsMap({ ..._replyMsgsMap })
          })
      } else {
        setReplyMsgsMap({ ..._replyMsgsMap })
      }
    }
  }, [msgs])

  // // 绑定和解绑事件监听
  useEffect(() => {
    // 初始加载时，如果有消息，发送已读回执
    if (msgs.length) {
      const _msgs = [...msgs].reverse()
      handleHistoryMsgReceipt(_msgs)
    }

    // 绑定事件监听
    nim.V2NIMMessageService.on('onReceiveMessages', onReceiveMessages)
    nim.V2NIMTeamService.on('onTeamDismissed', onTeamDismissed)
    nim.V2NIMTeamService.on('onTeamLeft', onTeamLeft)

    return () => {
      // 解绑事件监听
      nim.V2NIMMessageService.off('onReceiveMessages', onReceiveMessages)
      nim.V2NIMTeamService.off('onTeamDismissed', onTeamDismissed)
      nim.V2NIMTeamService.off('onTeamLeft', onTeamLeft)
    }
  }, [conversationId, handleIncomingMessages])

  return (
    <div className="msg-page-wrapper-h5">
      <NavBar
        title={title}
        showLeft={true}
        leftContent={
          <div onClick={backToConversation}>
            <Icon type="icon-zuojiantou" size={24} />
          </div>
        }
        rightContent={
          isMultiSelecting ? (
            <div className="msg-nav-cancel" onClick={exitMultiSelect}>
              {t('cancelText')}
            </div>
          ) : (
            <div onClick={handleSetting}>
              <Icon type="icon-More" size={24} />
            </div>
          )
        }
        // P2P 会话时显示在线状态文字，使用 iconContent 确保不被截断
        iconContent={statusText ? <span className="nav-status-text">{statusText}</span> : undefined}
      />

      <div className="msg-alert">
        <NetworkAlert />
      </div>

      {renderSecurityTip()}

      <MessageList
        conversationType={conversationType}
        to={to}
        msgs={msgs}
        loadingOlder={loadingOlder}
        hasOlder={hasOlder}
        replyMsgsMap={replyMsgsMap}
        voiceTextMap={voiceTextMap}
        setVoiceText={setVoiceText}
        anchorMessageClientId={anchorMessageClientId}
        anchorMode={anchorMode}
        loadingNewer={loadingNewer}
        autoScrollToBottom={!anchorMode}
        onLoadOlder={loadOlder}
        onLoadNewer={loadNewer}
        isMultiSelecting={isMultiSelecting}
        selectedMessageIds={selectedMessageIds}
        onToggleSelect={toggleSelectMessage}
        onMultiSelect={enterMultiSelect}
      />

      {anchorMode && (hasNewer || showLatestHint) && (
        <div className="msg-anchor-latest" onClick={backToLatestMsgs}>
          {loadingNewer ? <Icon type="icon-a-Frame8" size={20} iconClassName="msg-anchor-loading" /> : <Icon type="icon-jiantou" size={20} />}
        </div>
      )}

      {isMultiSelecting ? (
        <div className="msg-multi-action-bar">
          <div className={`msg-multi-action ${!selectedMessages.length ? 'disabled' : ''}`} onClick={handleMergeForward}>
            <div className="msg-multi-action-icon">
              <Icon type="icon-zhuanfa" size={22} />
            </div>
            <div>{t('mergeForwardText')}</div>
          </div>
          <div className={`msg-multi-action ${!selectedMessages.length ? 'disabled' : ''}`} onClick={handleMultiForward}>
            <div className="msg-multi-action-icon">
              <Icon type="icon-zhuanfa" size={22} />
            </div>
            <div>{t('oneByOneForwardText')}</div>
          </div>
          <div className={`msg-multi-action ${!selectedMessages.length ? 'disabled' : ''}`} onClick={handleMultiDelete}>
            <div className="msg-multi-action-icon">
              <Icon type="icon-shanchu" size={22} />
            </div>
            <div>{t('deleteText')}</div>
          </div>
        </div>
      ) : (
        <MessageInput replyMsgsMap={replyMsgsMap} conversationType={conversationType} to={to} onSendMessage={handleSendMessage} />
      )}

      {!!multiForwardMsgs.length && (
        <MessageForward
          visible={!!multiForwardMsgs.length}
          msgIdClient={multiForwardMsgs[0]?.messageClientId || ''}
          msgs={multiForwardMsgs}
          forwardMode={multiForwardMode}
          conversationId={conversationId}
          onClose={() => {
            setMultiForwardMsgs([])
          }}
          onForwardSuccess={() => {
            exitMultiSelect()
          }}
        />
      )}
    </div>
  )
})

export default Chat
