// nim-kit-vue-ui-h5/src/components/NEUIKit/Friend/friend-card/index.vue
<template>
  <div class="wrapper">
    <NavBar />
    <UserCard
      :account="userInfo && userInfo.accountId"
      :nick="userInfo && userInfo.name"
    ></UserCard>
    <template v-if="relation === 'stranger'">
      <div class="userInfo-item-wrapper">
        <div class="userInfo-item">
          <div class="item-left">{{ t("addBlacklist") }}</div>
          <Switch
            :checked="isInBlacklist"
            @change="(checked) => handleSwitchChange(checked)"
          />
        </div>
      </div>

      <div class="button" :style="{ marginTop: '10px' }" @click="addFriend">
        {{ t("addFriendText") }}
      </div>
    </template>
    <template v-else>
      <div class="userInfo-item-wrapper remark-wrapper">
        <div class="item-divider" />
        <div class="userInfo-item" @click="handleAliasClick">
          <div class="item-left">{{ t("remarkText") }}</div>
          <Icon
            iconClassName="more-icon"
            color="#999"
            type="icon-jiantou"
          />
        </div>
      </div>
      <div class="userInfo-item-wrapper">
        <div class="userInfo-item">
          <div class="item-left">{{ t("birthText") }}</div>
          <div class="item-right">
            {{ (userInfo && userInfo.birthday) || t("unknow") }}
          </div>
        </div>
        <div class="item-divider" />
        <div class="userInfo-item">
          <div class="item-left">{{ t("mobile") }}</div>
          <div class="item-right">
            {{ (userInfo && userInfo.mobile) || t("unknow") }}
          </div>
        </div>
        <div class="item-divider" />
        <div class="userInfo-item">
          <div class="item-left">{{ t("email") }}</div>
          <div class="item-right">
            {{ (userInfo && userInfo.email) || t("unknow") }}
          </div>
        </div>
        <div class="item-divider" />
        <div class="userInfo-item">
          <div class="item-left">{{ t("sign") }}</div>
          <div class="item-right">
            {{ (userInfo && userInfo.sign) || t("unknow") }}
          </div>
        </div>
      </div>
      <div class="userInfo-item-wrapper">
        <div class="userInfo-item">
          <div class="item-left">{{ t("addBlacklist") }}</div>
          <Switch :checked="isInBlacklist" @change="handleSwitchChange" />
        </div>
      </div>
      <div class="button" @click="gotoChat">{{ t("chatWithFriendText") }}</div>
      <div class="item-divider" />
      <div class="button button-red" @click="deleteFriend">
        {{ t("deleteFriendText") }}
      </div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import UserCard from "../../CommonComponents/UserCard.vue";
import NavBar from "../../CommonComponents/NavBar.vue";
import { onUnmounted, ref, getCurrentInstance, onMounted } from "vue";
import { t } from "../../utils/i18n";
import { autorun } from "mobx";
import type { Relation } from "@xkit-yx/im-store-v2";
import type { V2NIMUser } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMUserService";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import Switch from "../../CommonComponents/Switch.vue";
import { toast } from "../../utils/toast";
import { modal } from "../../utils/modal";
import { showToast } from "../../utils/toast";
import { useRouter } from "vue-router";
import { neUiKitRouterPath } from "../../utils/uikitRouter";
import Icon from "../../CommonComponents/Icon.vue";
const router = useRouter();
const { proxy } = getCurrentInstance()!; // 获取组件实例
const store = proxy?.$UIKitStore;
const nim = proxy?.$NIM;
const userInfo = ref<V2NIMUser>();
const relation = ref<Relation>("stranger");
const isInBlacklist = ref(false);

let account = "";

const handleAliasClick = (e) => {
  e.stopPropagation();
  router.push({
    path: neUiKitRouterPath.friendInfoEdit,
    query: {
      accountId: account,
    },
  });
};

let uninstallFriendWatch = () => {};
let uninstallRelationWatch = () => {};

// 黑名单
const handleSwitchChange = async (value) => {
  const isAdd = value;
  isInBlacklist.value = value;
  try {
    if (isAdd) {
      await store?.relationStore.addUserToBlockListActive(account);
    } else {
      await store?.relationStore.removeUserFromBlockListActive(account);
    }
  } catch (error) {
    toast.info(isAdd ? t("setBlackFailText") : t("removeBlackFailText"));
  }
};

// 删除好友
const deleteFriend = () => {
  modal.confirm({
    title: t("deleteFriendText"),
    content: `${t("deleteFriendConfirmText")}"${store?.uiStore.getAppellation({
      account,
    })}"?`,
    async onConfirm() {
      try {
        await store?.friendStore.deleteFriendActive(account);
        toast.info(t("deleteFriendSuccessText"));
      } catch (error) {
        toast.info(t("deleteFriendFailText"));
      }
    },
  });
};

// 申请加好友
const addFriend = async () => {
  try {
    await store?.friendStore.addFriendActive(account, {
      addMode: V2NIMConst.V2NIMFriendAddMode.V2NIM_FRIEND_MODE_TYPE_APPLY,
      postscript: "",
    });

    // 发送申请成功后解除黑名单
    await store?.relationStore.removeUserFromBlockListActive(account);

    showToast({
      message: t("applyFriendSuccessText"),
      type: "info",
    });
  } catch (error) {
    showToast({
      message: t("applyFriendFailText"),
      type: "info",
    });
  }
};

// 聊天
const gotoChat = async () => {
  const conversationId = nim.V2NIMConversationIdUtil.p2pConversationId(
    userInfo.value?.accountId || ""
  );
  await store?.uiStore.selectConversation(conversationId);
  router.push(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`);
};

onMounted(() => {
  account = (router.currentRoute.value.query.accountId as string) || "";

  store?.userStore.getUserListFromCloudActive([account]);
  uninstallFriendWatch = autorun(() => {
    userInfo.value = store?.uiStore.getFriendWithUserNameCard(account);
  });

  uninstallRelationWatch = autorun(() => {
    const { relation: _relation, isInBlacklist: _isInBlacklist } =
      store?.uiStore.getRelation(account) as {
        relation: Relation;
        isInBlacklist: boolean;
      };
    relation.value = _relation;
    isInBlacklist.value = _isInBlacklist;
  });

});

onUnmounted(() => {
  uninstallFriendWatch();
  uninstallRelationWatch();
});
</script>

<style scoped>
.wrapper {
  background-color: rgb(245, 246, 247);
  height: 100%;
  box-sizing: border-box;
  padding-bottom: 50px;
  overflow: auto;
}

.userInfo-item-wrapper {
  background-color: #fff;
  margin-bottom: 10px;
}

.remark-wrapper {
  margin-top: 0;
}

.userInfo-item {
  display: flex;
  height: 50px;
  align-items: center;
  justify-content: space-between;
  padding: 0 25px;
}

.item-divider {
  margin: 0 25px;
  border-top: 1px solid #f5f5f5;
}

.item-left {
  font-size: 16px;
  color: #000;
}

.item-right {
  font-size: 15px;
  width: 200px;
  text-align: right;
  color: #a6adb6;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.button {
  display: block;
  width: 100%;
  background-color: #fff;
  color: rgb(25, 146, 239);
  text-align: center;
  height: 50px;
  font-size: 16px;
  line-height: 50px;
}

.button-red {
  color: #e6605c;
}

.bold-divider {
  height: 8px;
  background-color: rgb(245, 246, 247);
}

</style>

// nim-kit-react-ui-h5/src/NEUIKit/friend/friend-card/index.tsx
import React, { useEffect } from 'react'
import { useNavigate, useLocation } from '@/utils/router'
import { observer } from 'mobx-react-lite'
import NavBar from '@/NEUIKit/common/components/NavBar'
import UserCard from '@/NEUIKit/common/components/UserCard'
import Switch from '@/NEUIKit/common/components/Switch'
import Icon from '@/NEUIKit/common/components/Icon'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { neUiKitRouterPath } from '@/NEUIKit/common/utils/uikitRouter'
import { toast } from '@/NEUIKit/common/utils/toast'
import { modal } from '@/NEUIKit/common/utils/modal'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import './index.less'

/**
 * 好友名片组件
 */
const FriendCard: React.FC = observer(() => {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const { store } = useStateContext()

  // 从URL参数中获取账号ID
  const query = new URLSearchParams(location.search)
  const account = query.get('accountId') || ''

  // 强制拉取最新用户数据，防止缓存旧数据
  useEffect(() => {
    if (account) {
      store.userStore.getUserListFromCloudActive([account])
    }
  }, [account])

  // 状态
  const userInfo = store.uiStore.getFriendWithUserNameCard(account)
  const { relation, isInBlacklist } = store.uiStore.getRelation(account)
  // 处理备注点击
  const handleAliasClick = (e: React.MouseEvent) => {
    e.stopPropagation()
    navigate(`${neUiKitRouterPath.friendInfoEdit}?accountId=${account}`)
  }

  // 处理黑名单开关状态变更
  const handleSwitchChange = async (checked: boolean) => {
    // setIsInBlacklist(checked)
    try {
      if (checked) {
        await store.relationStore.addUserToBlockListActive(account)
      } else {
        await store.relationStore.removeUserFromBlockListActive(account)
      }
    } catch (error) {
      toast.info(checked ? t('setBlackFailText') : t('removeBlackFailText'))
    }
  }

  // 删除好友
  const deleteFriend = () => {
    modal.confirm({
      title: t('deleteFriendText'),
      content: `${t('deleteFriendConfirmText')}"${store.uiStore.getAppellation({
        account
      })}"?`,
      async onConfirm() {
        try {
          await store.friendStore.deleteFriendActive(account)
          toast.info(t('deleteFriendSuccessText'))
        } catch (error) {
          toast.info(t('deleteFriendFailText'))
        }
      }
    }).catch(() => {
      // 用户点击取消，不需要任何操作
    })
  }

  // 添加好友
  const addFriend = async () => {
    try {
      await store.friendStore.addFriendActive(account, {
        addMode: V2NIMConst.V2NIMFriendAddMode.V2NIM_FRIEND_MODE_TYPE_APPLY,
        postscript: ''
      })

      // 发送申请成功后解除黑名单
      await store.relationStore.removeUserFromBlockListActive(account)

      toast.info(t('applyFriendSuccessText'))
    } catch (error) {
      toast.info(t('applyFriendFailText'))
    }
  }

  // 跳转到聊天页面
  const gotoChat = async () => {
    const conversationId = store.nim.V2NIMConversationIdUtil.p2pConversationId(userInfo?.accountId || '')
    await store.uiStore.selectConversation(conversationId)
    navigate(`${neUiKitRouterPath.chat}?conversationId=${conversationId}`)
  }

  return (
    <div className="nim-friend-card">
      <NavBar />

      <UserCard account={userInfo?.accountId} nick={userInfo?.name} />

      {relation === 'stranger' ? (
        <>
          <div className="userInfo-item-wrapper">
            <div className="userInfo-item">
              <div className="item-left">{t('addBlacklist')}</div>
              <Switch checked={isInBlacklist} onChange={handleSwitchChange} />
            </div>
          </div>

          <div className="button" style={{ marginTop: '10px' }} onClick={addFriend}>
            {t('addFriendText')}
          </div>
        </>
      ) : (
        <>
          <div className="userInfo-item-wrapper remark-wrapper">
            <div className="item-divider" />
            <div className="userInfo-item" onClick={handleAliasClick}>
              <div className="item-left">{t('remarkText')}</div>
              <Icon iconClassName="more-icon" style={{ color: '#999' }} type="icon-jiantou" />
            </div>
          </div>

          <div className="userInfo-item-wrapper">
            <div className="userInfo-item">
              <div className="item-left">{t('birthText')}</div>
              <div className="item-right">{(userInfo && userInfo.birthday) || t('unknow')}</div>
            </div>

            <div className="item-divider" />

            <div className="userInfo-item">
              <div className="item-left">{t('mobile')}</div>
              <div className="item-right">{(userInfo && userInfo.mobile) || t('unknow')}</div>
            </div>

            <div className="item-divider" />

            <div className="userInfo-item">
              <div className="item-left">{t('email')}</div>
              <div className="item-right">{(userInfo && userInfo.email) || t('unknow')}</div>
            </div>

            <div className="item-divider" />

            <div className="userInfo-item">
              <div className="item-left">{t('sign')}</div>
              <div className="item-right">{(userInfo && userInfo.sign) || t('unknow')}</div>
            </div>
          </div>

          <div className="userInfo-item-wrapper">
            <div className="userInfo-item">
              <div className="item-left">{t('addBlacklist')}</div>
              <Switch checked={isInBlacklist} onChange={handleSwitchChange} />
            </div>
          </div>

          <div className="button" onClick={gotoChat}>
            {t('chatWithFriendText')}
          </div>

          <div className="item-divider" />
          <div className="button button-red" onClick={deleteFriend}>
            {t('deleteFriendText')}
          </div>
        </>
      )}
    </div>
  )
})

export default FriendCard
