// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/message/mention-choose-list.vue
<template>
  <div class="mention-member-list-wrapper">
    <div class="member-list-content">
      <div style="display: none">{{ teamExt }}</div>
      <div
        v-if="allowAtAll"
        class="member-item"
        @click="
          () =>
            handleItemClick({
              accountId: AT_ALL_ACCOUNT,
              //@ts-ignore
              appellation: t('teamAll'),
            })
        "
      >
        <Icon :size="36" type="icon-team2" color="#fff" />
        <span class="member-name">
          {{ t("teamAll") }}
        </span>
      </div>
      <div
        class="member-item"
        v-for="member in teamMembersWithoutSelf"
        :key="member.accountId"
        @click="() => handleItemClick(member)"
      >
        <Avatar :account="member.accountId" size="36" />
        <div class="member-name">
          <Appellation
            :account="member.accountId"
            :teamId="member.teamId"
          ></Appellation>
        </div>
        <div
          v-if="
            member.memberRole ===
            V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER
          "
          class="owner"
        >
          {{ t("teamOwner") }}
        </div>
        <div
          v-else-if="
            member.memberRole ===
            V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER
          "
          class="manager"
        >
          {{ t("teamManager") }}
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
/**@ 列表组件，用于在群里@ 成员列表 */
import { ref, computed, onUnmounted, getCurrentInstance } from "vue";
import { t } from "../../utils/i18n";
import { autorun, untracked } from "mobx";
import Avatar from "../../CommonComponents/Avatar.vue";
import Icon from "../../CommonComponents/Icon.vue";
import { ALLOW_AT, AT_ALL_ACCOUNT } from "../../utils/constants";
import Appellation from "../../CommonComponents/Appellation.vue";

import type {
  V2NIMTeam,
  V2NIMTeamMember,
} from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService";

import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";

const props = withDefaults(
  defineProps<{
    teamId: string;
  }>(),
  {}
);

const emit = defineEmits<{
  close: [];
  handleMemberClick: [member: any];
}>();

const { proxy } = getCurrentInstance()!; // 获取组件实例
const store = proxy?.$UIKitStore;

const team = ref<V2NIMTeam>();
const teamMembers = ref<V2NIMTeamMember[]>([]);
const teamExt = ref("");

/** 群成员 不包括当前登录用户 */
const teamMembersWithoutSelf = computed(() => {
  return teamMembers.value.filter(
    (item) => item.accountId !== store?.userStore.myUserInfo.accountId
  );
});

/** 是否是群主 */
const isGroupOwner = computed(() => {
  const myUser = store?.userStore.myUserInfo;
  return (
    (team.value ? team.value.ownerAccountId : "") ===
    (myUser ? myUser.accountId : "")
  );
});

/** 是否是群管理员 */
const isGroupManager = computed(() => {
  const myUser = store?.userStore.myUserInfo;
  return teamMembers.value
    .filter(
      (item) =>
        item.memberRole ===
        V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER
    )
    .some((member) => member.accountId === (myUser ? myUser.accountId : ""));
});

/** 是否允许@ 所有人 */
const allowAtAll = computed(() => {
  let ext: any = {};
  try {
    ext = JSON.parse(teamExt.value || "{}");
  } catch (error) {
    //
  }
  if (ext[ALLOW_AT] === "manager") {
    return isGroupOwner.value || isGroupManager.value;
  }
  return true;
});

/** 群成员排序 群主 > 管理员 > 成员 */
const sortGroupMembers = (members: V2NIMTeamMember[], teamId: string) => {
  const owner = members.filter(
    (item) =>
      item.memberRole ===
      V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER
  );
  const manager = members
    .filter(
      (item) =>
        item.memberRole ===
        V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER
    )
    .sort((a, b) => a.joinTime - b.joinTime);
  const other = members
    .filter(
      (item) =>
        ![
          V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER,
          V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER,
        ].includes(item.memberRole)
    )
    .sort((a, b) => a.joinTime - b.joinTime);
  const result = [...owner, ...manager, ...other].map((item) => {
    return {
      ...item,

      name: store?.uiStore.getAppellation({
        account: item.accountId,
        teamId,
      }),
    };
  });
  return result;
};

/**
 * 群成员点击函数
 */
const handleItemClick = (member: V2NIMTeamMember) => {
  const _member =
    member.accountId === AT_ALL_ACCOUNT
      ? member
      : {
          accountId: member.accountId,
          appellation: store?.uiStore.getAppellation({
            account: member.accountId,
            teamId: (member as V2NIMTeamMember).teamId,
            ignoreAlias: true,
          }),
        };

  // 触发 handleMemberClick 事件
  emit("handleMemberClick", _member);
};

/** 监听群成员 */
const teamMemberWatch = autorun(() => {
  if (props.teamId) {
    const members = store?.teamMemberStore.getTeamMember(
      props.teamId
    ) as V2NIMTeamMember[];
    teamMembers.value = sortGroupMembers(members, props.teamId);

    // 预加载缺失的群成员用户资料，避免列表名称从 accid 闪现为昵称
    untracked(() => {
      const missingAccountIds = (members || [])
        .map((m) => m.accountId)
        .filter((id) => !store?.userStore.users.has(id));
      if (missingAccountIds.length > 0) {
        store?.userStore.getUserListFromCloudActive(missingAccountIds);
      }
    });

    const _team = store?.teamStore.teams.get(props.teamId);
    if (_team) {
      team.value = _team;
      teamExt.value = _team?.serverExtension || "";
    }
  }
});

onUnmounted(() => {
  /** 移除监听 */
  teamMemberWatch();
});
</script>

<style scoped>
.mention-member-list-wrapper {
  z-index: 9999999;
  touch-action: none;
  max-height: 400px;
  overflow-y: auto;
}

.title {
  text-align: center;
  font-weight: 500;
  margin: 0 auto;
}

.header {
  display: flex;
  align-items: center;
  height: 60px;
}

.close {
  transform: rotate(90deg);
  margin-left: 15px;
}

.member-list-content {
  height: 100%;
  box-sizing: border-box;
  overflow-y: auto;
}

.member-item {
  display: flex;
  align-items: center;
  height: 60px;
  padding: 4px;
  cursor: pointer;
  font-size: 16px;
}

.member-name {
  margin-left: 10px;
  font-size: 16px;
  padding-right: 20px;
  color: #000000;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.contact-item-icon {
  height: 42px;
  width: 42px;
  border-radius: 50%;
  text-align: center;
  line-height: 39px;
  font-size: 20px;
  color: #fff;
  background-color: #53c3f4;
}

.owner,
.manager {
  color: rgb(6, 155, 235);
  background-color: rgb(210, 229, 246);
  height: 24px;
  line-height: 24px;
  border-radius: 4px;
  font-size: 12px;
  text-align: center;
  padding: 2px 4px;
  position: relative;
  right: 10px;
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/chat/message/mention-choose-list/index.tsx
import React, { useState, useEffect, useMemo } from 'react'
import { useStateContext } from '../../../common/hooks/useStateContext'
import { autorun, untracked } from 'mobx'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import { AT_ALL_ACCOUNT, ALLOW_AT } from '../../../common/utils/constants'
import { useTranslation } from '../../../common/hooks/useTranslate'
import Avatar from '../../../common/components/Avatar'
import Icon from '../../../common/components/Icon'
import Appellation from '../../../common/components/Appellation'
import type {
  V2NIMTeam,
  V2NIMTeamMember,
} from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMTeamService'

import './index.less'

interface MentionChooseListProps {
  teamId: string
  onClose?: () => void
  onMemberClick: (member: any) => void
}

/**
 * @ 成员选择列表组件
 */
const MentionChooseList: React.FC<MentionChooseListProps> = ({ 
  teamId,
  onClose,
  onMemberClick
}) => {
  const { t } = useTranslation()
  const { store } = useStateContext()
  
  const [team, setTeam] = useState<V2NIMTeam>()
  const [teamMembers, setTeamMembers] = useState<V2NIMTeamMember[]>([])
  const [teamExt, setTeamExt] = useState('')

  // 群成员排序 群主 > 管理员 > 成员
  const sortGroupMembers = (members: V2NIMTeamMember[], teamId: string) => {
    const owner = members.filter(
      (item) =>
        item.memberRole === V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER
    )
    
    const manager = members
      .filter(
        (item) =>
          item.memberRole === V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER
      )
      .sort((a, b) => a.joinTime - b.joinTime)
      
    const other = members
      .filter(
        (item) =>
          ![
            V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER,
            V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER,
          ].includes(item.memberRole)
      )
      .sort((a, b) => a.joinTime - b.joinTime)
      
    const result = [...owner, ...manager, ...other].map((item) => {
      return {
        ...item,
        name: store?.uiStore.getAppellation({
          account: item.accountId,
          teamId,
        }),
      }
    })
    
    return result
  }

  // 群成员不包括当前登录用户
  const teamMembersWithoutSelf = useMemo(() => {
    return teamMembers.filter(
      (item) => item.accountId !== store?.userStore.myUserInfo.accountId
    )
  }, [teamMembers, store?.userStore.myUserInfo.accountId])

  // 是否是群主
  const isGroupOwner = useMemo(() => {
    const myUser = store?.userStore.myUserInfo
    return (
      (team ? team.ownerAccountId : "") === (myUser ? myUser.accountId : "")
    )
  }, [team, store?.userStore.myUserInfo])

  // 是否是群管理员
  const isGroupManager = useMemo(() => {
    const myUser = store?.userStore.myUserInfo
    return teamMembers
      .filter(
        (item) =>
          item.memberRole === V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER
      )
      .some((member) => member.accountId === (myUser ? myUser.accountId : ""))
  }, [teamMembers, store?.userStore.myUserInfo])

  // 是否允许@ 所有人
  const allowAtAll = useMemo(() => {
    let ext: any = {}
    try {
      ext = JSON.parse(teamExt || '{}')
    } catch (error) {
      //
    }
    if (ext[ALLOW_AT] === 'manager') {
      return isGroupOwner || isGroupManager
    }
    return true
  }, [teamExt, isGroupOwner, isGroupManager])

  // 处理成员点击
  const handleItemClick = (member: V2NIMTeamMember) => {
    const _member =
      member.accountId === AT_ALL_ACCOUNT
        ? member
        : {
            accountId: member.accountId,
            // 不设置 ignoreAlias，使用默认值 false，确保与列表显示的名称一致（优先显示备注名）
            appellation: store?.uiStore.getAppellation({
              account: member.accountId,
              teamId: (member as V2NIMTeamMember).teamId,
              ignoreAlias: true,
            }),
          }

    onMemberClick(_member)
  }

  useEffect(() => {
    // 使用 autorun 监听群成员变化
    const teamMemberWatch = autorun(() => {
      if (teamId) {
        const members = store?.teamMemberStore.getTeamMember(teamId) as V2NIMTeamMember[] || []
        setTeamMembers(sortGroupMembers(members, teamId))

        // 预加载缺失的群成员用户资料，避免列表名称从 accid 闪现为昵称
        untracked(() => {
          const missingAccountIds = members
            .map((m) => m.accountId)
            .filter((id) => !store?.userStore.users.has(id))
          if (missingAccountIds.length > 0) {
            store?.userStore.getUserListFromCloudActive(missingAccountIds)
          }
        })

        const _team = store?.teamStore.teams.get(teamId)
        if (_team) {
          setTeam(_team)
          setTeamExt(_team?.serverExtension || '')
        }
      }
    })

    // 组件卸载时清除监听
    return () => {
      teamMemberWatch()
    }
  }, [teamId, store?.teamMemberStore, store?.teamStore])

  return (
    <div className="mention-member-list-wrapper">
      <div className="member-list-content">
        {/* Vue中的隐藏元素，用于触发响应式更新，React中可以省略 */}
        
        {/* @所有人选项 */}
        {allowAtAll && (
          <div 
            className="member-item"
            onClick={() => handleItemClick({
              accountId: AT_ALL_ACCOUNT,
              appellation: t('teamAll'),
            } as any)}
          >
            <Icon size={36} type="icon-team2" />
            <span className="member-name">
              {t('teamAll')}
            </span>
          </div>
        )}
        
        {/* 群成员列表 */}
        {teamMembersWithoutSelf.map(member => (
          <div 
            className="member-item" 
            key={member.accountId}
            onClick={() => handleItemClick(member)}
          >
            <Avatar account={member.accountId} size={36} />
            <div className="member-name">
              <Appellation
                account={member.accountId}
                teamId={member.teamId}
              />
            </div>
            {member.memberRole === V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_OWNER && (
              <div className="owner">
                {t('teamOwner')}
              </div>
            )}
            {member.memberRole === V2NIMConst.V2NIMTeamMemberRole.V2NIM_TEAM_MEMBER_ROLE_MANAGER && (
              <div className="manager">
                {t('teamManager')}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

export default MentionChooseList
