// nim-kit-react-ui-h5/src/NEUIKit/chat/message/merged-forward/card.tsx
import React, { useState } from 'react'
import { observer } from 'mobx-react-lite'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { showToast } from '@/NEUIKit/common/utils/toast'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import { normalizeMergedForwardText, parseMergedForwardPayload } from './utils'
import MergedForwardModal from './modal'
import './index.less'

interface MergedForwardCardProps {
  msg: V2NIMMessageForUI
}

const MergedForwardCard: React.FC<MergedForwardCardProps> = observer(({ msg }) => {
  const { t } = useTranslation()
  const { store } = useStateContext()
  const [visible, setVisible] = useState(false)
  const [msgs, setMsgs] = useState<V2NIMMessageForUI[]>([])
  const payload = parseMergedForwardPayload(msg)
  const data = payload?.data
  const sessionName = data?.sessionName || data?.sessionId || ''
  const title = `${sessionName}${t('messageOfText')}`

  const openMergedForward = async () => {
    if (msgs.length) {
      setVisible(true)
      return
    }

    try {
      if (!data?.url) throw new Error('Merged forward url missing')
      const res = await fetch(data.url)
      if (!res.ok) throw new Error('Merged forward fetch failed')
      const text = await res.text()
      const list = store.msgStore.deserializeMergeMsgs(normalizeMergedForwardText(text)) as V2NIMMessageForUI[]
      if (!list.length) throw new Error('Merged forward deserialize failed')
      setMsgs(list)
      setVisible(true)
    } catch {
      showToast({
        message: t('getMergedForwardFailedText'),
        type: 'error',
        duration: 1000
      })
    }
  }

  return (
    <>
      <div className={`msg-bg ${msg.isSelf ? 'msg-bg-out' : 'msg-bg-in'} merged-forward-card`} onClick={openMergedForward}>
        <div className="merged-forward-card-content">
          <div className="merged-forward-title">
            <span className="merged-forward-title-session">{sessionName}</span>
            <span className="merged-forward-title-suffix">{t('messageOfText')}</span>
          </div>
          <div className="merged-forward-abstracts">
            {(data?.abstracts || []).map((item, index) => (
              <div key={index} className="merged-forward-abstract">
                <span className="merged-forward-sender">{item.senderNick}: </span>
                <span className="merged-forward-abstract-content">{item.content}</span>
              </div>
            ))}
          </div>
          <div className="merged-forward-footer">{t('chatHistoryText')}</div>
        </div>
      </div>
      <MergedForwardModal visible={visible} title={title} msgs={msgs} onClose={() => setVisible(false)} />
    </>
  )
})

export default MergedForwardCard

// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/message/merged-forward/card.vue
<template>
  <div
    :class="`msg-bg ${msg.isSelf ? 'msg-bg-out' : 'msg-bg-in'} merged-forward-card`"
    @click="openMergedForward"
  >
    <div class="merged-forward-card-content">
      <div class="merged-forward-title">
        <span class="merged-forward-title-session">{{ sessionName }}</span>
        <span class="merged-forward-title-suffix">{{ t("messageOfText") }}</span>
      </div>
      <div class="merged-forward-abstracts">
        <div
          v-for="(item, index) in data?.abstracts || []"
          :key="`${item.userAccId}-${index}`"
          class="merged-forward-abstract"
        >
          <span class="merged-forward-sender">{{ item.senderNick }}: </span>
          <span class="merged-forward-content">{{ item.content }}</span>
        </div>
      </div>
      <div class="merged-forward-footer">{{ t("chatHistoryText") }}</div>
    </div>
  </div>
  <MergedForwardModal
    :visible="visible"
    :title="title"
    :msgs="mergedMsgs"
    @close="visible = false"
  />
</template>

<script lang="ts" setup>
import { computed, getCurrentInstance, ref } from "vue";
import type { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/src/types";
import { t } from "../../../utils/i18n";
import { showToast } from "../../../utils/toast";
import MergedForwardModal from "./modal.vue";
import {
  normalizeMergedForwardText,
  parseMergedForwardPayload,
} from "./utils";

const props = defineProps<{
  msg: V2NIMMessageForUI;
}>();

const { proxy } = getCurrentInstance()!;
const store = proxy?.$UIKitStore;
const visible = ref(false);
const mergedMsgs = ref<V2NIMMessageForUI[]>([]);
const payload = computed(() => parseMergedForwardPayload(props.msg));
const data = computed(() => payload.value?.data);
const sessionName = computed(
  () => data.value?.sessionName || data.value?.sessionId || ""
);
const title = computed(() => `${sessionName.value}${t("messageOfText")}`);

const openMergedForward = async () => {
  if (mergedMsgs.value.length) {
    visible.value = true;
    return;
  }

  try {
    if (!data.value?.url) {
      throw new Error("Merged forward url missing");
    }
    const res = await fetch(data.value.url);
    if (!res.ok) {
      throw new Error("Merged forward fetch failed");
    }
    const text = await res.text();
    const list = store?.msgStore.deserializeMergeMsgs(
      normalizeMergedForwardText(text)
    ) as V2NIMMessageForUI[];
    if (!list?.length) {
      throw new Error("Merged forward deserialize failed");
    }
    mergedMsgs.value = list;
    visible.value = true;
  } catch {
    showToast({
      message: t("getMergedForwardMsgFailedText"),
      type: "error",
      duration: 1000,
    });
  }
};
</script>

<style scoped>
.merged-forward-card {
  max-width: 63vw;
  overflow: hidden;
  padding: 8px;
  background-color: #c9def4;
  cursor: pointer;
}

.msg-bg-in {
  border-radius: 0 8px 8px 8px;
  margin-left: 8px;
}

.msg-bg-out {
  border-radius: 8px 0 8px 8px;
  margin-right: 8px;
}

.merged-forward-card-content {
  background-color: #fff;
  border-radius: 8px 0 8px 8px;
  padding: 12px 16px;
  min-width: 0;
}

.merged-forward-title {
  margin-bottom: 8px;
  display: flex;
  min-width: 0;
  white-space: nowrap;
  font-size: 16px;
  font-weight: 500;
  line-height: 22px;
}

.merged-forward-title-session {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.merged-forward-title-suffix {
  flex: 0 0 auto;
}

.merged-forward-abstract {
  display: flex;
  align-items: center;
  min-width: 0;
  color: #656a72;
  font-size: 13px;
  line-height: 18px;
  white-space: nowrap;
  overflow: hidden;
}

.merged-forward-sender {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: #3d4149;
}

.merged-forward-content {
  flex: 0 0 auto;
  white-space: nowrap;
}

.merged-forward-footer {
  margin: 10px -16px 0;
  padding: 8px 16px 0;
  border-top: 1px solid #edf0f3;
  color: #8b9099;
  font-size: 12px;
  line-height: 17px;
}
</style>
