// nim-kit-react-ui-h5/src/NEUIKit/chat/message/message-text/index.tsx
import React, { useMemo } from 'react'
import Icon from '@/NEUIKit/common/components/Icon'
import { parseText } from '@/NEUIKit/common/utils/parseText'
import { EMOJI_ICON_MAP_CONFIG } from '@/NEUIKit/common/utils/emoji'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import './index.less'

interface MessageTextProps {
  msg: V2NIMMessageForUI
  fontSize?: number
  disableAit?: boolean
}

/**
 * 文本消息组件
 * 支持文本、@、表情和链接混排显示
 */
const MessageText: React.FC<MessageTextProps> = ({ msg, fontSize = 16, disableAit = false }) => {
  // 解析文本
  const textArr = useMemo(() => {
    return parseText(msg?.text || '', disableAit ? undefined : msg?.serverExtension)
  }, [disableAit, msg?.serverExtension, msg?.text])

  return (
    <div className="msg-text" style={{ fontSize: `${fontSize}px` }}>
      {textArr.map((item, index) => {
        if (item.type === 'text') {
          // 普通文本
          return (
            <span key={item.key} className="msg-text">
              {item.value}
            </span>
          )
        } else if (item.type === 'Ait') {
          // @消息
          return (
            <span key={item.key} className="msg-text" style={{ color: '#1861df' }}>
              {` ${item.value} `}
            </span>
          )
        } else if (item.type === 'emoji') {
          // 表情
          return (
            <Icon
              key={item.key}
              type={EMOJI_ICON_MAP_CONFIG[item.value]}
              size={fontSize || 22}
              style={{
                margin: '0 2px 2px 2px',
                verticalAlign: 'bottom'
              }}
            />
          )
        } else if (item.type === 'link') {
          // 链接
          return (
            <a
              key={item.key}
              href={item.value}
              target="_blank"
              rel="noopener noreferrer"
              style={{
                color: '#1861df',
                fontSize: `${fontSize}px`
              }}
            >
              {item.value}
            </a>
          )
        }
        return null
      })}
    </div>
  )
}

export default MessageText

// nim-kit-vue-ui-h5/src/components/NEUIKit/Chat/message/message-text.vue
<template>
  <div class="msg-text" :style="{ fontSize: (fontSize || 16) + 'px' }">
    <template v-for="(item, index) in textArr" :key="item.key">
      <template v-if="item.type === 'text'">
        <span class="msg-text">{{ item.value }}</span>
      </template>
      <template v-else-if="item.type === 'Ait'">
        <text class="msg-text" :style="{ color: '#1861df' }">
          {{ " " + item.value + " " }}
        </text>
      </template>
      <template v-else-if="item.type === 'emoji'">
        <Icon
          :type="EMOJI_ICON_MAP_CONFIG[item.value]"
          :size="fontSize || 22"
          :style="{ margin: '0 2px 2px 2px', verticalAlign: 'bottom' }"
        />
      </template>
      <template v-else-if="item.type === 'link'">
        <a
          :href="item.value"
          target="_blank"
          rel="noopener noreferrer"
          :style="{ color: '#1861df', fontSize: (fontSize || 16) + 'px' }"
        >
          {{ item.value }}
        </a>
      </template>
    </template>
  </div>
</template>

<script lang="ts" setup>
import Icon from "../../CommonComponents/Icon.vue";
import { parseText } from "../../utils/parseText";
import { EMOJI_ICON_MAP_CONFIG } from "../../utils/emoji";
import type { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/src/types";

const props = withDefaults(
  defineProps<{
    msg: V2NIMMessageForUI;
    fontSize?: number;
    disableAit?: boolean;
  }>(),
  {}
);

// 解析文本
const textArr = parseText(
  props.msg?.text || "",
  props.disableAit ? undefined : props.msg?.serverExtension
);
</script>

<style scoped>
.msg-text {
  color: #000;
  text-align: left;
  overflow-y: auto;
  word-break: break-all;
  word-wrap: break-word;
  white-space: break-spaces;
}
</style>
