// nim-kit-react-ui-h5/src/NEUIKit/conversation/conversation-list/conversation-item-last-msg-content.tsx
import React, { useMemo } from 'react'
import { observer } from 'mobx-react-lite'
import Icon from '@/NEUIKit/common/components/Icon'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import type { V2NIMLastMessage } from 'nim-web-sdk-ng/dist/esm/nim/src/V2NIMConversationService'
import { EMOJI_ICON_MAP_CONFIG, emojiRegExp } from '@/NEUIKit/common/utils/emoji'
import { parseMergedForwardPayload } from '@/NEUIKit/chat/message/merged-forward/utils'
import './conversation-item-last-msg-content.less'

interface LastMsgContentProps {
  lastMessage: V2NIMLastMessage
}

interface ParsedItem {
  type: 'emoji' | 'text'
  value: string
  index: number
}

/**
 * 会话列表最后一条消息内容组件
 */
const LastMsgContent: React.FC<LastMsgContentProps> = observer(({ lastMessage }) => {
  const { t } = useTranslation()

  // 翻译消息类型
  const translateMsg = (key: string): string => {
    const textMap: Record<string, string> = {
      textMsgText: t('textMsgText'),
      customMsgText: t('customMsgText'),
      audioMsgText: t('audioMsgText'),
      videoMsgText: t('videoMsgText'),
      fileMsgText: t('fileMsgText'),
      callMsgText: t('callMsgText'),
      geoMsgText: t('geoMsgText'),
      imgMsgText: t('imgMsgText'),
      notiMsgText: t('notiMsgText'),
      robotMsgText: t('robotMsgText'),
      tipMsgText: t('tipMsgText'),
      unknowMsgText: t('unknowMsgText')
    }

    return `[${textMap[key] || ''}]`
  }

  // 解析文本和表情
  const parseTextWithEmoji = (text: string): ParsedItem[] => {
    if (!text) return []

    const matches: ParsedItem[] = []
    let match
    const regexEmoji = emojiRegExp
    
    // 重置正则表达式的lastIndex
    regexEmoji.lastIndex = 0
    
    // 使用一个临时变量记录已处理的位置
    let lastIndex = 0
    
    // 找出所有表情符号，并记录它们之间的文本
    while ((match = regexEmoji.exec(text)) !== null) {
      // 如果表情前面有文本，记录下来
      if (match.index > lastIndex) {
        const textBefore = text.slice(lastIndex, match.index)
        if (textBefore) {
          matches.push({
            type: 'text',
            value: textBefore,
            index: lastIndex
          })
        }
      }
      
      // 记录表情
      matches.push({
        type: 'emoji',
        value: match[0],
        index: match.index
      })
      
      lastIndex = match.index + match[0].length
    }
    
    // 如果最后还有剩余文本，记录下来
    if (lastIndex < text.length) {
      const remainingText = text.slice(lastIndex)
      if (remainingText) {
        matches.push({
          type: 'text',
          value: remainingText,
          index: lastIndex
        })
      }
    }

    // 按索引排序
    return matches.sort((a, b) => a.index - b.index)
  }

  // 解析文本内容
  const textArr = useMemo(() => {
    return parseTextWithEmoji(lastMessage.text as string)
  }, [lastMessage.text])

  // 根据消息状态和类型显示不同内容
  if (lastMessage.lastMessageState === V2NIMConst.V2NIMLastMessageState.V2NIM_MESSAGE_STATUS_REVOKE) {
    return <div>{t('recall')}</div>
  }

  if (lastMessage.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION) {
    return <div>{t('conversationNotificationText')}</div>
  }

  if (lastMessage.sendingState === V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_FAILED) {
    return <div>{t('conversationSendFailText')}</div>
  }

  switch (lastMessage.messageType) {
    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_FILE:
      return <div>{translateMsg('fileMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_IMAGE:
      return <div>{translateMsg('imgMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM:
      if (parseMergedForwardPayload(lastMessage as any)) {
        return <div>{`[${t('chatHistoryText')}]`}</div>
      }
      return <div>{lastMessage.text || translateMsg('customMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_AUDIO:
      return <div>{translateMsg('audioMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL:
      return <div>{translateMsg('callMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_LOCATION:
      return <div>{translateMsg('geoMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_ROBOT:
      return <div>{translateMsg('robotMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TIPS:
      return <div>{translateMsg('tipMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_VIDEO:
      return <div>{translateMsg('videoMsgText')}</div>

    case V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TEXT:
      return (
        <div className="msg-conversation-text-wrap">
          {textArr.map((item, index) =>
            item.type === 'text' ? (
              <span key={index} className="msg-conversation-text">
                {item.value}
              </span>
            ) : (
              <span key={index} className="msg-conversation-text-emoji">
                <Icon type={EMOJI_ICON_MAP_CONFIG[item.value]} size={16} />
              </span>
            )
          )}
        </div>
      )

    default:
      return <div>{translateMsg('unknowMsgText')}</div>
  }
})

export default LastMsgContent

// src/components/NEUIKit/Conversation/conversation-item-last-msg-content.vue
<template>
  <div>
    <div
      v-if="
        props.lastMessage.lastMessageState ===
        V2NIMConst.V2NIMLastMessageState.V2NIM_MESSAGE_STATUS_REVOKE
      "
    >
      {{ t("recall") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION
      "
    >
      {{ t("conversationNotificationText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.sendingState ===
        V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_FAILED
      "
    >
      {{ t("conversationSendFailText") }}
    </div>

    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_FILE
      "
    >
      {{ translateMsg("fileMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_IMAGE
      "
    >
      {{ translateMsg("imgMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM
      "
    >
      {{ props.lastMessage.text || translateMsg("customMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_AUDIO
      "
    >
      {{ translateMsg("audioMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL
      "
    >
      {{ translateMsg("callMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_LOCATION
      "
    >
      {{ translateMsg("geoMsgText") }}
    </div>

    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_ROBOT
      "
    >
      {{ translateMsg("robotMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TIPS
      "
    >
      {{ translateMsg("tipMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_VIDEO
      "
    >
      {{ translateMsg("videoMsgText") }}
    </div>
    <div
      v-else-if="
        props.lastMessage.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TEXT
      "
      class="msg-conversation-text-wrap"
    >
      <template v-for="item in textArr">
        <template v-if="item.type === 'text'">
          <span class="msg-conversation-text">{{ item.value }}</span>
        </template>
        <template v-else-if="item.type === 'emoji'">
          <span class="msg-conversation-text-emoji">
            <Icon :type="EMOJI_ICON_MAP_CONFIG[item.value]" :size="16" />
          </span>
        </template>
      </template>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import Icon from "../CommonComponents/Icon.vue";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import { t } from "../utils/i18n";
import { V2NIMLastMessage } from "nim-web-sdk-ng/dist/esm/nim/src/V2NIMConversationService";
import { EMOJI_ICON_MAP_CONFIG, emojiRegExp } from "../utils/emoji";
const props = withDefaults(
  defineProps<{
    lastMessage: V2NIMLastMessage;
  }>(),
  {}
);

// 筛选出文本和表情
const parseTextWithEmoji = (text: string) => {
  if (!text) return [];
  const matches: {
    type: "emoji" | "text";
    value: string;
    index: number;
  }[] = [];
  let match;
  const regexEmoji = emojiRegExp;

  while ((match = regexEmoji.exec(text)) !== null) {
    matches.push({
      type: "emoji",
      value: match[0],
      index: match.index,
    });
    const fillText = " ".repeat(match[0].length);
    text = text.replace(match[0], fillText);
  }

  text = text.replace(regexEmoji, " ");

  if (text) {
    text
      .split(" ")
      .filter((item) => item.trim())
      .map((item) => {
        const index = text?.indexOf(item);
        matches.push({
          type: "text",
          value: item,
          index,
        });
        const fillText = " ".repeat(item.length);
        text = text.replace(item, fillText);
      });
  }

  return matches.sort((a, b) => a.index - b.index);
};

const textArr = computed(() => {
  return parseTextWithEmoji(props.lastMessage.text as string);
});

const translateMsg = (key: string): string => {
  const text =
    {
      textMsgText: t("textMsgText"),
      customMsgText: t("customMsgText"),
      audioMsgText: t("audioMsgText"),
      videoMsgText: t("videoMsgText"),
      fileMsgText: t("fileMsgText"),
      callMsgText: t("callMsgText"),
      geoMsgText: t("geoMsgText"),
      imgMsgText: t("imgMsgText"),
      notiMsgText: t("notiMsgText"),
      robotMsgText: t("robotMsgText"),
      tipMsgText: t("tipMsgText"),
      unknowMsgText: t("unknowMsgText"),
    }[key] || "";
  return `[${text}]`;
};
</script>

<style scoped>
.wrapper {
  flex: 1;
  font-size: 13px;
  width: 100%;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.msg-conversation-text {
  font-size: 13px !important;
  height: 22px;
  line-height: 22px;
  width: 100%;
  display: inline;
}

.msg-conversation-text-wrap {
  width: 100%;
  line-height: 22px;
  height: 22px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  box-sizing: border-box;
  font-size: 14px;
}
.msg-conversation-text-emoji {
  display: inline-flex;
  width: 18px;
  height: 18px;
  box-sizing: border-box;
  align-items: center;
  justify-content: center;
}

.msg-conversation-text-emoji-wx {
  display: inline-flex;
  width: 18px;
  height: 18px;
  box-sizing: border-box;
  align-items: center;
  justify-content: center;
  position: relative;
  bottom: 4px;
}
</style>
