// nim-kit-react-ui-h5/src/NEUIKit/chat/message/message-item/index.tsx
import React, { useState, useMemo, useEffect } from 'react'
import { observer } from 'mobx-react-lite'
import Avatar from '@/NEUIKit/common/components/Avatar'
import MessageBubble from '@/NEUIKit/chat/message/message-bubble'
import MessageFile from '@/NEUIKit/chat/message/message-file'
import MessageText from '@/NEUIKit/chat/message/message-text'
import MessageAudio from '@/NEUIKit/chat/message/message-audio'
import MessageNotification from '@/NEUIKit/chat/message/message-notification'
import MessageG2 from '@/NEUIKit/chat/message/message-g2'
import MessageRead from '@/NEUIKit/chat/message/message-read'
import ReplyMessage from '@/NEUIKit/chat/message/message-reply'
import MergedForwardCard from '@/NEUIKit/chat/message/merged-forward/card'
import Icon from '@/NEUIKit/common/components/Icon'
import PreviewImage from '@/NEUIKit/common/components/PreviewImage'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { events, MSG_ID_FLAG } from '@/NEUIKit/common/utils/constants'
import emitter from '@/NEUIKit/common/utils/eventBus'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import { getPinOperatorId, isMessagePinned } from '@/NEUIKit/chat/message-pin/utils'
import { isSelectableMessage } from '@/NEUIKit/chat/message/message-multi-select/utils'
import { isMergedForwardMsg } from '@/NEUIKit/chat/message/merged-forward/utils'
import { getImageAttachmentSize, getImageRenderStyle, getImageThumbUrl } from '@/NEUIKit/common/utils/image'
import './index.less'

interface MessageItemProps {
  msg: V2NIMMessageForUI & { timeValue?: number }
  index: number
  replyMsgsMap?: {
    [key: string]: V2NIMMessageForUI
  }
  broadcastNewAudioSrc: string
  /**
   * 语音转文字结果映射
   */
  voiceTextMap?: Map<string, string>
  /**
   * 设置语音转文字结果
   */
  setVoiceText?: (messageClientId: string, text: string) => void
  isMultiSelecting?: boolean
  selected?: boolean
  onToggleSelect?: (msg: V2NIMMessageForUI) => void
  onMultiSelect?: (msg: V2NIMMessageForUI) => void
  readonly?: boolean
}

/**
 * 消息项组件，根据不同的消息类型展示不同的消息内容
 */
const MessageItem: React.FC<MessageItemProps> = observer(({ msg, index, replyMsgsMap = {}, broadcastNewAudioSrc, voiceTextMap = new Map(), setVoiceText, isMultiSelecting = false, selected = false, onToggleSelect, onMultiSelect, readonly = false }) => {
  const { t } = useTranslation()
  const { store, nim, locale } = useStateContext()

  // 图片预览状态
  const [isPreviewVisible, setIsPreviewVisible] = useState(false)

  // 回复消息
  const replyMsg = useMemo(() => {
    return replyMsgsMap && replyMsgsMap[msg.messageClientId]
  }, [msg.messageClientId, replyMsgsMap])

  const canParseConversationId = !readonly && !!msg.conversationId

  // 会话类型
  const conversationType = readonly
    ? (msg.conversationType as unknown as V2NIMConst.V2NIMConversationType)
    : (nim.V2NIMConversationIdUtil.parseConversationType(msg.conversationId) as unknown as V2NIMConst.V2NIMConversationType)

  // 会话对象
  const to = canParseConversationId ? nim.V2NIMConversationIdUtil.parseConversationTargetId(msg.conversationId) : ''

  // 昵称展示顺序 群昵称 > 备注 > 个人昵称 > 帐号
  const appellation = store.uiStore.getAppellation({
    account: msg.senderId,
    teamId: conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM ? to : ''
  })

  const mergedForwardSenderInfo = useMemo(() => {
    let serverExtension: Record<string, string> = {}

    try {
      serverExtension = JSON.parse(msg.serverExtension || '{}')
    } catch {
      serverExtension = {}
    }

    return {
      nick: serverExtension.mergedMessageNickKey || (msg as any).fromNick || msg.senderId,
      avatar: serverExtension.mergedMessageAvatarKey || ''
    }
  }, [msg.serverExtension, msg.senderId, (msg as any).fromNick])

  const senderName = readonly ? mergedForwardSenderInfo.nick : appellation
  const senderAvatar = readonly ? mergedForwardSenderInfo.avatar : ''
  const showSenderName = readonly || !msg.isSelf
  const readonlyAudioText = t('audioMsgText')
  const readonlyCallText = (msg.attachment as any)?.type == 1 ? t('voiceCallText') : t('videoCallText')
  const canAitSender =
    !readonly &&
    !msg.isSelf &&
    conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM

  const pinInfoMap = store.msgStore.pinMsgs.map.get(msg.conversationId)
  const pinOperatorId = getPinOperatorId(msg, pinInfoMap)
  const pinOperatorName = pinOperatorId
    ? store.uiStore.getAppellation({
        account: pinOperatorId,
        teamId: conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM ? to : ''
      })
    : ''
  const pinTipName = pinOperatorId === store.userStore.myUserInfo?.accountId ? t('you') : pinOperatorName || pinOperatorId

  // 群ID
  const teamId = useMemo(() => {
    if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM) {
      return to
    }
    return ''
  }, [conversationType, to])

  const handleAvatarLongpress = () => {
    if (!canAitSender) return

    emitter.emit(events.AIT_TEAM_MEMBER, {
      accountId: msg.senderId,
      appellation: store.uiStore.getAppellation({
        account: msg.senderId,
        teamId,
        ignoreAlias: true
      })
    })
  }

  const senderAvatarNode = (
    <Avatar
      account={msg.senderId}
      teamId={teamId}
      avatar={senderAvatar}
      nickFromMsg={senderName}
      gotoUserCard={!readonly}
      onLongpress={handleAvatarLongpress}
    />
  )

  // 获取视频首帧
  const videoFirstFrameDataUrl = useMemo(() => {
    //@ts-ignore
    const url = msg.attachment?.url
    return url ? `${url}${url.includes('?') ? '&' : '?'}vframe=1` : ''
  }, [msg.attachment])

  // 图片URL
  const imageUrl = useMemo(() => {
    if (!(msg && msg.attachment)) {
      return ''
    }
    // 被拉黑
    if (msg.messageStatus?.errorCode === 102426) {
      return 'https://yx-web-nosdn.netease.im/common/c1f278b963b18667ecba4ee9a6e68047/img-fail.png'
    }
    if ('url' in msg.attachment) return msg.attachment.url
    if ('file' in msg.attachment) return URL.createObjectURL(msg.attachment.file as File)

    return ''
  }, [msg.attachment, msg.messageStatus?.errorCode])

  const thumbnail = useMemo(() => {
    const { width, height } = getImageAttachmentSize(msg.attachment)
    return getImageThumbUrl(imageUrl, width, height)
  }, [imageUrl, msg.attachment])

  const imageRenderStyle = useMemo(() => {
    const { width, height } = getImageAttachmentSize(msg.attachment)
    return getImageRenderStyle(width, height, 'chat')
  }, [msg.attachment])

  // 点击图片预览
  const handleImageTouch = (url: string) => {
    if (url) {
      setIsPreviewVisible(true)
    }
  }

  // 点击视频播放
  const handleVideoTouch = (msg: V2NIMMessageForUI) => {
    //@ts-ignore
    const url = msg.attachment?.url
    if (url) {
      // 在新窗口打开视频
      window.open(url, '_blank', 'noopener,noreferrer')
    }
  }

  // 重新编辑消息
  const handleReeditMsg = (msg: V2NIMMessageForUI) => {
    emitter.emit(events.ON_REEDIT_MSG, msg)
  }

  // 消息置顶类判断
  const isPinned = isMessagePinned(msg) && !(msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && msg.timeValue !== undefined) && !msg.recallType
  const isEnglish = locale === 'en'
  const pinTip = isEnglish ? `${t('pinThisText')} ${pinTipName}` : `${pinTipName}${t('pinThisText')}`
  const pinTipNode = isPinned ? (
    <div className={msg.isSelf ? 'msg-pin-tip msg-pin-tip-self' : 'msg-pin-tip'}>
      <Icon type="icon-green-pin" size={12} />
      <span className="msg-pin-tip-text">{pinTip}</span>
    </div>
  ) : null
  const selectable = isSelectableMessage(msg)
  const bubbleMultiSelectProps = selectable && !readonly ? {
    isMultiSelecting,
    onMultiSelect
  } : {}
  const handleMultiSelectItemClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (!isMultiSelecting || !selectable) return
    event.preventDefault()
    event.stopPropagation()
    onToggleSelect?.(msg)
  }

  return (
    <div
      className={`msg-item-wrapper ${isPinned ? 'msg-pin' : ''} ${isMultiSelecting ? 'msg-item-multi-selecting' : ''} ${isMultiSelecting && selectable ? 'msg-item-selectable' : ''}`}
      id={MSG_ID_FLAG + msg.messageClientId}
      key={msg.createTime}
      onClickCapture={handleMultiSelectItemClick}
    >
      {isMultiSelecting && selectable && !readonly && (
        <div className="msg-select-column">
          <div className={`msg-select-box ${selected ? 'selected' : ''}`}>{selected && <span className="msg-select-check">✓</span>}</div>
        </div>
      )}
      {/* 消息时间间隔提示 */}
      {msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && msg.timeValue !== undefined ? (
        <div className="msg-time">{msg.timeValue}</div>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && msg.recallType === 'reCallMsg' && msg.canEdit ? (
        /* 撤回消息-可重新编辑 */
        <div
          className="msg-common"
          style={{
            flexDirection: !msg.isSelf ? 'row' : 'row-reverse'
          }}
        >
          {senderAvatarNode}
          <MessageBubble msg={msg} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
            <span className="recall-text">{t('recall2')}</span>
            <span className="msg-recall-btn" onClick={() => handleReeditMsg(msg)}>
              {t('reeditText')}
            </span>
          </MessageBubble>
        </div>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && msg.recallType === 'reCallMsg' && !msg.canEdit ? (
        /* 撤回消息-不可重新编辑 */
        <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
          {senderAvatarNode}
          <MessageBubble msg={msg} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
            <div className="recall-text">{t('you') + t('recall')}</div>
          </MessageBubble>
        </div>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && msg.recallType === 'beReCallMsg' ? (
        /* 撤回消息-对方撤回 */
        <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
          {senderAvatarNode}
          <div className="msg-content">
            {showSenderName && <div className="msg-name">{senderName}</div>}
            <div className={msg.isSelf ? 'self-msg-recall' : 'msg-recall'}>
              <span className="msg-recall2">{!msg.isSelf ? t('recall2') : `${t('you') + t('recall')}`}</span>
            </div>
          </div>
        </div>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TEXT ? (
        /* 文本消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
                {!!replyMsg && <ReplyMessage replyMsg={replyMsg} />}
                <MessageText msg={msg} disableAit={readonly} />
              </MessageBubble>
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_IMAGE ? (
        /* 图片消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
                <div onClick={() => handleImageTouch(imageUrl)}>
                  {msg.sendingState === V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_SENDING ? (
                    <div className="msg-image" style={imageRenderStyle}>
                      <div className="loading-spinner"></div>
                    </div>
                  ) : (
                    <img className="msg-image" style={imageRenderStyle} loading="lazy" src={thumbnail} alt="图片" />
                  )}
                </div>
              </MessageBubble>
              {/* 图片预览 */}
              {isPreviewVisible && <PreviewImage visible={isPreviewVisible} imageUrl={imageUrl} onClose={() => setIsPreviewVisible(false)} />}
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_VIDEO ? (
        /* 视频消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
                <div className="video-msg-wrapper" onClick={() => handleVideoTouch(msg)}>
                  <div className="video-play-button">
                    <div className="video-play-icon"></div>
                  </div>
                  <img className="msg-image" style={imageRenderStyle} loading="lazy" src={videoFirstFrameDataUrl} alt="视频封面" />
                </div>
              </MessageBubble>
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL ? (
        /* 音视频通话消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
                {readonly ? `[${readonlyCallText}]` : <MessageG2 msg={msg} />}
              </MessageBubble>
            </div>
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_FILE ? (
        /* 文件消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={false} readonly={readonly} {...bubbleMultiSelectProps}>
                <MessageFile msg={msg} />
              </MessageBubble>
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_AUDIO ? (
        /* 语音消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} voiceTextMap={voiceTextMap} setVoiceText={setVoiceText} readonly={readonly} {...bubbleMultiSelectProps}>
                {readonly ? `[${readonlyAudioText}]` : <MessageAudio msg={msg} broadcastNewAudioSrc={broadcastNewAudioSrc} voiceText={voiceTextMap.get(msg.messageClientId as string)} />}
              </MessageBubble>
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM && isMergedForwardMsg(store, msg) ? (
        /* 合并转发消息 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={false} readonly={readonly} {...bubbleMultiSelectProps}>
                <MergedForwardCard msg={msg} />
              </MessageBubble>
            </div>
            {msg?.isSelf && !readonly && <MessageRead msg={msg} />}
          </div>
          {pinTipNode}
        </>
      ) : msg.messageType === V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION ? (
        /* 通知消息 */
        <MessageNotification msg={msg} />
      ) : (
        /* 未知消息类型 */
        <>
          <div className="msg-common" style={{ flexDirection: !msg.isSelf ? 'row' : 'row-reverse' }}>
            {senderAvatarNode}
            <div className="msg-content">
              {showSenderName && <div className="msg-name">{senderName}</div>}
              <MessageBubble msg={msg} tooltipVisible={true} bgVisible={true} readonly={readonly} {...bubbleMultiSelectProps}>
                [{t('unknowMsgText')}]
              </MessageBubble>
            </div>
          </div>
          {pinTipNode}
        </>
      )}
    </div>
  )
})

export default MessageItem

// src/components/NEUIKit/Chat/message/message-item.vue
<template>
  <div
    :class="`msg-item-wrapper ${
      props.msg.pinState &&
      !(
        props.msg.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        props.msg.timeValue !== undefined
      ) &&
      !props.msg.recallType
        ? 'msg-pin'
        : ''
    }`"
    :id="MSG_ID_FLAG + props.msg.messageClientId"
    :key="props.msg.createTime"
  >
    <!-- 消息时间间隔提示 -->
    <div
      class="msg-time"
      v-if="
        props.msg.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        props.msg.timeValue !== undefined
      "
    >
      {{ props.msg.timeValue }}
    </div>
    <!-- 撤回消息-可重新编辑 -->
    <div
      class="msg-common"
      :style="{
        flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse',
      }"
      v-else-if="
        props.msg.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        props.msg.recallType === 'reCallMsg' &&
        props.msg.canEdit
      "
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <MessageBubble :msg="props.msg" :bg-visible="true">
        <span class="recall-text">{{ t("recall2") }}</span>
        <text
          class="msg-recall-btn"
          @click="
            () => {
              handleReeditMsg(props.msg);
            }
          "
        >
          {{ t("reeditText") }}
        </text>
      </MessageBubble>
    </div>
    <!-- 撤回消息-不可重新编辑 -->
    <div
      class="msg-common"
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
      v-else-if="
        props.msg.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        props.msg.recallType === 'reCallMsg' &&
        !props.msg.canEdit
      "
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <MessageBubble :msg="props.msg" :bg-visible="true">
        <div class="recall-text">{{ t("you") + t("recall") }}</div>
      </MessageBubble>
    </div>
    <!-- 撤回消息-对方撤回-->
    <div
      class="msg-common"
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
      v-else-if="
        props.msg.messageType ===
          V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CUSTOM &&
        props.msg.recallType === 'beReCallMsg'
      "
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <div :class="props.msg.isSelf ? 'self-msg-recall' : 'msg-recall'">
          <text class="msg-recall2">
            {{ !props.msg.isSelf ? t("recall2") : `${t("you") + t("recall")}` }}
          </text>
        </div>
      </div>
    </div>
    <!-- 文本消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_TEXT
      "
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
        >
          <ReplyMessage v-if="!!replyMsg" :replyMsg="replyMsg"></ReplyMessage>
          <MessageText :msg="props.msg"></MessageText>
        </MessageBubble>
      </div>
      <MessageIsRead v-if="props.msg?.isSelf" :msg="props.msg"></MessageIsRead>
    </div>
    <!-- 图片消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_IMAGE
      "
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
        >
          <div
            @click="
              () => {
                //@ts-ignore
                handleImageTouch(props.msg.attachment.url);
              }
            "
          >
          <div class="msg-image" v-if="props.msg.sendingState == V2NIMConst.V2NIMMessageSendingState.V2NIM_MESSAGE_SENDING_STATE_SENDING">
            <div 
              class="loading-spinner"
            ></div>
          </div>
            <img
              v-else
              class="msg-image"
              :lazy-load="true"
              mode="aspectFill"
              :src="imageUrl"
            />
          </div>
        </MessageBubble>
        <!-- 图片预览 -->
        <PreviewImage
          :visible="isPreviewVisible"
          :image-url="imageUrl"
          :onClose="
            () => {
              isPreviewVisible = false;
            }
          "
        />
      </div>
      <MessageIsRead v-if="props.msg?.isSelf" :msg="props.msg"></MessageIsRead>
    </div>
    <!-- 视频消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_VIDEO
      "
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
          style="cursor: pointer"
        >
          <div
            class="video-msg-wrapper"
            @click="() => handleVideoTouch(props.msg)"
          >
            <div class="video-play-button">
              <div class="video-play-icon"></div>
            </div>
            <img
              class="msg-image"
              :lazy-load="true"
              mode="aspectFill"
              :src="videoFirstFrameDataUrl"
            ></img>
          </div>
        </MessageBubble>
      </div>
      <MessageIsRead v-if="props.msg?.isSelf" :msg="props.msg"></MessageIsRead>
    </div>
    <!-- 音视频消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_CALL
      "
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
        >
          <MessageG2 :msg="props.msg" />
        </MessageBubble>
      </div>
    </div>
    <!-- 文件消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_FILE
      "
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="false"
        >
          <MessageFile :msg="props.msg" />
        </MessageBubble>
      </div>
      <MessageIsRead v-if="props.msg?.isSelf" :msg="props.msg"></MessageIsRead>
    </div>
    <!-- 语音消息 -->
    <div
      class="msg-common"
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_AUDIO
      "
      :style="{
        flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse',
      }"
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
          style="cursor: pointer"
        >
          <MessageAudio
            :msg="props.msg"
            :broadcastNewAudioSrc="broadcastNewAudioSrc"
          />
        </MessageBubble>
      </div>
      <MessageIsRead v-if="props.msg?.isSelf" :msg="props.msg"></MessageIsRead>
    </div>
    <!-- 通知消息 -->
    <MessageNotification
      v-else-if="
        props.msg.messageType ===
        V2NIMConst.V2NIMMessageType.V2NIM_MESSAGE_TYPE_NOTIFICATION
      "
      :msg="props.msg"
    />
    <!-- 未知消息 -->
    <div
      class="msg-common"
      :style="{ flexDirection: !props.msg.isSelf ? 'row' : 'row-reverse' }"
      v-else
    >
      <Avatar
        :account="props.msg.senderId"
        :teamId="teamId"
        :goto-user-card="true"
      />
      <div class="msg-content">
        <div class="msg-name" v-if="!props.msg.isSelf">
          {{ appellation }}
        </div>
        <MessageBubble
          :msg="props.msg"
          :tooltip-visible="true"
          :bg-visible="true"
        >
          [{{ t("unknowMsgText") }}]
        </MessageBubble>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import {
  ref,
  computed,
  onUnmounted,
  getCurrentInstance,
} from "vue";
import Avatar from "../../CommonComponents/Avatar.vue";
import MessageBubble from "./message-bubble.vue";
import { events, MSG_ID_FLAG } from "../../utils/constants";
import { autorun } from "mobx";
import { t } from "../../utils/i18n";
import ReplyMessage from "./message-reply.vue";
import MessageFile from "./message-file.vue";
import MessageText from "./message-text.vue";
import MessageAudio from "./message-audio.vue";
import MessageNotification from "./message-notification.vue";
import MessageG2 from "./message-g2.vue";
import { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/types";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import MessageIsRead from "./message-read.vue";
import emitter from "../../utils/eventBus";
import PreviewImage from "../../CommonComponents/PreviewImage.vue";



const isPreviewVisible = ref(false);
const props = withDefaults(
  defineProps<{
    msg: V2NIMMessageForUI & { timeValue?: number };
    index: number;
    replyMsgsMap?: {
      [key: string]: V2NIMMessageForUI;
    };
    broadcastNewAudioSrc: string;
  }>(),
  {}
);

const replyMsg = computed(() => {
  return props.replyMsgsMap && props.replyMsgsMap[props.msg.messageClientId];
});
const { proxy } = getCurrentInstance()!; // 获取组件实例

// 昵称
const appellation = ref("");
const accountId = proxy?.$UIKitStore.userStore?.myUserInfo.accountId;

// 会话类型
const conversationType =
  proxy?.$NIM.V2NIMConversationIdUtil.parseConversationType(
    props.msg.conversationId
  ) as unknown as V2NIMConst.V2NIMConversationType;
// 会话对象
const to = proxy?.$NIM.V2NIMConversationIdUtil.parseConversationTargetId(
  props.msg.conversationId
);

// 获取视频首帧
const videoFirstFrameDataUrl = computed(() => {
  //@ts-ignore
  const url = props.msg.attachment?.url;
  return url ? `${url}${url.includes("?") ? "&" : "?"}vframe=1` : "";
});

// 图片
const imageUrl = computed(() => {
  // 被拉黑
  if (props.msg.messageStatus.errorCode == 102426) {
    return "https://yx-web-nosdn.netease.im/common/c1f278b963b18667ecba4ee9a6e68047/img-fail.png";
  }
  //@ts-ignore
  return props.msg?.attachment?.url || props.msg.attachment?.file;
});

// 点击图片预览
const handleImageTouch = (url: string) => {
  if (url) {
    isPreviewVisible.value = true;
  }
};

// 点击视频播放
const handleVideoTouch = (msg: V2NIMMessageForUI) => {
   //@ts-ignore
   const url = msg.attachment?.url;
  if (url) {
    // 在新窗口打开视频
    window.open(url, '_blank', 'noopener,noreferrer');
  }
};

// 重新编辑消息
const handleReeditMsg = (msg: V2NIMMessageForUI) => {
  
  emitter.emit(events.ON_REEDIT_MSG, msg);
};

// 监听昵称变化
const uninstallAppellationWatch = autorun(() => {
  // 昵称展示顺序 群昵称 > 备注 > 个人昵称 > 帐号
  appellation.value = proxy?.$UIKitStore.uiStore.getAppellation({
    account: props.msg.senderId,
    teamId:
      conversationType ===
      V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
        ? to
        : "",
  }) as string;
});

const teamId = computed(() => {
  if (
    conversationType ===
    V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
  ) {
    return to;
  }
  return "";
});

onUnmounted(() => {
  uninstallAppellationWatch();
});
</script>

<style scoped>
.msg-item-wrapper {
  padding: 0 10px 10px 10px;
}

.msg-common {
  padding-top: 8px;
  display: flex;
  align-items: flex-start;
  font-size: 16px;
}
.msg-pin {
  opacity: 1;
  background: #fffbea;
}
.msg-pin-tip {
  font-size: 11px;
  font-weight: normal;
  color: #3eaf96;
  margin: 8px 50px 0 50px;
  display: flex;
  align-items: center;
  white-space: nowrap;
  overflow: hidden;
}
.loading-spinner {
  width: 20px;
  height: 20px;
  border: 2px solid #f3f3f3;
  border-top: 2px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 10px auto;
  position: relative;
  top: 50%;
  transform: translateY(-50%);

}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.msg-content {
  display: flex;
  flex-direction: column;
}

.msg-name {
  font-size: 12px;
  color: #999;
  text-align: left;
  margin-bottom: 4px;
  max-width: 300px;
  padding-left: 8px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.msg-image {
  max-width: 100%;
  min-width: 150px;
  height: 200px;
  display: inline-block;
}

.msg-time {
  margin-top: 8px;
  text-align: center;
  color: #b3b7bc;
  font-size: 12px;
}

.msg-recall-btn {
  margin-left: 5px;
  color: #1861df;
}

.msg-recall2 {
  font-size: 16px;
}

.self-msg-recall {
  max-width: 360px;
  overflow: hidden;
  padding: 12px 16px;
  border-radius: 8px 0px 8px 8px;
  margin-right: 8px;
  background-color: #d6e5f6;
  color: #666666;
}

.recall-text{
  color: #666666;
}

.msg-recall {
  max-width: 360px;
  width: fit-content;
  overflow: hidden;
  padding: 12px 16px;
  border-radius: 0px 8px 8px 8px;
  margin-left: 8px;
  background-color: #e8eaed;
  color: #666666;
}

.recall-text {
  color: #666666;
}

.video-play-button {
  width: 50px;
  height: 50px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: rgba(0, 0, 0, 0.5);
  border-radius: 50%;
  z-index: 9;
}

.video-play-icon {
  width: 0;
  height: 0;
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent;
  border-left: 18px solid #fff;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-40%, -50%);
}

.video-msg-wrapper {
  box-sizing: border-box;
  max-width: 360px;
}
</style>
../../utils/router
