// nim-kit-react-ui-h5/src/NEUIKit/chat/message/message-g2/index.tsx
import React, { useMemo } from 'react'
import { observer } from 'mobx-react-lite'
import Icon from '@/NEUIKit/common/components/Icon'
import { convertSecondsToTime } from '@/NEUIKit/common/utils'
import { g2StatusMap } from '@/NEUIKit/common/utils/constants'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import './index.less'

interface MessageG2Props {
  msg: V2NIMMessageForUI
}

/**
 * 音视频通话记录消息组件
 */
const MessageG2: React.FC<MessageG2Props> = observer(({ msg }) => {
  // 获取通话时长
  const duration = useMemo(() => {
    //@ts-ignore
    return convertSecondsToTime(msg.attachment?.durations[0]?.duration)
  }, [msg.attachment])

  // 获取通话状态
  const status = useMemo(() => {
    //@ts-ignore
    return g2StatusMap[msg.attachment?.status]
  }, [msg.attachment])

  // 根据通话类型决定图标
  const iconType = useMemo(() => {
    //@ts-ignore
    return msg.attachment?.type == 1 ? 'icon-yuyin8' : 'icon-shipin8'
  }, [msg.attachment])

  return (
    <div className="g2-message-wrapper">
      <Icon type={iconType} size={28} />
      <div className="g2-message-status">{status}</div>
      {duration && <div className="g2-message-duration">{duration}</div>}
    </div>
  )
})

export default MessageG2

// src/components/NEUIKit/Chat/message/message-g2.vue
<template>
  <div class="g2-message-wrapper">
    <Icon :type="iconType" :size="28"></Icon>
    <div class="g2-message-status">{{ status }}</div>
    <div v-if="duration" class="g2-message-duration">{{ duration }}</div>
  </div>
</template>

<script lang="ts" setup>
import Icon from "../../CommonComponents/Icon.vue";
import { convertSecondsToTime } from "../../utils";
import { g2StatusMap } from "../../utils/constants";
import { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/types";

const props = withDefaults(defineProps<{ msg: V2NIMMessageForUI }>(), {});

const duration = convertSecondsToTime(
  //@ts-ignore
  props.msg.attachment?.durations[0]?.duration
);
//@ts-ignore
const status = g2StatusMap[props.msg.attachment?.status];
const iconType =
  //@ts-ignore
  props.msg.attachment?.type == 1 ? "icon-yuyin8" : "icon-shipin8";
</script>

<style scoped>
/* 音视频消息容器 */
.g2-message-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
}

/* 音视频消息状态 */
.g2-message-status {
  margin: 0 7px;
}

/* 音视频消息时长 */
.g2-message-duration {
  color: #666;
}
</style>
