// nim-kit-react-ui-h5/src/NEUIKit/chat/message/message-forward-modal/index.tsx
import React, { useState, useMemo } from 'react'
import { observer } from 'mobx-react-lite'
import Modal from '@/NEUIKit/common/components/Modal'
import Avatar from '@/NEUIKit/common/components/Avatar'
import Input from '@/NEUIKit/common/components/Input'
import { useTranslation } from '@/NEUIKit/common/hooks/useTranslate'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { V2NIMConst } from 'nim-web-sdk-ng/dist/esm/nim'
import type { V2NIMMessageForUI } from '@xkit-yx/im-store-v2/dist/types/src/types'
import './index.less'

interface ForwardToTeamInfo {
  teamId: string
  name: string
  avatar: string
}

interface MessageForwardModalProps {
  forwardModalVisible: boolean
  forwardTo: string
  forwardMsg: V2NIMMessageForUI | undefined
  sourceConversationId: string
  forwardConversationType: V2NIMConst.V2NIMConversationType
  forwardToTeamInfo?: ForwardToTeamInfo
  isOneByOneForward?: boolean
  isMergeForward?: boolean
  onConfirm: (comment: string) => void
  onCancel: () => void
}

/**
 * 消息转发模态框组件
 */
const MessageForwardModal: React.FC<MessageForwardModalProps> = observer(
  ({ forwardModalVisible, forwardTo, forwardMsg, sourceConversationId, forwardConversationType, forwardToTeamInfo, isOneByOneForward, isMergeForward, onConfirm, onCancel }) => {
    const { t } = useTranslation()
    const { store, nim } = useStateContext()

    // 转发评论
    const [forwardComment, setForwardComment] = useState('')

    // 处理输入变化
    const handleForwardInputChange = (value: string) => {
      setForwardComment(value)
    }

    // 处理取消
    const handleCancel = () => {
      onCancel()
    }

    // 处理确认
    const handleConfirm = () => {
      onConfirm(forwardComment)
    }

    // 转发消息的接收方昵称
    const forwardToNick = useMemo(() => {
      return store.uiStore.getAppellation({
        account: forwardTo
      })
    }, [forwardTo])

    // 转发消息所属会话名称
    const forwardSourceName = useMemo(() => {
      const conversationId = sourceConversationId || forwardMsg?.conversationId
      if (!conversationId) return ''

      const conversationType = nim.V2NIMConversationIdUtil.parseConversationType(conversationId) as unknown as V2NIMConst.V2NIMConversationType
      const targetId = nim.V2NIMConversationIdUtil.parseConversationTargetId(conversationId)

      if (conversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM) {
        return store.teamStore.teams.get(targetId)?.name || targetId
      }

      return (
        store.uiStore.getAppellation({
          account: targetId
        }) || targetId
      )
    }, [sourceConversationId, forwardMsg?.conversationId])

    return (
      <Modal
        title={t('sendToText')}
        visible={forwardModalVisible}
        confirmText={t('sendText')}
        cancelText={t('cancelText')}
        onCancel={handleCancel}
        onConfirm={handleConfirm}
      >
        <div className="message-forward-modal-wrapper">
          {forwardConversationType === V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM ? (
            <div className="avatar-wrapper">
              <Avatar account={forwardToTeamInfo?.teamId || ''} avatar={forwardToTeamInfo?.avatar} size="36" />
              <div className="name">{forwardToTeamInfo?.name || ''}</div>
            </div>
          ) : (
            <div className="avatar-wrapper">
              <Avatar account={forwardTo} size="36" />
              <div className="name">
                <span>{forwardToNick}</span>
              </div>
            </div>
          )}

          <div className="description">{`[${t(isMergeForward ? 'mergeForwardText' : isOneByOneForward ? 'oneByOneForwardText' : 'forwardText')}] ${forwardSourceName || ''} ${t('sessionRecordText')}`}</div>

          <Input
            id="forward-input"
            className="forward-input"
            value={forwardComment}
            onChange={handleForwardInputChange}
            placeholder={t('forwardComment')}
            inputStyle={{ height: '22px' }}
          />
        </div>
      </Modal>
    )
  }
)

export default MessageForwardModal

// src/components/NEUIKit/Chat/message/message-forward-modal.vue
<template>
  <Modal
    :title="t('sendToText')"
    :visible="forwardModalVisible"
    :confirmText="t('sendText')"
    :cancelText="t('cancelText')"
    @cancel="handleCancel"
    @confirm="handleConfirm"
  >
    <div
      v-if="
        props.forwardConversationType ===
        V2NIMConst.V2NIMConversationType.V2NIM_CONVERSATION_TYPE_TEAM
      "
      class="avatar-wrapper"
    >
      <Avatar
        :account="
          (props.forwardToTeamInfo && props.forwardToTeamInfo.teamId) || ''
        "
        :avatar="props.forwardToTeamInfo && props.forwardToTeamInfo.avatar"
        size="36"
      />
      <div class="name">
        {{ (props.forwardToTeamInfo && props.forwardToTeamInfo.name) || "" }}
      </div>
    </div>
    <div v-else class="avatar-wrapper">
      <Avatar :account="forwardTo" size="36" />
      <div class="name">
        <span>{{ forwardToNick }}</span>
      </div>
    </div>
    <div class="description">
      {{ "[" + t("forwardText") + "]" }}
      {{ forwardFromNick }}
      {{ t("sessionRecordText") }}
    </div>
    <Input
      class="forward-input"
      @input="handleForwardInputChange"
      :placeholder="t('forwardComment')"
      :inputStyle="{ height: '22px' }"
    />
  </Modal>
</template>

<script lang="ts" setup>
import { t } from "../../utils/i18n";
import { ref, computed, getCurrentInstance } from "vue";
import Modal from "../../CommonComponents/Modal.vue";
import Avatar from "../../CommonComponents/Avatar.vue";
import { V2NIMMessageForUI } from "@xkit-yx/im-store-v2/dist/types/types";
import { V2NIMConst } from "nim-web-sdk-ng/dist/esm/nim";
import Input from "../../CommonComponents/Input.vue";
interface ForwardToTeamInfo {
  teamId: string;
  name: string;
  avatar: string;
}

const props = withDefaults(
  defineProps<{
    forwardModalVisible: boolean;
    forwardTo: string;
    forwardMsg: V2NIMMessageForUI | undefined;
    forwardConversationType: V2NIMConst.V2NIMConversationType;
    forwardToTeamInfo?: ForwardToTeamInfo;
  }>(),
  {}
);

const emit = defineEmits(["confirm", "cancel"]);

const forwardComment = ref("");

const { proxy } = getCurrentInstance()!; // 获取组件实例

const handleForwardInputChange = (value) => {
  forwardComment.value = value;
};

const handleCancel = () => {
  emit("cancel");
};

const handleConfirm = () => {
  emit("confirm", forwardComment.value);
};

// 转发消息的接收方昵称
const forwardToNick = computed(() => {
  return proxy?.$UIKitStore.uiStore.getAppellation({
    account: props.forwardTo,
  });
});

// 转发消息的发送方昵称
const forwardFromNick = computed(() => {
  return proxy?.$UIKitStore.uiStore.getAppellation({
    account: props.forwardMsg?.senderId as string,
  });
});
</script>

<style scoped>
/* 描述文本 */
.description {
  font-size: 14px;
  height: 32px;
  color: #000;
  background-color: #f2f4f5;
  margin: 10px 0px;
  padding: 0 16px;
  line-height: 32px;
  border-radius: 4px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

/* 转发输入框 */
.forward-input {
  height: 32px;
  border: 1px solid #e1e6e8;
  border-radius: 4px;
  padding: 5px 8px;
  box-sizing: border-box;
}

/* 头像容器 */
.avatar-wrapper {
  display: flex;
  align-items: center;
  height: 36px;
  margin: 0px 10px;
}

/* 用户名称 */
.avatar-wrapper .name {
  margin-left: 10px;
  font-size: 14px;
  color: #000;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>
