// nim-kit-vue-ui-h5/src/components/NEUIKit/Login/components/login-form.vue
<template>
  <div>
    <div class="navigation-bar"></div>
    <div class="login-form-container">
      <div class="login-tabs">
        <span
          v-for="item in loginTabs.list"
          :key="item.key"
          :class="['login-tab', { active: loginTabs.active === item.key }]"
          @click="loginTabs.active = item.key"
        >
          <span>{{ item.title }}</span>
        </span>
      </div>
      <div class="login-tips">{{ i18n.loginTips }}</div>
      <div class="login-form">
        <FormInput
          className="login-form-input"
          type="tel"
          :value="loginForm.mobile"
          @updateModelValue="(val) => (loginForm.mobile = val)"
          :placeholder="i18n.mobilePlaceholder"
          :allow-clear="true"
          :rule="mobileInputRule"
        >
          <template #addonBefore>
            <span class="phone-addon-before">+86</span>
          </template>
        </FormInput>
        <FormInput
          className="login-form-input"
          type="tel"
          :value="loginForm.smsCode"
          @updateModelValue="(val) => (loginForm.smsCode = val)"
          :placeholder="i18n.smsCodePlaceholder"
          :rule="smsCodeInputRule"
        >
          <template #addonAfter>
            <span
              :class="[
                'sms-addon-after',
                { disabled: smsCount > 0 && smsCount < 60 },
              ]"
              @click="startSmsCount()"
              >{{ smsText }}</span
            >
          </template>
        </FormInput>
      </div>
    </div>
    <button class="login-btn" @click="submitLoginForm()">
      {{ i18n.loginBtnTitle }}
    </button>
  </div>
</template>

<script lang="ts" setup>
import { ref, reactive, computed, getCurrentInstance } from "vue";
import i18n from "../i18n/zh-cn";
import { getLoginSmsCode, loginRegisterByCode } from "../utils/api";
import FormInput from "./form-input.vue";
import { showToast } from "../../utils/toast";
import { inject } from "vue";
import { init } from "../../utils/init";
import { useRouter } from "vue-router";
import { neUiKitRouterPath } from "../../utils/uikitRouter";

const app = getCurrentInstance();
const router = useRouter();

const mobileInputRule = {
  reg: /^(13[0-9]|14[01456879]|15[0-35-9]|16[2567]|17[0-8]|18[0-9]|19[0-35-9])\d{8}$/,
  message: i18n.mobileErrorMsg,
  trigger: "blur",
};
const smsCodeInputRule = {
  reg: /^\d+$/,
  message: i18n.smsErrorMsg,
  trigger: "blur",
};

const smsCount = ref(60);
const loginTabs = reactive({
  active: 0,
  list: [{ key: 0, title: i18n.loginTitle }],
});
const loginForm = reactive({
  mobile: "",
  smsCode: "",
});

const smsText = computed(() => {
  if (smsCount.value > 0 && smsCount.value < 60) {
    return smsCount.value + i18n.smsCodeBtnTitleCount;
  } else {
    return i18n.smsCodeBtnTitle;
  }
});
// 获取验证码
async function startSmsCount() {
  if (!mobileInputRule.reg.test(loginForm.mobile)) {
    showToast({
      message: i18n.mobileErrorMsg,
      type: "info",
    });
    return;
  }
  try {
    await getLoginSmsCode({ mobile: loginForm.mobile });
  } catch (error: any) {
    let msg = error.errMsg || error.msg || error.message || i18n.smsCodeFailMsg;
    if (msg.startsWith("request:fail")) {
      msg = i18n.smsCodeNetworkErrorMsg;
    }
    showToast({
      message: msg,
      type: "info",
    });
    return;
  }

  if (smsCount.value > 0 && smsCount.value < 60) {
    return;
  }
  smsCount.value--;
  const timer = setInterval(() => {
    if (smsCount.value > 0) {
      smsCount.value--;
    } else {
      clearInterval(timer);
      smsCount.value = 60;
    }
  }, 1000);
}

// 登录
async function submitLoginForm() {
  if (
    !mobileInputRule.reg.test(loginForm.mobile) ||
    !smsCodeInputRule.reg.test(loginForm.smsCode)
  ) {
    showToast({
      message: i18n.mobileOrSmsCodeErrorMsg,
      type: "info",
    });
    return;
  }
  try {
    const res = await loginRegisterByCode(loginForm);
    // 存储登录信息到 localStorage
    localStorage.setItem(
      "__yx_im_options__h5",
      JSON.stringify({
        account: res.imAccid,
        token: res.imToken,
      })
    );

    const { nim, store } = init();
    if (app) {
      app.appContext.app.config.globalProperties.$NIM = nim;
      app.appContext.app.config.globalProperties.$UIKitStore = store;
    }

    const handelKickedOffline = () => {
      showToast({
        message: "您已被踢下线",
        type: "info",
      });
      router.push("/login");
      localStorage.removeItem("__yx_im_options__h5");
      store.destroy();
      nim.V2NIMLoginService.off("onKickedOffline", handelKickedOffline);
    };

    nim.V2NIMLoginService.login(res.imAccid, res.imToken)
      .then(() => {
        // IM 登录成功后跳转到会话页面
        router.push(neUiKitRouterPath.conversation);
        nim.V2NIMLoginService.on("onKickedOffline", handelKickedOffline);
      })
      .catch((error) => {
        if (error.code === 102422) {
          // 账号被封禁
          showToast({
            message: "当前账号已被封禁",
            type: "info",
          });
          // 登录信息无效，清除并跳转到登录页
          localStorage.removeItem("__yx_im_options__h5");
        }
      });
  } catch (error: any) {
    let msg = error.errMsg || error.msg || error.message || i18n.smsCodeFailMsg;
    if (msg.startsWith("request:fail")) {
      msg = i18n.loginNetworkErrorMsg;
    }
    showToast({
      message: msg,
      type: "info",
    });
  }
}
</script>

<style scoped>
.navigation-bar {
  height: 80px;
}

.login-form-container {
  padding: 0 30px;
}

.login-tab {
  display: inline-block;
  font-size: 22px;
  line-height: 31px;
  color: #666b73;
  margin-right: 20px;
  margin-bottom: 20px;
}

.login-tab.active {
  color: #222222;
  font-weight: bold;
}

.login-tab-active-line {
  display: block;
  width: 80px;
  height: 2px;
  background: #337eff;
  margin: 5px auto;
  border-radius: 2px;
}

.login-tips {
  font-size: 14px;
  line-height: 20px;
  color: #999999;
  margin-bottom: 20px;
}

.phone-addon-before {
  color: #999999;
  border-right: 1px solid #999999;
  padding: 0 5px;
  margin-right: 5px;
}

.sms-addon-after {
  color: #337eff;
}

.sms-addon-after.disabled {
  color: #666b73;
}

.login-form-input {
  margin-bottom: 20px;
  color: #333;
}

.login-btn {
  border: none;
  height: 50px;
  width: 90%;
  background: #337eff;
  border-radius: 8px;
  color: #fff;
  margin-top: 54px;
  position: relative;
  font-size: 16px;
  left: 50%;
  transform: translateX(-50%);
}
</style>

// nim-kit-react-ui-h5/src/NEUIKit/login/components/LoginForm.tsx
import React, { useState, useMemo } from 'react'
import { useNavigate } from '@/utils/router'

import FormInput from './FormInput'
import i18n from '../i18n/zh-CN'
import { getLoginSmsCode, loginRegisterByCode } from '../utils/api'
import { toast } from '@/NEUIKit/common/utils/toast'
import { useStateContext } from '@/NEUIKit/common/hooks/useStateContext'
import { neUiKitRouterPath } from '@/NEUIKit/common/utils/uikitRouter'

import './LoginForm.less'

/**
 * 登录表单组件
 */
const LoginForm: React.FC = () => {
  const navigate = useNavigate()
  const { nim } = useStateContext()

  // 短信倒计时
  const [smsCount, setSmsCount] = useState(60)

  // 登录选项卡
  const [loginTabs] = useState({
    active: 0,
    list: [{ key: 0, title: i18n.loginTitle }]
  })

  // 表单数据
  const [loginForm, setLoginForm] = useState({
    mobile: '',
    smsCode: ''
  })

  // 手机号输入规则
  const mobileInputRule = {
    reg: /^(13[0-9]|14[01456879]|15[0-35-9]|16[2567]|17[0-8]|18[0-9]|19[0-35-9])\d{8}$/,
    message: i18n.mobileErrorMsg,
    trigger: 'blur'
  }

  // 验证码输入规则
  const smsCodeInputRule = {
    reg: /^\d+$/,
    message: i18n.smsErrorMsg,
    trigger: 'blur'
  }

  // 计算短信按钮文字
  const smsText = useMemo(() => {
    if (smsCount > 0 && smsCount < 60) {
      return smsCount + i18n.smsCodeBtnTitleCount
    } else {
      return i18n.smsCodeBtnTitle
    }
  }, [smsCount])

  // 更新手机号
  const handleMobileChange = (value: string) => {
    setLoginForm((prev) => ({ ...prev, mobile: value }))
  }

  // 更新短信验证码
  const handleSmsCodeChange = (value: string) => {
    setLoginForm((prev) => ({ ...prev, smsCode: value }))
  }

  // 获取验证码
  const startSmsCount = async () => {
    // 如果倒计时已经开始，不重复发送
    if (smsCount > 0 && smsCount < 60) {
      return
    }

    // 验证手机号
    if (!mobileInputRule.reg.test(loginForm.mobile)) {
      toast.info(i18n.mobileErrorMsg)
      return
    }

    try {
      // 发送验证码请求
      await getLoginSmsCode({ mobile: loginForm.mobile })

      // 开始倒计时
      setSmsCount((prev) => prev - 1)
      const timer = setInterval(() => {
        setSmsCount((prev) => {
          if (prev > 0) {
            return prev - 1
          } else {
            clearInterval(timer)
            return 60
          }
        })
      }, 1000)
    } catch (error: any) {
      // 处理错误
      let msg = error.errMsg || error.msg || error.message || i18n.smsCodeFailMsg
      if (msg.startsWith('request:fail') || msg.startsWith('Failed to fetch')) {
        msg = i18n.smsCodeNetworkErrorMsg
      }
      toast.error(msg)
    }
  }

  // 提交登录表单
  const submitLoginForm = async () => {
    // 表单验证
    if (!mobileInputRule.reg.test(loginForm.mobile) || !smsCodeInputRule.reg.test(loginForm.smsCode)) {
      toast.info(i18n.mobileOrSmsCodeErrorMsg)
      return
    }

    try {
      // 登录请求
      const res = await loginRegisterByCode(loginForm)

      // 存储登录信息到 localStorage
      localStorage.setItem(
        '__yx_im_options__h5',
        JSON.stringify({
          account: res.imAccid,
          token: res.imToken
        })
      )

      // 执行 IM 登录（使用 Provider 中的 nim 实例，避免创建重复实例）
      nim.V2NIMLoginService.login(res.imAccid, res.imToken).then(() => {
        // IM 登录成功后跳转到会话页面
        navigate(neUiKitRouterPath.conversation)
      })
    } catch (error: any) {
      // 处理错误
      let msg = error.errMsg || error.msg || error.message || i18n.loginFailMsg
      if (msg.startsWith('request:fail')) {
        msg = i18n.loginNetworkErrorMsg
      }
      toast.info(msg)
    }
  }

  return (
    <div className="login-form-wrapper">
      <div className="navigation-bar"></div>
      <div className="login-form-container">
        <div className="login-tabs">
          {loginTabs.list.map((item) => (
            <span key={item.key} className={`login-tab ${loginTabs.active === item.key ? 'active' : ''}`}>
              <span>{item.title}</span>
            </span>
          ))}
        </div>
        <div className="login-tips">{i18n.loginTips}</div>
        <div className="login-form">
          <FormInput
            className="login-form-input"
            type="tel"
            value={loginForm.mobile}
            onChange={handleMobileChange}
            placeholder={i18n.mobilePlaceholder}
            allowClear={true}
            rule={mobileInputRule}
            addonBefore={<span className="phone-addon-before">+86</span>}
          />
          <FormInput
            className="login-form-input"
            type="tel"
            value={loginForm.smsCode}
            onChange={handleSmsCodeChange}
            placeholder={i18n.smsCodePlaceholder}
            rule={smsCodeInputRule}
            addonAfter={
              <span className={`sms-addon-after ${smsCount > 0 && smsCount < 60 ? 'disabled' : ''}`} onClick={startSmsCount}>
                {smsText}
              </span>
            }
          />
        </div>
      </div>
      <button className="login-btn" onClick={submitLoginForm}>
        {i18n.loginBtnTitle}
      </button>
    </div>
  )
}

export default LoginForm
